### ISSUE TITLE
bracket-push: input change

### ISSUE THREAD

**Issue by ilmanzo** [exercism/go#1019]
Generating bracket-push
2018/01/16 08:31:28 [LOCAL] fetching bracket-push test data
2018/01/16 08:31:28 [LOCAL] No test data found
2018/01/16 08:31:28 [REMOTE] fetching bracket-push test data
2018/01/16 08:31:28 [REMOTE] source: https://raw.githubusercontent.com/exercism/problem-specifications/master/exercises/bracket-push/canonical-data.json
2018/01/16 08:31:28 unexpected data structure: json: cannot unmarshal object into Go struct field .Input of type string
exit status 1

**Comment by ilmanzo** [comment]
Can I manage this ?

**Comment by ferhatelmas** [comment]
Go for it please :smile:
