### ISSUE TITLE
github rate limit exceeded running bin/run-generators

### ISSUE THREAD

**Issue by ilmanzo** [exercism/go#1025]
having to fetch over 100 problem specifications, if you repeat it a few times in a short time, it's easy to hit the github [rate limit](https://developer.github.com/v3/rate_limit/)

```
{
  "message": "API rate limit exceeded for <IP_ADDRESS>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

This results in errors like 

```
$ bin/run-generators
Generating acronym
2018/01/18 22:34:49 [LOCAL] fetching acronym test data
2018/01/18 22:34:49 [LOCAL] No test data found
2018/01/18 22:34:49 [REMOTE] fetching acronym test data
2018/01/18 22:34:51 json: cannot unmarshal object into Go value of type []gen.Commits
exit status 1
[FAIL]: Generator acronym gives error
```

Maybe gen.go should catch the "API rate limit exceeded" message ? Or find a way to issue authenticated requests ?

**Comment by tleen** [comment]
IIRC one way to avoid this is to checkout the problem-specification repo [as a sibling to the go repo](https://github.com/exercism/go/blob/master/gen/gen.go#L21). It will look for that local copy first before going to the API.

**Comment by ilmanzo** [comment]
You're right, I did exactly this... Maybe document this useful feature ?

**Comment by tleen** [comment]
Yep good idea.

**Comment by tleen** [comment]
On second thought will re-open this and close it when documented.
