### ISSUE TITLE
The Bracket push exercise has an unused error return

### ISSUE THREAD

**Issue by zeimusu** [exercism/go#1072]
The Bracket-push exercise requires a `(bool, error)` return value. But every test case the error value should be "`nil`". As any string can be tested for paired brackets the error return value is not required, and the Brackets function should just return a `bool`.

**Comment by tleen** [comment]
You are right. I believe back when things were less organized around common test cases there [was an error](https://github.com/exercism/problem-specifications/issues/127) used to indicate the lack of any brackets in the string.

Seems sort of ambiguous to me still based on the README. The description states:

> Given a string containing brackets [], braces {} and parentheses (), verify that all the pairs are matched and nested correctly.

To me **Given a string containing** would indicate that if the string did not have any of these it could be an error condition. I'll bump it up to the [problem-specifications repo](https://github.com/exercism/problem-specifications) and see what comes of it.
