### ISSUE TITLE
BenchmarkListSize for the Simple Linked List problem in Go hangs for a very long time

### ISSUE THREAD

**Issue by krisiasty** [exercism/go#1073]
BenchmarkListSize for the Simple Linked List problem in Go hangs for a very long time.
The function it tries to benchmark ( list.Size() )is probably too fast (in my solution it just returns the value of list.size). That results in the very large number of iterations that are needed to acurately measure the time, 
but when we also use the b.StopTimer() and b.StartTimer() functions inside the bench loop, the total time needed is much much longer. 

Since the benchmark uses the same array for each list and we only want to benchmark the list.Size() function we might just create a single list before bench loop and use that list without stopping / starting the timer.

**Comment by krisiasty** [comment]
Looks like other benchmarks using b.StopTimer() and b.StartTimer() shows similar behavior, although since the other benchmarked functions are a little bit more complicated (and slower) the number of iterations is not as high as for list.Size().

For example, BenchmarkListPush took several minutes and 3000000 iterations (516 ns/op).
The original BenchmarkListSize ran for dozen of minutes before I had to kill it, and modified version as described above took 2000000000 iterations (0.44 ns/op)

All benchmarks run on Core i3-61200U (dual core with HT) using Golang 1.9.4 on Windows 10 64-bit

**Comment by leenipper** [comment]
@krisiasty , thanks for reporting the issue.  I would be interested in your feedback regarding use of the #1074 proposed changes to the benchmark.

**Comment by krisiasty** [comment]
I put my comments under https://github.com/exercism/go/pull/1074. It's better, but still needs some fine-tuning.
