### ISSUE TITLE
SCA of golang

### ISSUE THREAD

**Issue by CodeFreezr** [exercism/go#1090]
Hello,

I love this approach of polyglot coding. Great Idea!

I 've looked a bit in the go sources.

Not sure, but GoReportCard are not such keen:  
[![Go Report Card](https://goreportcard.com/badge/github.com/exercism/go)](https://goreportcard.com/report/github.com/exercism/go)

92 Issues in 378 Files. Can you have look? 

Yours, CF

**Comment by tleen** [comment]
This is an interesting tool thanks for bringing it to our attention. A lot of these issues are things like *cyclomatic complexity* and *comments* which may be a little too nitpicky for our needs. We will have to take a closer look. Things like the formatting though this is very helpful in uncovering.

92 issues are a lot for a single GitHub issue! Perhaps you can break them down into more specific areas?

**Comment by tleen** [comment]
I'm going to close this, its an interesting tool, but until we can isolate it in a more granular fashion the report is overwhelming and in many cases do not apply.
