### ISSUE TITLE
parallel-letter-frequency: tests are easily bypassed

### ISSUE THREAD

**Issue by nolcay** [exercism/go#1114]
http://exercism.io/submissions/75420415a6b9471ba643dbf27716fda1

It speaks for itself. (That's my submission BTW)

**Comment by leenipper** [comment]
Hmm.  The test program has these two lines which probably need to be in the README.md:
```
// In the separate file frequency.go, you are given a function, Frequency(),
// to sequentially count letter frequencies in a single text.
```
If one does the intended exercise and does not alter the **_given_** Frequency() func, all is well, and a ConcurrentFrequency() which does nothing and returns true results in a test failure.
