### ISSUE TITLE
tree-building exercise fails 'duplicate node' test

### ISSUE THREAD

**Issue by devillexio** [exercism/go#1119]
The [Tree Building exercise](https://github.com/exercism/go/tree/master/exercises/tree-building) fails the `duplicate node` when you fetch the exercise. This gets in the way of solving the challenge, which focuses on refactoring a working, but slow solution.

I had to add a duplicate check to the `Build` function for the tests to pass.

Not sure if it’s correct, or preferred - 
```go
// ...
dupe := make(map[int]*Record)
for _, r := range records {
  temp := dupe[r.ID]

  if temp == nil {
  dupe[r.ID] = &r
    continue
  }

  if temp.Parent == r.Parent {
    // duplicate
    return nil, fmt.Errorf("b")
  }
}
// ...
```
I'm happy to submit a PR, but I'm also still new to Golang, so I may need some guidance on what the preferred way would be to fix the test, without detracting from what this exercise aims to achieve.

**Comment by hilary** [comment]
@devillexio would you please submit a PR, adding your code to the initial version of `Build` so it passes the tests?

The beauty of this particular issue is that the initial version of `Build` is supposed to be ugly and slow, but **working**, so all that really matters is that your code makes `Build` pass the tests.

You can grab me on the exercism slack if you need any help putting together your PR.

**Comment by devillexio** [comment]
Thanks @hilary! I've created a PR (#1155) to add the duplicate check.

Please let me know if you'd like me to change something.

**Comment by hilary** [comment]
I'm closing this issue as the initial code now passes the tests. We still have a lot of work to do with tree building, but at least we've fixed this issue 😄 Thanks again, @devillexio
