### ISSUE TITLE
get involved as co-maintainer

### ISSUE THREAD

**Issue by sebito91** [exercism/go#1122]
Hi @iHiD, @kytrinyx and @leenipper, would like to volunteer to help out as a co-maintainer on this repo if possible. Is there a process to apply?

Thanks!

**Comment by leenipper** [comment]
@sebito91 ,  Thank you!.  I appreciate your willingness to help out.  We have  been a little light on coverage lately.

I would say for the short term, simply jump in and comment on issues and PRs, and submit updates too.
Adding you as maintainer can shortly follow.  That was the path taken in my case.

**Comment by sebito91** [comment]
Wonderful, thanks for the feedback. Looking forward to helping out!
