### ISSUE TITLE
grep: move to later in the track

### ISSUE THREAD

**Issue by hilary** [exercism/go#1131]
grep is unlocked by Hamming. While a learner may be able to stumble through an ugly solution after Hamming, they'll be much more ready to write a clean solution after having mastered some of the later concepts.

**Comment by leenipper** [comment]
I agree. Need suggestion for new "unlocked by".

**Comment by hilary** [comment]
Ayup. Will do once I come up with one :)

**Comment by bitfield** [comment]
@hilary
