### ISSUE TITLE
Logo is out of date

### ISSUE THREAD

**Issue by twhitbeck** [exercism/go#1154]
I'm currently going through the Go track, and I noticed the logo is the old gopher logo. It should probably be updated to match Go's new branding.

http://blog.golang.org/go-brand

**Comment by hilary** [comment]
Nice catch!

**Comment by tehsphinx** [comment]
Just to clearify: There never was an old `gopher logo`. The old logo was this one: https://dev.to/deanveloper/the-gopher-is-not-dead-1m7k

**Comment by hilary** [comment]
Fixed by #1163
