### ISSUE TITLE
Twelve days is out of sync with specification

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/go#1165]
The specification for twelve days has been change to correct a punctuation issue.

https://github.com/exercism/problem-specifications/blob/84aa47979df7f526bdcb777cacc2c2cc9647dcaa/exercises/twelve-days/description.md

**Comment by PatrickMcSweeny** [comment]
The test and example solution still need to be updated.

**Comment by nywilken** [comment]
> This pull request did not actually resolve the issue.

@PatrickMcSweeny sorry I missed the updates to example.go and twelve_days_test.go. I thought the issue was specific to the README being out of sync with the problem specification. I see you opened a PR #1166 to fix the issue within the source and test files. I'll review it now.

**Comment by PatrickMcSweeny** [comment]
The PR I opened over a month ago fixed the README as well, I just rebased after the other one got merged.
