### ISSUE TITLE
Accumulate implementation can modify its input

### ISSUE THREAD

**Issue by dcloues** [exercism/go#1187]
While working on the Accumulate exercise I noticed that the README specifies that `Accumulate` should return a new collection, but the tests don't enforce this. I cheated and wrote a solution that modifies its input in-place: https://exercism.io/tracks/go/exercises/accumulate/solutions/ed63d071f51f40678e7ff1e4620590b1

I think it would be neat to check for this, because it would help folks think about the implications of modifying input data. I tested a change for the test to accomplish this - let me know if you'd like me to submit a PR! I also saw some other issues indicating that there's a plan to deprecate this exercise at some point, so I'd totally understand if you'd prefer to just leave it alone.

Thanks for making Exercism 😸

**Comment by kytrinyx** [comment]
> My hot take is no.

Agreed.

> I say let a thousand side exercises bloom!

Haha, yes you certainly have a point.

OK, so shall we override the README instructions to leave the in-place or new data structure up to the person solving it?

**Comment by bitfield** [comment]
This is a functional-_style_ exercise, even if we're not doing it in a functional language, so it seems like returning a new collection is in the _spirit_ of the exercise—and that's what the README says, right now.

I think it's fine to leave the wording as it is, and close this issue as "After very careful consideration, and with some regret, won't fix."

**Comment by kytrinyx** [comment]
> I think it's fine to leave the wording as it is, and close this issue as "After very careful consideration, and with some regret, won't fix."

I think that's probably fine. One question before we do: does this decision add a burden to the maintainers to continuously have the same conversation over and over with people? If so, is it a good conversation to have?

**Comment by bitfield** [comment]
What conversation are you thinking of? About this exercise in particular, or the general issue of whether tests should or shouldn't enforce strict compliance with the exercise instructions, as well as correctness?

**Comment by kytrinyx** [comment]
> What conversation are you thinking of? About this exercise in particular, or the general issue of whether tests should or shouldn't enforce strict compliance with the exercise instructions, as well as correctness?

I was thinking of this exercise in particular.

I don't think that we should enforce strict compliance with exercise definitions in problem-specifications, but I do think that we should be careful to ensure that our instructions are correct and not confusing, and where necessary override any of the bits and pieces that would help clarify.

Closing, thanks for discussing, all!
