### ISSUE TITLE
Suggestion: change name of user-written function in reverse-strings.

### ISSUE THREAD

**Issue by sbromberger** [exercism/go#1230]
Right now, the reverse-strings exercise does not include a stub. That's not a problem, but a quick glance at the `reverse_string_test.go` shows a source of confusion. There are three functions defined in that file:
1. `TestReverse()` on line 8,
2. `TestReverseOfReverse()` on line 18, and
3. `BenchmarkReverse()` on line 27.

A novice (read: someone who's working on these problems as a user) would therefore assume that the function that s/he needs to write should be named `Reverse()`, since the purpose of the function is to reverse a string, and all the test functions refer to something called `Reverse` in their names.

However, the actual function the user is expected to write is called `String()` (as evidenced by the calls on lines 10, 20, and 30 of the test file).

I would suggest that function that the user is required to create, `String()`, should be changed to `Reverse()`. Not only does this make things consistent with the test file and more intuitive, but it is a more appropriate name for a function that reverses a string, and since we're focusing on programming style as well as substance, perhaps we should encourage the use of meaningful function names.

**Comment by bitfield** [comment]
Agreed, the student's function should be named Reverse(), and that's what the test code should call. PRs welcome!

**Comment by sbromberger** [comment]
Ref: #1231
