### ISSUE TITLE
Go 1.12 exports io.StringWriter, should the tournament exercise be updated

### ISSUE THREAD

**Issue by aarti** [exercism/go#1235]
https://github.com/golang/go/commit/112f28defcbd8f48de83f4502093ac97149b4da6#diff-3908a096d6ac2c353be898fcf92929f9

**Comment by kytrinyx** [comment]
I think the answer is "probably, yes".

Would you mind writing down some quick thoughts about how you think the tournament exercise should be changed, so that it's easier for someone else to pick this one up?

**Comment by leenipper** [comment]
A side note - Consider doing this after Go 1.13 is released, since [travis](https://github.com/exercism/go/blob/master/.travis.yml#L21-L22) tests with 1.11.x and 1.12.x at present.

**Comment by ferhatelmas** [comment]
Since there is no more activity and existing implementation gives more flexibility, there is no need to update, IMHO.

While checking it, saw we could use `sort.Slice` though, updated via #1310.

Closing this to be cleaner, but if you think we could improve, please let me know.
