### ISSUE TITLE
Proposal to add "go.mod" file to Go exercises

### ISSUE THREAD

**Issue by BattleBas** [exercism/go#1256]
I would like to propose for each Go exercise that there should be a "go.mod" file included. The exercises aren't added into GOPATH by default and without a "go.mod" file the Visual Studio Code Go extension fails to function correctly (Not running gofmt for example, which was the issue I was having).

These exercises don't have dependencies they need to manage, but the following Q&A supports that it is still a good idea to have a "go.mod" file:
[Should I still add a gomod file if I do not have any dependencies?](https://github.com/golang/go/wiki/Modules#should-i-still-add-a-gomod-file-if-i-do-not-have-any-dependencies)

What do you think? Is this a good idea? Thanks.

**Comment by kellydanma** [comment]
Is there not already a `go.mod` file added when you download a new exercise? I just ran `exercism download --exercise=error-handling --track=go` from VSCode and the exercise contains a `go.mod` file under the `error-handling` directory.

The VSCode go extension also works correctly. For reference, I am running a linux subsystem on Windows 10. 

This issue should be closed.

**Comment by tehsphinx** [comment]
Correct. We added them a while back.
