### ISSUE TITLE
Exercise on idiomatic enumeration

### ISSUE THREAD

**Issue by udhos** [exercism/go#1273]
Hi gophers,

How about adding a basic exercise on how to handle idiomatic enumeration in Go?

I am thinking of this:

Stackoverflow: https://stackoverflow.com/questions/14426366/what-is-an-idiomatic-way-of-representing-enums-in-go

Playground: https://play.golang.org/p/bRwg0N-TLMI

**Comment by bitfield** [comment]
Actually, I think the best way to represent these is with rune literals: `'A', 'C', 'T', 'G'`!

Perhaps we can think of an example problem which requires something a bit more complicated.

**Comment by udhos** [comment]
@bitfield Yes, in order to illustrate the case for the enumeration I added names for the bases and the option to scan the elements:

https://play.golang.org/p/bRwg0N-TLMI

However I see that an actual problem/exercise would make the case better.

**Comment by junedev** [comment]
We have a concept exercise `savings-account` now that covers the topic of idiomatic enumeration. It just needs a bit more work before it can go live (see https://github.com/exercism/go/issues/1583).
