### ISSUE TITLE
space-age: missing type upon exercise download

### ISSUE THREAD

**Issue by Anmol-Sharma** [exercism/go#1293]
There is a small bug in the exercise Space Age. When one downloads the problem and tries to test the solution. There is an error:

```# space [space.test]
./cases_test.go:9:14: undefined: Planet
FAIL	space [build failed]
```

The file **cases_test.go** shows the following : 

```
package space

// Source: exercism/problem-specifications
// Commit: 28b3dac0 space-age: restrict seconds to fit within 32-bit int range
// Problem Specifications Version: 1.2.0

var testCases = []struct {
	description string
	planet      Planet
	seconds     float64
	expected    float64
}{
	{
		description: "age on Earth",
		planet:      "Earth",
		seconds:     1000000000,
		expected:    31.69,
	},
	{
		description: "age on Mercury",
		planet:      "Mercury",
		seconds:     2134835688,
		expected:    280.88,
	},
	{
		description: "age on Venus",
		planet:      "Venus",
		seconds:     189839836,
		expected:    9.78,
	},
	{
		description: "age on Mars",
		planet:      "Mars",
		seconds:     2129871239,
		expected:    35.88,
	},
	{
		description: "age on Jupiter",
		planet:      "Jupiter",
		seconds:     901876382,
		expected:    2.41,
	},
	{
		description: "age on Saturn",
		planet:      "Saturn",
		seconds:     2000000000,
		expected:    2.15,
	},
	{
		description: "age on Uranus",
		planet:      "Uranus",
		seconds:     1210123456,
		expected:    0.46,
	},
	{
		description: "age on Neptune",
		planet:      "Neptune",
		seconds:     1821023456,
		expected:    0.35,
	},
}
```

The planet datatype should be `string` and not `Planet`. There is no such custom data-type defined.

**Comment by LDODen** [comment]
As for my opinion we shouldn't change planet datatype to `string`, but simply move 'Planet' type definition to space_age.go file. When one downloads the problem, he also downloads space_age.go with preset type definition, and it will prevent error, mentioned by You

**Comment by Anmol-Sharma** [comment]
@LDODen converting to string is the most simplest of the solutions. Yes, we can move the definition of **Planet** type to space_age.go but the I don't think there is anything else to be added to that data-type instead of just a Name identifier. 

Either way, this bug is very easy to fix, but not sure, if exercism are actively monitoring this repo. as I pointed this out more than 2 months ago and there has been almost no response/action.

**Comment by LDODen** [comment]
Yes, this is seems as simpliest way, but in this way we should also refactor  `example.go`, which contains a solution based on `Planet` type

**Comment by Anmol-Sharma** [comment]
@LDODen see this line : https://github.com/exercism/go/blob/c545db854be41530ec3f70b29ce3823a08c73000/exercises/space-age/example.go#L4

They've already declared Planet as type string

**Comment by ferhatelmas** [comment]
Sorry, for the late reply here. Maintainers were away, should be more timely responses from now on.

Here, planet type was added, just to make the exercise more difficult. That's why changing type back to string would be moving backwards.

My suggestion is similar to @LDODen but instead of moving, we should copy. Then, while testing stub file is ignored and we have a working implementation to satisfy tests but also users won't see this error message either.

How does it sound? Would you like to send a PR?

**Comment by Anmol-Sharma** [comment]
Sure. I'll send a PR in a bit.

**Comment by LDODen** [comment]
It will be one type declared twice in one package.

**Comment by ferhatelmas** [comment]
Yes, but while testing stub is ignored. When downloaded, example is ignored so users see only one of them at a time.

**Comment by ferhatelmas** [comment]
While checking https://github.com/exercism/go/pull/1299, saw meetup exercise has also similar issue but it has a [comment at least](https://github.com/exercism/go/blob/master/exercises/meetup/meetup_test.go#L5).

**Comment by ferhatelmas** [comment]
resolved by https://github.com/exercism/go/pull/1301
