### ISSUE TITLE
matrix: test file refers to nonexistent instructions

### ISSUE THREAD

**Issue by nickgrim** [exercism/go#1294]
`matrix_test.go` [states near the top](https://github.com/exercism/go/blob/master/exercises/matrix/matrix_test.go#L4-L5):
> You must implement a constructor and methods Rows() and Cols() as described in the README…

…but there is no such description - or even any clues as to the expected API - [in the README](https://github.com/exercism/go/blob/master/exercises/matrix/README.md). As it is, a user has to derive the expected API from the test failures.

One possibility would be to write the obviously-missing description, but a better one might be to add stubbed-versions of the expected API to `matrix.go`.

**Comment by kellydanma** [comment]
I agree, I had a lot of difficulty deciphering the API in this problem. I would be willing to elaborate on the README or add stubbed-versions to the expected API if others agree this needs to be addressed!

**Comment by tehsphinx** [comment]
@kellydanma: Note that there is a kind of hold on fixing the current exercises because we focus on building v3 right now. If you want to get involved on `v3` feel free to contact us! https://exercism.io/blog/call-for-maintainers-2020

**Comment by kellydanma** [comment]
@tehsphinx Thanks for letting me know! I won't work on anything before the v3 changes. I'm currently in a tough semester at school and don't think I can dedicate 3 hours / week. Once the semester is finished, I will have more time to help.

**Comment by tehsphinx** [comment]
@kellydanma no problem. We would not require those 3 hours a week. That is more for the core team members that lead the v3 efforts.
