### ISSUE TITLE
prime-factors: fails despite valid output

### ISSUE THREAD

**Issue by JackMordaunt** [exercism/go#1295]
Since the test file use `reflect.DeepEqual`, the slice values must appear in the exact same order to be considered equal. This is poor behaviour because the requirements do not specify ordering. 

Thus `int64[]{2, 3, 2}` fails for the expected output `[]int64{2, 2, 3}`. 

Solution: 
1. Custom implementation of equality that doesn't rely on order.
2. Sort the slice before using `reflect.DeepEqual` in the test harness.

**Comment by ferhatelmas** [comment]
@JackMordaunt there is [a comment on test file](https://github.com/exercism/go/blob/master/exercises/prime-factors/prime_factors_test.go#L3). However, there is no mention of an order in exercise description so sounds good to fix this implementation issue.

Are you up for a PR?
