### ISSUE TITLE
Recruiting additional maintainers for Go

### ISSUE THREAD

**Issue by kytrinyx** [exercism/go#1304]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by sebito91** [comment]
I'm an existing maintainer but haven't been holding my weight over the past few months. I'm committing myself to 2-3hrs/week over the next few months!

**Comment by Prounckk** [comment]
Hi, I'd like to be part of this!

**Comment by tehsphinx** [comment]
I'll also like to be part of this!

**Comment by hans-d** [comment]
I'd like to be part of it as well. 
Same handle on exercism, mentoring on go, and known to @tehsphinx as well, and already diving into some of the code involved.

**Comment by ZoltanOnody** [comment]
Hi, I'd like to contribute as well.

I'm a Software Engineer at Exponea, where I'm working on a proprietary database engine for real-time data analyses. I'm working mostly with C++, Go, Python and k8s. My handle on exercism is `ZoltanOnody` and I've been mentoring the Go track in the past.

I'd like to become a Go track maintainer:
- to improve my Go skills (by working on problems outside of my domain),
- to give back to the Go community,
- to work on something useful in my free time (I really like the Exercism's mission),
- and to contribute to opensource.

I would be able to dedicate 4-6hours/week.

**Comment by lloyddewit** [comment]
I'd like to contribute. I'm a mentor on the Exercism Go track.

**Comment by da-edra** [comment]
I'd love to contribute with this!

**Comment by andres-zartab** [comment]
Hi everyone! 

I'm a Data Scientist who decided to learn Go to improve my software development skills and ended up loving it. Currently I'm a mentor on the Go track and new to open source, but I'm eager to learn and would love to contribute as well.

**Comment by leenipper** [comment]
Katrina,

The v3 does sound very interesting.
But for now, I'm in this category: "still want to be a maintainer and just
help where you can".

**Comment by mcaci** [comment]
Hello Katrina,

I would be quite happy to join the maintainers group. My Exercism handle is "nikiforosFreespirit". I am a C++ developer switching to Go in the latest year. I have completed Exercism's Go main track and I keep doing side exercises from time to time. I also work on some personal projects on Github written in Go to keep improving my skills.
I would be able to dedicate 2/3 hrs per week to it.

**Comment by DavyJ0nes** [comment]
Hey,

I'd like to volunteer as well.

I've been using Go as one of my main programming languages for about 4 years. Currently I work as a Software Engineer writing backend services and automation tooling using Go for a fintech company.

I've used Exercism off and on for a couple of years and recommend it to anyone wanting to up-skill in a language.

I want to be a Exercism Go track maintainer to:
- Give something back to the Go community and share my passion for the language.
- Help develop people new to the language and improve my teaching and mentoring skills.
- Be part of a project that I have a lot of respect for and have gotten a lot out of.
- Learn from others

I will be able to give about 4 - 7 hours a week to this.

Cheers! 😄

**Comment by l0nax** [comment]
I'd like to become an additional maintainer of the `go` exercism's.

**Comment by ilknarf** [comment]
Hi, I'd like to be a part of this!

**Comment by iHiD** [comment]
@ilknarf Great. What's your Exercism handle?

**Comment by ilknarf** [comment]
@ilknarf

**Comment by oanaOM** [comment]
Hi,

I would like to be help as well.

I currently work as a frontend developer for a fintech company and a few months ago I’ve decided to learn Go and fall in love with it especially after starting Go main track on Exercism.  Besides the knowledge, I think this platform offers a unique empathy feeling that none of the other learning platform offer. 

I’m eager to learn more so I’m committing myself  to 3-4h/weeks over the next few months and it would be my pleasure to contribute to this community to help out as much as I can with version 3  and not only.

**Comment by tehsphinx** [comment]
@oanaOM: are you on exercism slack? What is your handle there?

**Comment by oanaOM** [comment]
@tehsphinx no, I'm not on slack at the moment. Please let me know how to get access to it.

**Comment by iHiD** [comment]
@oanaOM Thanks! :) @ErikSchierboom will drop you an email tomorrow with details!

**Comment by ErikSchierboom** [comment]
@oanaOM You have an email in your inbox with the information on how to contribute to the Go track. Thanks for wanting to help!

**Comment by Vaibhavi24** [comment]
Hi all,

I'm experienced in C++, Java, Python, Flask, Angular etc. Picked the ropes of programming in High School and have been a passionate programmer ever since.

Currently, I'm learning Go along with strengthening my CS fundamentals. I've been actively involved in Open Source communities and have mentored for OS programs like Google Summer of Code, Google Code-In, LearnITGirl before. I'd attended GopherconEU'19 and KubernetesDayIndia'19 on full scholarship too.

I want to contribute as a maintainer for the Go track. Feeling really excited to be a part of the learning process of so many on exercism :) 

Thanks to @kytrinyx and @iHiD for this wonderful project!

**Comment by vmanikes** [comment]
Hello Guys, I am Venkata. I am a Full-Time DevOps and Software Engineer. I am an experienced Go lang developer and I maintain ~15 Go microservices in production and have my own web framework written in Go called Cyclops(https://github.com/flannel-dev-lab/cyclops). I am ready to help and I am willing to commit to 10 hours a week.

I like exercism and I have a few ideas that I want to put in to make it much better and also I want to work with other great minds to be more proficient in Go

Here is my exercism [handle](https://exercism.io/profiles/vmanikes)

**Comment by PauloJoseBR** [comment]
Hello Everyone. I'm a Full-Time Software Engineer at a Brazilian Software Consulting company.
I have a reasonable experience in developing enterprising level software using .NET Core, Azure, Xamarin and Microsoft Stacks. 
I have several reasons why I wish to contribute on this amazing project! 

- I believe in this project. Professional education is one of the best ways is to fight poverty in developing countries.
- I'm jumping in Open Source and I choosed this project to contribute. This is going to be my first one. 
And...
- I need and I will master GoLang.

Thank you guys for such an oportunity.
When and How Can I Start?

**Comment by Lumexralph** [comment]
Hi guys! I am Olumide ([Exercism handle](https://exercism.io/profiles/Lumexralph)), I am a Fullstack Software Engineer with experience in Go, Javascript, Typescript, Python, and very little in Rust. Exercism helped me learn Rust and I am very excited about this opportunity which will give me the chance to give back as a Go maintainer and also learn from the awesome team.

I am very interested and would love to join the Go maintainer team, here's why:

* I am an active Go contributor to some open source projects like [pomerium](https://github.com/pomerium/pomerium), [mattermost](https://github.com/mattermost), and recently [pion](https://github.com/pion).

* I want to be proficient in Go, and working with the amazing people in the team and this project will give me such an opportunity to learn more.

* Exercism is doing awesome work in helping people learn easily and I want to be part of the team that keeps the project alive.

Thank you guys, I would like to know the next step in making this happen.

**Comment by tehsphinx** [comment]
@ErikSchierboom

**Comment by ErikSchierboom** [comment]
@Lumexralph That's great! The first thing to do is to submit a PR to https://github.com/exercism/go/blob/master/config/maintainers.json to add yourself to the list of maintainers. Once this is merged, you'll have the proper permissions as a Go maintainer.

We're currently building v3 of Exercism, which has tons of really exciting new stuff and where we could really use the help. Could you send an email to me: erik.schierboom at exercism.io  I'll then send you all the information on how to get started with being a Go maintainer. 

Once again, thanks for wanting to become a maintainer! We greatly appreciate it.

**Comment by ErikSchierboom** [comment]
@PauloJoseBR The exact same goes for you! Thanks for wanting to become a maintainer. See the above comment for details on how to proceed.

**Comment by iHiD** [comment]
Also please email erik@exercism.io and he can add you to our Slack 🙂

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our push to implement the v3 version of this track and v3 has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

New maintainer are always welcome though!
