### ISSUE TITLE
ci: consider moving to github actions

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/go#1311]
Right now, head forward isn't clear due to upcoming v3 preparation but it seems that:

* travis future isn't clear
* github actions is fast
* github actions enables easier maintenance (one place, easier configuration, etc.)

That's why moving to github actions might be an improvement in the long run.

**Comment by stanleynguyen** [comment]
hey @ferhatelmas can I take up this one?

**Comment by ferhatelmas** [comment]
@stanleynguyen sorry for the late reply, I was away. 

It seems #1364 took care of it. 

Feel free to take something else and I will be around to help though. 

Either way, thank you for asking and offering help :+1:
