### ISSUE TITLE
listops_test undefined errors

### ISSUE THREAD

**Issue by SoloJ** [exercism/go#1324]
Im not sure if i am missing something but the test for listops fails to run for me with the following errors:

# listops [listops.test]
./listops_test.go:11:11: undefined: binFunc
./listops_test.go:13:11: undefined: listops
./listops_test.go:87:11: undefined: predFunc
./listops_test.go:123:11: undefined: IntList
./listops_test.go:155:11: undefined: IntList
./listops_test.go:156:11: undefined: unaryFunc
./listops_test.go:157:11: undefined: IntList
./listops_test.go:190:11: undefined: IntList
./listops_test.go:191:11: undefined: IntList
./listops_test.go:222:13: undefined: IntList
./listops_test.go:222:13: too many errors
FAIL    listops [build failed]

**Comment by ferhatelmas** [comment]
How are you running it?

**Comment by SoloJ** [comment]
I am on OSX 10.15.2
i am go version go1.13.6 darwin/amd64
I am running this test with the [go test] command

**Comment by ferhatelmas** [comment]
OK, you're working on downloaded exercise, not on this repo. These are types you need to define but stub should guide you, added more clarification.

**Comment by SoloJ** [comment]
Thanks!
