### ISSUE TITLE
scale-generator missing description of C scale

### ISSUE THREAD

**Issue by SoloJ** [exercism/go#1327]
Unless i am misunderstanding, it appears that the first test case gives "C" and expects a sharp scale bus that is not described as expected behavior in the sharps reference within the readme:

in the Readme:
Use Sharps:
G, D, A, E, B, F# major
e, b, f#, c#, g#, d# minor

In cases_test.go
description: "Chromatic scale with sharps",
		tonic:       "C",
		interval:    "",
		expected:    []string{"C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"},

**Comment by b10s** [comment]
According to the "Instructions" (Readme in your terms): `No Sharps or Flats: C major a minor`.
I would ask what does it mean `no Sharps or Flats` ?
