### ISSUE TITLE
Largest Series Product: why LargestSeriesProduct(, 0) wants 1 ?

### ISSUE THREAD

**Issue by b10s** [exercism/go#1331]
Hi,

the `LargestSeriesProduct(, 0)` wants `1` as a result but product of nothing can not be 1, isn't it ?

**Comment by tehsphinx** [comment]
This is a definition thing. You can find the explanation in the original test cases in the problem-specification repository here: https://github.com/exercism/problem-specifications/blob/master/exercises/largest-series-product/canonical-data.json#L107
