### ISSUE TITLE
Protein Translation: task description, "codon to amino acid" table improvement

### ISSUE THREAD

**Issue by b10s** [exercism/go#1332]
I'm not sure but seems in the "codon to amino acid" table the amino acid column should have title "amino acid" instead of "Protein":

![Selection_159](https://user-images.githubusercontent.com/4618288/74581933-e030ce00-4ff8-11ea-81c8-13d174881675.png)

prove:
![Selection_160](https://user-images.githubusercontent.com/4618288/74581925-bc6d8800-4ff8-11ea-86d5-1b8c863ee8cc.png)

**Comment by tehsphinx** [comment]
This belongs in the `problem-specification` repository as this is the same in all languages.

@b10s can you recreate the issue there? I'd also mention which exercise you are talking about somewhere. That makes it easier to find. The exercise is `protein-translation`.

**Comment by tehsphinx** [comment]
Here the link to the file in the `problem-specification` repo:

https://github.com/exercism/problem-specifications/blob/master/exercises/protein-translation/description.md
