### ISSUE TITLE
Access Denied: BUILD FAILED 

### ISSUE THREAD

**Issue by Sagr859** [exercism/go#1338]
I completed nearly 8 exercises until now, using **Visual Studio** Code and **Go extensions**. But recently it started to malfunction. Whenever I start a new terminal and try to run the .go code using `go test` command it hangs up a few seconds and disappears. I tried the same using CMD in Administrative and returned:
```
open C:\Users\Hp\AppData\Local\Temp\go-.....\..test.exe: Access is denied.
FAIL   program_name [build failed]
 
```
It started to reflect in all other programs too.
I have installed Golang separately in my system ( Windows 10 ) and it works fine. So it's something wrong with Exercism and not GOPATH. 

It started after the completion of nucleotide_counts and while doing the raindrops questions.

Posted twice accidentally: https://github.com/exercism/cli/issues/926#issue-601793350

**Comment by tehsphinx** [comment]
If you can't run `go test` it is not a problem with exercism. It also does not have to do with "not GOPATH" as we have `go.mod` files in every exercise which makes putting the exercises in the GOPATH obsolete.

I'm not sure if I understood the problem correctly so here a few questions:
- are you talking about 2 computers/notebooks? One windows 10, the other is ...?
- or are you talking about different command lines? One in VSCode, one CMD (windows console?) in administrative mode, another (installed Golang seperately?) one?
- what do you mean by "installed Golang separately"? You should always completely uninstall Go an old version if you e.g. want to update.

**Comment by Sagr859** [comment]
nop.. There is just one laptop with Windows10 where I do all my stuffs.
yup, I have been doing all my previous exercises in VS Code and inbuilt terminal in it. Since when I try to run the go test command it just disappears without any error reports, I tried the same command in CMD in administrative mode in the proper path. That gave me an error, saying it's failing the build of .exe file. 
Installed Golang separately was did way before I even started Exercism. while starting Exercism I accidentally ended up installing it again. But it worked fine because I kept it as a backup.

The thing is that it just started crashing every Exercism programs I'm trying to run using the go test command. Because when I first came across this problem I tried running the old ones (previous completed exercises) which failed too. But when I tried running a simple Go program with the same CMD, it worked fine. Here is where I used the 'separately' installed Golang.

**Comment by tehsphinx** [comment]
I can't help much I'm afraid as I am not on windows. But I can tell you my thoughts on this and some background knowledge:

When using `go run`, Go will build an executable in a temp folder, in your case probably C:\Users\Hp\Appdata\Local\Temp. Then it will run that executable. 
When using `go test` it does the same, just that it build an executable containing the tests and the code needed to run the tests.

For some reason after building this executable for the tests, the Go command is not able to execute the file it just built -- which is kind of strange as the go command had access to write the file (at least that is what it looks like). What is even stranger is that `go run` obviously does not have a problem executing it's own creation.

What I would do:
- remove all versions of Go as described here: https://golang.org/doc/install?download=go1.14.2.windows-amd64.msi#uninstall. If you actually have 2 separate version installed, make sure you delete everything and remove all paths involved. If you have projects in GOPATH move them somewhere else and remove the GOPATH as well.
- re-install the latest version of Go

**Comment by mikejgray** [comment]
I also ran into this issue after upgrading to Windows 10 2004 (Insiders Build). I've been running my tests in a Docker container to work around it but I suspect Microsoft has changed permissions in the AppData folder. I tried removing all versions of Go and re-installing the latest version and continued to have the same problem.

**Comment by Sagr859** [comment]
Thanx Guys. I think its now working fine. My anti-virus finally reported the issue and I figured that some virus named 'gen : variant cerbu 70524' got into the build files. So I removed all the go updates reinstalled them. I did the same for the Exercism files and the build files in the Temp folder.

So now I'm closing all those issues links... Thank you guys!!
