### ISSUE TITLE
Protein Translation issue

### ISSUE THREAD

**Issue by iHiD** [exercism/go#1361]
Hello. I was sent this the email below. I've asked for him to send me his code, and I'll add it if he does so, but I thought I'd raise this in case anything jumps out anyway.

---

Dear Exercism team

I think the test suite of the "Protein Translation" side exercise in the
Go track is broken. My code shouldn't succeed but does anyways. Just not
sure where to report / how to fix it. The `if test.errorExected != nil
{` section never comes back true.

I'm not having an account on Github, out of ethical reservations against
that platform, so wouldn't be able to submit an issue there, should that
be the place to do it, but thought I should make you aware nevertheless.

Thanks

**Comment by GLOFonseca** [comment]
Hi, can you give me access to this exercise? I would like to look closer.
My exercism.io io user is the same as GitHub, GLOFonseca.

**Comment by GLOFonseca** [comment]
I've looked at the test and everything looks fine and working. 
But when you have the code from him please let me know!

**Comment by iHiD** [comment]
Here you go:
```
package protein

var codons = map[string]string{
	"AUG": "Methionine",
	"UUU": "Phenylalanine",
	"UUC": "Phenylalanine",
	"UUA": "Leucine",
	"UUG": "Leucine",
	"UCU": "Serine",
	"UCC": "Serine",
	"UCA": "Serine",
	"UCG": "Serine",
	"UAU": "Tyrosine",
	"UAC": "Tyrosine",
	"UGU": "Cysteine",
	"UGC": "Cysteine",
	"UGG": "Tryptophan",
}

var stops = [...]string{"UAA", "UAG", "UGA"}

var ErrStop error
var ErrInvalidBase error

func FromCodon(codon string) (string, error) {

	return codons[codon], nil

}

func FromRNA(rna string) ([]string, error) {

	codon := make([]string, 0)
	lo := 0
	hi := 3

	for x := 1; x <= len(rna)/3; x++ {
		candidate := rna[lo:hi]

		if codons[candidate] == "" {
			break
		}

		codon = append(codon, codons[candidate])
		lo += 3
		hi += 3
	}

	return codon, nil
}
```

He commented: 
> I'm never using ErrStop or ErrInvalidBase, nevertheless it passes the test.

**Comment by GLOFonseca** [comment]
I'll check in the next days.
Thanks!

**Comment by GLOFonseca** [comment]
So I think the problem is with his code.

The test is passing, but his code declares the two errors variables but without value:
```go
var ErrStop error
var ErrInvalidBase error
```

So both variables are nil, not entering this condition:
```go
if test.errorExpected != nil {
	if test.errorExpected != err {
		t.Fatalf("FAIL: Protein translation test: %s\nExpected error: %q\nActual error: %q",
			test.input, test.errorExpected, err)
	}
} 
```

**Comment by GLOFonseca** [comment]
But I agree that maybe the test could be failed even with this scenario. One solution could be to create a new field on **codonCase** struct, like a boolean for check if an error is expected or not, and not use the same field for this and for the error value.

What do you think @iHiD? I can create a PR for this.

**Comment by GLOFonseca** [comment]
Actually, I was implementing that and I've noticed that the real problem is that the test is using the error declared on the actual function to compare with the returned one. So even with another boolean field, the problem occurred.

I've created a PR with a solution (#1365) that creates mock variables for these errors.

**Comment by iHiD** [comment]
Sweet. Thanks @GLOFonseca!
