### ISSUE TITLE
[V3] Implement new Concept Exercise: `range-iteration`

### ISSUE THREAD

**Issue by tehsphinx** [exercism/go#1381]
This issue describes how to implement the `range-iteration` concept exercise for the Go track.

## Goal

The goal of this exercise is to make the student familiar with the `range` loop on `slices` and `maps`.

## Things to teach

- iterate a `slice` with a `range` loop
- iterate a `map` with a `range` loop
- omit the index with `_`
- omit the value by just providing one variable (don't use `_` to omit the value!)
- omit both, index and value
- random order of `map` iteration

## Things not to teach

- channel iteration
- string iteration

## Concepts

- `range-iteration`

## Prerequisites

- `slices`
- `maps`
- `iteration`

## Implementing

Here you can find the [Implementation Guide](https://github.com/exercism/v3/blob/master/languages/go/docs/implementing-a-concept-exercise.md).

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

**Comment by bobtfish** [comment]
Should this issue be closed, as the `range-iteration` exercise was merged a while ago :)
