### ISSUE TITLE
[v3] Configure online editor

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1393]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

In Exercism v3, students can now choose to work on exercises directly from their browser, instead of having to download exercises to their local machine. The track-specific settings for the in-browser editor are defined in the top-level `"online_editor"` field in the track's `config.json` file. This field is defined as an object with two fields:

- `"indent_style"`: the indent style, either "space" or "tab".
- `"indent_size"`: the indent size, which is an integer (e.g. 4).

You can find a full description of these fields in [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#metadata).

## Goal

The `"online_editor"` field should be updated to correspond to the track's best practices regarding indentation.

## Example

```json
"online_editor": {
  "indent_style": "space",
  "indent_size": 4
}
```

## Tracking

https://github.com/exercism/v3-launch/issues/2

**Comment by voroskoi** [comment]
This is already set for go:
```
"online_editor": {
  "indent_style": "tab",
  "indent_size": 4
}
```

I think it can be closed.
