### ISSUE TITLE
Build Test Runner

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1398]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

In Exercism v3, one of the biggest changes is that we'll automatically check if a submitted solution passes all the tests.

We'll check this via a new, track-specific tool: the [Test Runner](https://github.com/exercism/v3-docs/tree/main/anatomy/track-tooling/test-runners). Each test runner is track-specific. When a new solution is submitted, we run the track's test runner, which outputs a JSON file that describes the test results.

The test runner must be able to run the tests suites of both [Concept Exercises](https://github.com/exercism/v3-docs/blob/main/product/concept-exercises.md) and [Practice Exercises](https://github.com/exercism/v3-docs/blob/main/product/practice-exercises.md). Depending on the test runner implementation, this could mean having to update the Practice Exercises to the format expected by the test runner.

## Goal

Build a test runner for your track according to [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/test-runners/interface.md).

If you are building a test runner from scratch, we have a [starting guide](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/test-runners/creating-from-scratch.md) and a [generic test runner](https://github.com/exercism/generic-test-runner/) that can be used as the base for the new test runner.

If a test runner has already been built for this track, please check if it works on both Concept Exercises _and_ Practice Exercises.

It can be very useful to check how [other tracks have implemented their test runner](https://github.com/search?q=org%3Aexercism+test-runner&type=repositories).

## Tracking

https://github.com/exercism/v3-launch/issues/4

**Comment by ekingery** [comment]
[Test runner has been built](https://github.com/exercism/go-test-runner), still need to check that it works on Concept and Practice Exercises.

**Comment by ErikSchierboom** [comment]
I think this issue can be closed as there is a working version of the test runner. Note that the test runner itself can be improved, but that does not preclude this issue from being closed as test runner improvements can be handled in the test runner repo.
