### ISSUE TITLE
Go Exercise Largest Series Product Wrong Testcase Error Description

### ISSUE THREAD

**Issue by deepaksathya** [exercism/go#1434]
Hi,

```go
var tests = []struct {
	digits  string
	span    int
	product int64
	ok      bool
	error   string
}{
	{"", 0, 1, true, ""}, // Testcase 1
	{"123", 0, 1, true, ""}, // Testcase 2
	{"", 1, -1, false, "span must be smaller than string length"}, // Testcase 3
	{"12345", -1, -1, false, "span must be greater than zero"}, // Testcase 4
}
```

If  you see above the 2nd parameter is span. Testcases 1 and 2 are passing with  span equal "0".

But if you refer Testcase 4 the error expected says "span must be greater than zero". It should be actually "span must not be a negative number". If  we say "span must be greater than zero", then Testcase 1 and 2 should also not pass.

**Comment by iHiD** [comment]
@ekingery Thanks :) I've moved this to the Go repository for you :)

**Comment by deepaksathya** [comment]
Thanks. Does it mean nothing more is required from my side?

**Comment by iHiD** [comment]
@deepaksathya You can fix it if you like and get the credit for the change 🙂 

To do that edit [this file](https://github.com/exercism/go/blob/811db944679d14855027f9ecfd20a8f6da20070a/exercises/practice/largest-series-product/cases_test.go) and create a PR referencing this issue (you can do all that via the GitHub UI)

**Comment by deepaksathya** [comment]
I pushed the changes to my github repo and created a PR. Thanks for giving the first time opportunity to do a PR. Opportunity itself a credit for me ;-)

**Comment by deepaksathya** [comment]
Closes
