### ISSUE TITLE
Anagram: add test case with UTF8 characters

### ISSUE THREAD

**Issue by CoderYihaoWang** [exercism/go#1451]
In Go, strings are made of UTF8 runes. Therefore, it is not appropriate to assume strings as just English letters, unless it is explicitly said so in the description. 

However, in the exercise Anagram, the test cases only cover English letter strings, although "你好" and "好你" should also be treated as anagrams. This encourages some "clever" solutions using `[26]int` to represent a word, which I think is theoretically wrong, as strings are not a collection of English letters.

Perhaps we should add some test cases to this to capture these scenarios. Also some descriptions could be added for corner cases (e.g. how to treat punctuations? etc)

Or we can specify in the description that the input strings only contain English letters. However, in that case, the better type to use would be `[]byte` instead of `string`.

**Comment by eklatzer** [comment]
Hey, as we discussed adding additional in #1892, this issue could be continued

**Comment by junedev** [comment]
Yes! The documentation how to add custom test cases can be found here: https://github.com/exercism/go#tests

**Comment by eklatzer** [comment]
@CoderYihaoWang Do you want to add test cases?

**Comment by CoderYihaoWang** [comment]
Thanks for letting me know @eklatzer, and glad to know that custom test cases are supported now. I will have a look and add those tests soon :)
