### ISSUE TITLE
Syllabus -> Constants = blocked by "Comments" but "Comments" not visible.

### ISSUE THREAD

**Issue by goatthinking** [exercism/go#1495]
While going through the Syllabus I completed the following concepts:
* Basics
* Nil
* Zero Values
* Booleans
* Strings

My next concept would be "Constants" which shows as Locked w/ message: `Learn Basics, Comments, and Strings to unlock this concept.`

However, there is no "Comments" available to do. While looking at things quick I think it should be related to this in some way, but could be very wrong.
https://github.com/exercism/go/blob/2f58e6d0aaf6c379d02741c59d3b8ba297f7d3c3/config.json#L71-L82

Good work on the V3 so far! It looks amazing. Thank you to everyone who has put in time to accomplish this.

**Comment by SterverSVK** [comment]
+1 to priority

**Comment by louis-cl** [comment]
At a quick glance, it is missing tests
https://github.com/exercism/go/blob/a167c7853aed6b62bc3117e798f8cc51755a4bde/exercises/concept/weather-forecast/weather_test.go#L1

**Comment by pwierer** [comment]
Same here. +1

**Comment by oanaOM** [comment]
Thanks everyone for reporting this! sorry for the inconvenience.  Will work on fixing this today.

**Comment by iHiD** [comment]
I've hotfixed this here: https://github.com/exercism/go/pull/1509

Hopefully @oanaOM will be able to come up with a more solid fix later :)

**Comment by micuffaro** [comment]
If it's only about adding proper tests to `go/exercises/concept/weather-forecast/weather_test.go`, I can probably take a stab at it.
Would that be alright @oanaOM , @iHiD ?
Anything else besides the tests that I need to be aware of?

**Comment by ekingery** [comment]
The code looks good (and the tests pass with the exemplar). Thanks and nice work using `ast`, @micuffaro! I am seeing three items to cover before or just after merge:

1. In the first test, do we want to support >= 4, or will the AST parsing definitely catch and count multi-line comments as 1? 
2. Can you please add a `go.mod` file? 
```
module weather

go 1.13
```
3. We'll want to re-enable comments after merge, undoing [L92](https://github.com/exercism/go/pull/1509/files#diff-587cb980af76fdc7e52369fd0b9d926dff266976b6f8ac631e358fecc49ff8cfL92) in #1509

**Comment by micuffaro** [comment]
Thanks @ekingery.

> In the first test, do we want to support >= 4, or will the AST parsing definitely catch and count multi-line comments as 1?

The field `Comments` of the [ast.File](https://pkg.go.dev/go/ast#File) (the length of which is what we are interested in) is a slice of `*CommentGroup`, so here the parsing indeed treats multi-line comments as one `*CommentGroup`; in turn each of those is a slice of `*Comment`, with each being the individual comment line.

I thought that asserting the exact number of expected comment-groups in the whole file, would prevent students from adding or removing functions or declarations, and stick with the source code we provide them.

> Can you please add a go.mod file?

Sure thing, adding a commit for that.

> We'll want to re-enable comments after merge, undoing L92

Shall I directly do that in my PR?

Thank you for the quick feedback, despite being busy :)

**Comment by ekingery** [comment]
> Thanks @ekingery.
> 
> > In the first test, do we want to support >= 4, or will the AST parsing definitely catch and count multi-line comments as 1?
> 
> The field `Comments` of the [ast.File](https://pkg.go.dev/go/ast#File) (the length of which is what we are interested in) is a slice of `*CommentGroup`, so here the parsing indeed treats multi-line comments as one `*CommentGroup`; in turn each of those is a slice of `*Comment`, with each being the individual comment line.
>
> I thought that asserting the exact number of expected comment-groups in the whole file, would prevent students from adding or removing functions or declarations, and stick with the source code we provide them.

Perfect, thanks for explaining that! I remember the comments being tricky from doing the AST parsing for the test runner. 

>> Can you please add a go.mod file?
> 
> Sure thing, adding a commit for that.

Thanks!

> > We'll want to re-enable comments after merge, undoing L92
> 
> Shall I directly do that in my PR?

Whichever you prefer - either way is good with me. 

> Thank you for the quick feedback, despite being busy :)

No problem, most everybody is busy ;-)

**Comment by micuffaro** [comment]
> Whichever you prefer - either way is good with me.

Added commit 75f74f9  to address that :-)

**Comment by ekingery** [comment]
> > Whichever you prefer - either way is good with me.
> 
> Added commit [75f74f9](https://github.com/exercism/go/commit/75f74f9b25183073006c29068a289bf455f8b77d) to address that :-)

Thanks! Fortunately the build / checks should now pass , but unfortunately it appears  to be failing on a legitimate issues: https://github.com/exercism/go/pull/1543/checks?check_run_id=3583430566

**Comment by micuffaro** [comment]
Fixed that too, was missing some `config.json` settings. :)

**Comment by ekingery** [comment]
> Fixed that too, was missing some `config.json` settings. :)

Excellent - merged. @micuffaro, thanks for your contributions! It's very valuable to have this exercise back in the mix.

**Comment by ekingery** [comment]
@goatthinking, thanks for the report! If you could verify the comments exercise is available, we would appreciate it.
