### ISSUE TITLE
Lasagna exercise completely broke in online editor

### ISSUE THREAD

**Issue by sambeckingham** [exercism/go#1497]
So I noticed on the online editor, none of the test cases are showing. Further to this, "run tests" always fails if you call the package `lasagna` as it is by default.

![image](https://user-images.githubusercontent.com/48661226/131935554-2b5bfb67-f87a-4aaf-a18b-e36819c0e05e.png)

You may have noticed there's a spelling mistake on line 16 there, `reutnr`.  Well, turns out it doesn't matter. In fact you can even skip implementing functions entirely as long as you call the package anything but `lasagna`.

![image](https://user-images.githubusercontent.com/48661226/131935762-fe81ef41-7150-4870-bb90-419d80409cb5.png)

Et voila! I've looked at other open issues but I can't see anything that looks similar. There's the issue with Party Robot having a typo in go.mod - This doesn't have a go.mod at all - and there's the issue about the --json flag breaking reporting panics as success in Go 1.14.

I've looked through this repo and the documentation provided by Exercism and I can't really see any clear documentation on how the editor is working or what version of Go it's compiling and running tests for, so anything beyond this point is pure speculation.

I have a sneaking suspicion the root cause of this issue is that the [lasagna.go](https://github.com/exercism/go/blob/main/exercises/concept/lasagna/lasagna.go) file does not have the functions defined, so `go test` can't compile the package which I'm then assuming is used to create the test outlines we see in the online editor.

I'd be willing to look into this further if no one has the time and could point me to some documentation as to how the online editor is working with Go.

**Comment by mynlexi** [comment]
I tried it locally and get the an undefined, which would support your hypothesis @sambeckingham. 
`in ~/Exercism/go/lasagna  > go test -v lasagna_test.go
# command-line-arguments [command-line-arguments.test]
./lasagna_test.go:21:14: undefined: OvenTime
./lasagna_test.go:39:14: undefined: RemainingOvenTime
./lasagna_test.go:63:14: undefined: PreparationTime
./lasagna_test.go:88:14: undefined: ElapsedTime
FAIL    command-line-arguments [build failed]
FAIL
`
this also blocking me, unless i want to leave the learning track.

**Comment by scmbradley** [comment]
I couldn't get the online editor to work for this exercise. I also had to do `go mod init lasagna` to get this to work locally.

**Comment by Tultra** [comment]
I'm currently having problem with this same exercise, but on the Clojure track. In my case, it appears to me it's a problem with the namespaces.
![image](https://user-images.githubusercontent.com/71472992/132783361-36576c13-2522-45e9-bd3a-cc43d41a1504.png)

**Comment by andrerfcsantos** [comment]
I think this was fixed with https://github.com/exercism/go/pull/1547. Can you confirm @jmrunkle?

**Comment by jmrunkle** [comment]
I am pretty sure this works now so yeah, closing this issue.
