### ISSUE TITLE
Party Robot test typo

### ISSUE THREAD

**Issue by LurenzZ** [exercism/go#1518]
There is an error/typo in the fourth test of PartyRobot exercise.
The test pass **27** as table number variable but is expects for the string 

 "You have been assigned to table **_1B_**"

**Comment by jmrunkle** [comment]
That is not a typo, this is directly from the instructions:

> The robot provides the table number in hex (uppercase) due to a misalignment of its creator and the rest of the world.

`27` (decimal) == `1B` (uppercase hexadecimal) == `1 * 16^1 + 11 * 16^0` == `16 + 11`
