### ISSUE TITLE
Blackjack Exercise 'Processing' Forever

### ISSUE THREAD

**Issue by geoffreywiseman** [exercism/go#1528]
Not sure if this an issue with a high-level exercism component, the analyzer/test runner ... so I'm splitting the difference at filing this under `go`:

1. Submitted the blackjack exercise from cli
2. Said 'processing', should take 20-30s
3. Days later, still says processing:

<img width="873" alt="CleanShot 2021-09-09 at 15 40 37@2x" src="https://user-images.githubusercontent.com/49935/132751941-190bd3a2-2e27-449e-ac8b-6252de4dc5eb.png">

@iHiD  says:
> Each iteration gets tested/analyzed. That one hasn't for some reason. It's not queued or anything.

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/1884, although the test results output is going to be BIG.
