### ISSUE TITLE
Gross-store: correct the task description for RemoveItem

### ISSUE THREAD

**Issue by pavelanni** [exercism/go#1539]
In Gross-store in "4. Remove item from the customer bill" the description should be:

- Check whether the given item is in the bill
- Check whether the given unit of measurement is correct
- Check whether the new quantity is less than 0, if so don't remove the item and return `false`
- Check whether the new quantity is 0, if so return `true` and remove the item from the customer bill
- Otherwise reduce the quantity of the item

**Comment by jmrunkle** [comment]
This exercise has a number of issues... I have a holistic fix prepared in #1538 which corrects the parameters in the stub as well as the description.

**Comment by ekingery** [comment]
Thanks for the report. Please re-open if not closed by #1538
