### ISSUE TITLE
`cars-assemble` is supposed to teach `conditionals-if` but the stub already implements the only method that uses conditionals

### ISSUE THREAD

**Issue by NobbZ** [exercism/go#1542]
Though the current implementation of the exercise does ask to write 2 functions, which are just multiplying numbers with some conversion from float to int and back.

The only function that requires conditionals is actually pre-defined.

**Comment by jmrunkle** [comment]
Interesting. So according to config.json, it does "teach" this concept: https://github.com/exercism/go/blob/main/config.json#L132

So the real issue is that it pre-implemented the conditional logic there. Yeah... we should fix that. Changing the title to reflect what needs to be changed.

**Comment by ErikSchierboom** [comment]
Excellent observation @NobbZ. Two changes must be made:

1. The [stub implementation](https://github.com/exercism/go/blob/main/exercises/concept/cars-assemble/cars_assemble.go#L17) of the `successRate` function should be removed
2. The `successRate` function should be made public and tests should be added to https://github.com/exercism/go/blob/main/exercises/concept/cars-assemble/cars_assemble_test.go
