### ISSUE TITLE
need-for-speed: `NewCar` is pre-implemented, though exercise descriptions asks to implement it

### ISSUE THREAD

**Issue by NobbZ** [exercism/go#1545]
The function `NewCar` is asked to get implemented in the first step of the description:

https://github.com/exercism/go/blob/7bb631df3154fcd77d318e64d6d097676603815e/exercises/concept/need-for-speed/.docs/instructions.md?plain=1#L11-L20

Though the stub file contains the function already filled in:

https://github.com/exercism/go/blob/7bb631df3154fcd77d318e64d6d097676603815e/exercises/concept/need-for-speed/need_for_speed.go#L11-L18

**Comment by jmrunkle** [comment]
Agreed. There is no good reason for this to be pre-defined and somewhat ruins half of this exercise whose purpose is to teach about structs.
