### ISSUE TITLE
blackjack: move `FirstTurn` function from stub to tests file

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1558]
The [stub file](https://github.com/exercism/go/blob/main/exercises/concept/blackjack/blackjack.go#L24) of the `blackjack` exercise contains a `FirstTurn` function which the comments state should not be edited. This is problematic for two reasons:

1. Students might not notice the comment and edit this function, leading to invalid implementations
2. Students might notice the comment and edit the function, purposefully getting invalid implementations to pass the tests

For the above reasons, this function should really be moved into the [test file](https://github.com/exercism/go/blob/main/exercises/concept/blackjack/blackjack_test.go).

**Comment by awmorgan** [comment]
@junedev @ErikSchierboom  how are you supposed to solve this problem now? The state of the last 3 cards has been removed. You need the 3 cards for the logic. I think the exercise should be updated.
