### ISSUE TITLE
config: remove `basics` from `prerequisites` if exercise has more than one prequisite

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1559]
If an exercise in the [config.json file](https://github.com/exercism/go/blob/main/config.json#L91) has more than one prerequisite in its `prerequisites` and those `prerequisites` include the `basics` concept, that `basics` concept can be removed.

For example:

```json
"prerequisites": [
  "basics",
  "strings"
],
```

should become:

```json
"prerequisites": [
  "strings"
],
```

**Comment by moshegood** [comment]
This is done already.

**Comment by junedev** [comment]
yes, I did this as part of https://github.com/exercism/go/pull/1682
