### ISSUE TITLE
booking-up-for-beauty: add `booleans` to prerequisites

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1560]
The `booking-up-for-beauty` exercise depends on the student knowing what a `bool` is, but the `booleans` concept is [not listed in the prerequisites](https://github.com/exercism/go/blob/main/config.json#L118). The `booleans` concept should be added to the `prerequisites` of the `booking-up-for-beauty` exercise.

**Comment by omindu** [comment]
@ErikSchierboom I have added a [PR](https://github.com/exercism/go/pull/1777). Do let me know if it is not the expectation.

**Comment by ErikSchierboom** [comment]
Thanks!
