### ISSUE TITLE
numbers: about document is fairly empty

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1562]
The [about.md document](https://github.com/exercism/go/blob/main/concepts/numbers/about.md) of the `numbers` concept seems to be missing most of its content when compared to its [introduction.md document](https://github.com/exercism/go/blob/main/concepts/numbers/introduction.md). In general, the `about.md` document should contain _all_ the information from the `introduction.md`, but it can also add links to external resources, more in-depth discussion of the topic, etc. The https://exercism.org/docs/building/tracks/concepts page describes these documents in detail.

For now, the minimal fix would be to copy the content from the `introduction.md` file to the `about.md` file (minus the things mentioned here: https://github.com/exercism/go/issues/1561) and add any missing links. The existing link in the `about.md` file is probably good to have.

**Comment by andrerfcsantos** [comment]
Submitted the quick fix for now. But I think this concept can be improved further. Made my suggestions in a separate issue: https://github.com/exercism/go/issues/1574
