### ISSUE TITLE
card-tricks: should have for-loops as a prerequisite

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1565]
The [exemplar solution](https://github.com/exercism/go/blob/main/exercises/concept/card-tricks/.meta/exemplar.go) of the `card-tricks` exercise uses [for loops](https://github.com/exercism/go/blob/main/exercises/concept/card-tricks/.meta/exemplar.go#L29).

This concepts should be added as prerequisite. (This relies on [Bird Watcher being implemented](https://github.com/exercism/go/issues/1617))

**Comment by jmrunkle** [comment]
Stuck on this one until bird-watcher is implemented. I guess I can take that one since I need it to finish this one.

**Comment by jmrunkle** [comment]
Actually nevermind, that one is assigned to sachinmk27. Just waiting for that to be implemented.

**Comment by junedev** [comment]
There is a problem with this task. It is very hard to make a sensible for loop exercise without slices. That is why the exercise that is currently in the making has slices as prerequisite. That means card tricks that teaches slices cannot have for loops as prerequisite.

I would recommend solving this by removing the for loop task from card tricks as this is much easier than removing slices from the for loop exercise. Maybe someone has a good idea for a replacement task.

**Comment by junedev** [comment]
There are more things around card tricks that need to be fixed. I am closing this issue and create a new one that fits the current state of things.
