### ISSUE TITLE
card-tricks: introduction mentions implementation details

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1566]
The [introduction.md document](https://github.com/exercism/go/blob/main/exercises/concept/card-tricks/.docs/introduction.md) of the `card-tricks` exercise has the following section:

> Technically a slice consists of a pointer to a start element in an array and a length. This makes for example creating a sub-slice s[3:7] very efficient. But don't worry: most of the time this knowledge is not needed in order to work with slices.

While useful, the student doesn't really need to know this information to solve the exercise (unless I'm mistaken). As per [the docs](https://exercism.org/docs/building/tracks/concepts), any such non-essential information should be removed from the `introduction.md` document. The concept's `about.md` file is perfect for this type of information.

**Comment by jmrunkle** [comment]
Assigning myself (to discourage duplicate work), but moshegood is handling this in #1665
