### ISSUE TITLE
card-tricks: introduction should expand on slicing options

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1567]
Firstly, the [introduction.md document](https://github.com/exercism/go/blob/main/exercises/concept/card-tricks/.docs/introduction.md) of the `card-tricks` exercise very briefly mentions how to get a subslice from a slice. It would be very useful to update the example to show a slice and a subslice operation on that slice and show what is returned for the subslice.

Secondly, the [exemplar solution](https://github.com/exercism/go/blob/main/exercises/concept/card-tricks/.meta/exemplar.go#L40) interacts with slices in three ways that the student doesn't know about:

1. Getting a single element: https://github.com/exercism/go/blob/main/exercises/concept/card-tricks/.meta/exemplar.go#L9
2. Getting the elements up to an index: https://github.com/exercism/go/blob/main/exercises/concept/card-tricks/.meta/exemplar.go#L40
3. Gettting the elements from an index: https://github.com/exercism/go/blob/main/exercises/concept/card-tricks/.meta/exemplar.go#L40

The `introduction.md` document should introduce _all_ syntax that the student must know about to complete the exercise. For more information, check [the docs](https://exercism.org/docs/building/tracks/concepts).

**Comment by jmrunkle** [comment]
Assigning myself (to discourage duplicate work), but moshegood is handling this in #1665
