### ISSUE TITLE
weather-forecast: story tweaks

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1579]
The [instructions.md document](https://github.com/exercism/go/blob/main/exercises/concept/weather-forecast/.docs/instructions.md) of the `weather-forecast` exercise has a very basic theme:

> In this exercise, your task is to help a weather station manage their weather forecasting program.

The tasks themselves are then all about adding comments to existing code. There are two issues with this:

1. The tasks don't naturally link to the story/theme. The student is asked to help a weather station, but then only adds comments.
2. It is quite dull. There are probably not many programmers that would find the tasks interesting. 

While both are not necessarily big issues, we might be able to improve things a bit. For example, for the story we could perhaps make the link to the tasks a bit more direct by stating something like:

> In this exercise, you are hired to help a weather station update their legacy weather forecasting program. Your first look at the code base revealed that none of the code is commented! Being a diligent and professional programmer, you set about to change that.

As for the exercise being dull, one option is to have this exercise introduce two concepts (comments and another concept). I don't know if we can find a concept where this makes sense, and if not, we shouldn't force it.

**Comment by andrerfcsantos** [comment]
After two PR's being merged with small improvements to this, we are slowly getting there, we know have a small story/motivation to add the comments.

I personally would like for the story to be developed a bit more, by making the tasks refer to directly to the story in some way, instead of just having the task description.

**Comment by MikaeelMF** [comment]
Hi!
I have created PR #2216 to help resolve this issue. I would appreciate it if you could check it out!
Thank you!
