### ISSUE TITLE
party-robot: teach package-import concept

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1586]
The `party-robot` expects students to use the `fmt` package, but its [introduction.md document](https://github.com/exercism/go/blob/main/exercises/concept/party-robot/.docs/introduction.md) nor its dependencies explain how to import a package using the `import` keyword. 

This exercise should explain how to import packages in the `party-robot` exercise. This means updating the `introduction.md` file, adding a concept to the `concepts` array and creating the files for that concept.

**Comment by bobtfish** [comment]
Hey @ErikSchierboom I see that there's already a [packages concept](https://github.com/exercism/go/tree/main/concepts/packages) that just needs some work, so I've started work on getting that into shape in PR#1651 (very much a WIP still right now!).

Do you have strong feelings about the name of the concept? I.e. `packages` which was pre-existing vs `package-import` as in this ticket. I have a mild preference for the former as think covering both declaring and importing packages at the same time makes sense, but I'm happy to take your advice.

**Comment by ErikSchierboom** [comment]
I also think `packages` is the better name 👍
