### ISSUE TITLE
party-robot: improve hints

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1588]
The [hints.md document](https://github.com/exercism/go/blob/main/exercises/concept/party-robot/.docs/hints.md) of the `party-robot` exercise should be improved upon in the following ways:

1. Add hints per task (see [the docs](https://exercism.org/docs/building/tracks/concept-exercises))
2. Replace the code example with a link to an external resource

**Comment by andrerfcsantos** [comment]
I think this issue can be closed, as there was already a merge request addressing this https://github.com/exercism/go/pull/1726

New improvements for the hints of this exercise were suggested and are being tracked in #1776

**Comment by junedev** [comment]
I added checking the hints to #1776 as the hints for task 3 need to be rewritten there anyway. Closing this.
