### ISSUE TITLE
gross-store: exemplar uses unknown syntax

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1591]
The `gross-store` exercise's [exemplar solution](https://github.com/exercism/go/blob/main/exercises/concept/gross-store/.meta/exemplar.go) uses a concepts that is not in the prerequisites:

```go
if _, ok := units[unit]; !ok {
```

I don't know what to do with this: rewriting the code or explaining what the `if ...; ..` syntax does.

**Comment by iHiD** [comment]
@june Thoughts on the if syntax?

**Comment by iHiD** [comment]
@junedev Thoughts on this?

**Comment by junedev** [comment]
This syntax is used rather frequently and although it is sometimes overused in over cases, it is idiomatic in this use case. This syntax should be introduced as part of the `conditionals-if` concept (cars assemble).

**Comment by ErikSchierboom** [comment]
@junedev The cars-assemble exercise does not know about multiple return values, so I felt like teaching the natural place to introduce this syntax is in the exercise that will teach multiple return values: `card-tricks`: https://github.com/exercism/go/issues/1619 The `gross-store` exercise can then have `multiple-return-values` as a prerequisite.

**Comment by junedev** [comment]
@ErikSchierboom You are totally right, multiple return values are not introduced yet. However multiple return values have no actual relation to the `if expression; condition { ... }` syntax. Imagine this code for example:
```go
if num := someFunction(); num != 0 {
  //...
}
```

So feel free to ignore this, but I still think `if expression; condition { ... }` should be part of `conditionals-if` and additionally we need to find a home for introducing multiple return values. Why do you think it fits with Card Tricks?

Why not adding it to Gross Store where we need it? Is that "too late" in the tree?

**Comment by ErikSchierboom** [comment]
@junedev Issue created: https://github.com/exercism/go/issues/1644

**Comment by ErikSchierboom** [comment]
> additionally we need to find a home for introducing multiple return values. Why do you think it fits with Card Tricks?

Well, `card-tricks` uses multiple return values (`func GetItem(slice []uint8, index int) (uint8, bool)`) and the introduction is relatively short, so I felt it there was room there.

**Comment by junedev** [comment]
Ah, I missed that part when skimming the file. All good then.
