### ISSUE TITLE
elons-toys: tweak introduction

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1599]
The [introduction.md document](https://github.com/exercism/go/blob/main/exercises/concept/elons-toys/.docs/introduction.md) of the `elons-toys` exercise can use some tweaks.

Firstly, there is a section on pointer receivers:

> You can declare methods with pointer receivers in order to modify the value to which the receiver points. Such modifications are visible to the caller or the method as well.

The text itself doesn't explain _how_ to define a pointer receiver, that is only shown in the example. This should be fixed.

Secondly, the external links should be removed, as we generally don't want to link to external resources in the introduction.

Thirdly, the examples use a `main` function but it would be slightly more concise and readable if the `main` func wrapper was omited and just the statement inside that function listed.

**Comment by bobtfish** [comment]
This should be able to be closed out now.
