### ISSUE TITLE
chessboard: tweak introduction

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1604]
The [introduction.md document](https://github.com/exercism/go/blob/main/exercises/concept/chessboard/.docs/introduction.md) of the `chessboard` exercise could be tweaked a bit.

As per [the docs](https://exercism.org/docs/building/tracks/concept-exercises):

> - The information provided should give the student just enough context to figure out the solution themselves.
> - Only information that is needed to understand the fundamentals of the concept and solve the exercise should be provided. Extra information should be left for the concept's about.md document.

Applying this to the introduction means that the final section ("Last but not least, if you are required to perform some action but you are not interested in values nor keys of the slice or map, you can omit both index and value:" and its sample) can be removed, as the exemplar file does not seem to require it.

**Comment by junedev** [comment]
@ErikSchierboom I don't think removing that section makes sense. This is essential to be able to work with range loops in Go. The reason is that Go does not compile when there are unused variables, so without the underscore syntax you are lost when you dont need the index for example.
