### ISSUE TITLE
[Sept Sprint] Gopher's Gorgeous Lasagna

### ISSUE THREAD

**Issue by iHiD** [exercism/go#1609]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. Assigned to @andrerfcsantos.

---

## Gopher's Gorgeous Lasagna 

This is almost there. Needs one change making.

- Change first task to use `const` instead of function 
  - Add a sentence about `const` to the [exercise introduction](https://github.com/exercism/go/blob/main/exercises/concept/lasagna/.docs/introduction.md), [concept introduction](https://github.com/exercism/go/blob/main/concepts/basics/introduction.md) and [concept about](https://github.com/exercism/go/blob/main/concepts/basics/about.md). We should only mention const variables, no `iota` or advanced const usage.
  - Change [first task instructions](https://github.com/exercism/go/blob/main/exercises/concept/lasagna/.docs/instructions.md)
  - Change [stub](https://github.com/exercism/go/blob/main/exercises/concept/lasagna/lasagna.go)
  - Change [exemplar](https://github.com/exercism/go/blob/main/exercises/concept/lasagna/.meta/exemplar.go)
  - Change [tests](https://github.com/exercism/go/blob/main/exercises/concept/lasagna/lasagna_test.go)
- Check/resolve/close https://github.com/exercism/go/issues/1497

**Comment by andrerfcsantos** [comment]
I can take this one.

**Comment by andrerfcsantos** [comment]
I noticed the links in the hints point to the language spec. Should we really do this? For instance if we compare the language spec vs other resources like the Tour of Go:

* [Language Spec: Constants](https://golang.org/ref/spec#Constants)
* [Tour of Go: Constants](https://tour.golang.org/basics/15)

I think the Tour of Go is more straight to the point, provides examples, simple explanations and an interactive editor for the student to play with the concept. Personally I think linking to The Tour of Go or Go by Example would be a better fit as hints.

If we decide to link to Tour of Go or other similar, we might need to review other links in this exercise and in other exercises too.

**Comment by iHiD** [comment]
General rule is to link to the clearest source (so Tour of Go in this case?). Also note that exercise introductions shouldn't have links unless they are absolutely essential. Links should go in the after.md files.

**Comment by andrerfcsantos** [comment]
> General rule is to link to the clearest source (so Tour of Go in this case?). Also note that exercise introductions shouldn't have links unless they are absolutely essential. Links should go in the after.md files.

Ok, thanks. In this specific case I'm talking about the links in [hints.md](https://github.com/exercism/go/blob/main/exercises/concept/lasagna/.docs/hints.md). I assume it's ok for the hints to have links? (Based on what's already there)

**Comment by iHiD** [comment]
Yep! Definitely :)
