### ISSUE TITLE
[Sept Sprint] Cars Assemble

### ISSUE THREAD

**Issue by iHiD** [exercism/go#1611]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. **This exercise is claimed by @jmrunkle.**

---

## Cars Assemble

- [x] Add `arithmetic-operators` as a concept
  - Intro should have a table with the standard operators +,-,*,/,%, 
  - Intro should explain what happens for integer division (e.g. `5 / 2 = 2`)
  - Intro should introduce shorthand assignments `+=` etc.
  - Add `arithmetic-operators` to the `concepts` property of `cars-assembly` entry in the `config.json` file
  - Add an entry to the `concepts` array for the `arithmetic-operators` concept
  - Create a `concepts/arithmetic-operators` directory with its [required files](https://exercism.org/docs/building/tracks/concepts)
- [x] Add `comparison` as a concept
  - Add the `comparison` concept to the `cars assemble` exercise's `concepts` array in the config.json
  - Add an entry for the `comparison` concept to the `concepts` array in the config.json
  - Create a `concepts/comparison` directory with its [required files](https://exercism.org/docs/building/tracks/concepts) (check [this JS example](https://github.com/exercism/javascript/blob/main/concepts/comparison/introduction.md) for inspiration)
- [x] https://github.com/exercism/go/issues/1542
- [x] https://github.com/exercism/go/issues/1576
- [x] https://github.com/exercism/go/issues/1575
- [x] https://github.com/exercism/go/issues/1644
- [x] https://github.com/exercism/go/issues/1675
- [x] #1710

**Comment by jmrunkle** [comment]
Claiming this one since it looks like low-hanging fruit.

**Comment by iHiD** [comment]
Great. There's a question about whether this should also teach comparison. @junedev/@erikschierboom are discussing and will follow up on that on Tues :)

**Comment by ErikSchierboom** [comment]
@jmrunkle https://github.com/exercism/go/issues/1675 Has been added to the list of tasks.

**Comment by andrerfcsantos** [comment]
Since the comparison concept was previously planned to one of the exercises I was looking into, I already started making it and can take care of that task.

**Comment by ErikSchierboom** [comment]
Perfect!

**Comment by junedev** [comment]
@jmrunkle That was a copy and paste error. I will fix it.

The comparison concept introduces >, ==, etc which needed in this exercise. That is why introducing it in black jack would be "too late" in the concept tree so Erik indeed meant for it to be added to cars assemble.
