### ISSUE TITLE
[Sept Sprint] Improve Logs logs logs

### ISSUE THREAD

**Issue by iHiD** [exercism/go#1614]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. **This exercise is claimed by  
@sudomateo .**

---

## Logs Logs Logs

"Logs logs logs" will no longer teach basic strings (this will be poetry club instead), but instead will focus on Runes and string slices.

-  ~~This exercise should be introducing the `strings-package` concept. It should show how to access things from the package and show one usage example and a table with commonly used functions from the package. The concept about page should link to the full list of functions from the docs.~~
- [ ] This exercise should be introducing the `runes` concept and must use `ranges`.
- [x] https://github.com/exercism/go/issues/1596
- [x] https://github.com/exercism/go/issues/1595
- [x] https://github.com/exercism/go/issues/1594

**Comment by sudomateo** [comment]
@iHiD I'll snag this.

**Comment by iHiD** [comment]
@sudomateo Great. Thanks! :)

**Comment by junedev** [comment]
@sudomateo There was a mistake in the issue description here. The concept `strings-package` will be introduced in this exercise: https://github.com/exercism/go/issues/1613 If you have already written any content for this, please paste it as a comment into the other issue so the person working on this can use it. You can fully concentrate on `runes` in this concept and exercise.

**Comment by sudomateo** [comment]
@junedev I haven't started working on this yet as I was traveling. I will fully concentrate on `runes`. Thank you for informing me!

**Comment by sudomateo** [comment]
Just a reminder to myself to implement the work done in https://github.com/exercism/go/pull/1670.

**Comment by sudomateo** [comment]
Just a reminder to myself to implement the work done in https://github.com/exercism/go/pull/1670.

**Comment by sudomateo** [comment]
I'm all good! Just added content to the `runes` concept today. I'll finish up the exercise content tomorrow or the next day. All the work is in https://github.com/exercism/go/pull/1707.

**Comment by ErikSchierboom** [comment]
Great! Let me know when you'd like a review.

**Comment by sudomateo** [comment]
@ErikSchierboom #1707 is ready for review!
