### ISSUE TITLE
[Sept Sprint] Improve Weather Forecast

### ISSUE THREAD

**Issue by iHiD** [exercism/go#1615]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. **This exercise is unclaimed. To claim it, please comment below.**

---

## Weather Forecast

- [x] https://github.com/exercism/go/issues/1582
- [x] https://github.com/exercism/go/issues/1578
- [x] https://github.com/exercism/go/issues/1580

**Comment by sachinmk27** [comment]
I'd like to work on this

**Comment by junedev** [comment]
@sachinmk27 Thanks for helping with this. Please note that one of the task was already done by someone else and merged. It is marked as closed in the list in the issue description.
