### ISSUE TITLE
[Sept Sprint] Improve Blackjack

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1616]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. **This exercise is unclaimed. To claim it, please comment below.**

---

## Blackjack

- [x] https://github.com/exercism/go/issues/1556
- [x] https://github.com/exercism/go/issues/1558

**Comment by andrerfcsantos** [comment]
I'll take this one too :)

**Comment by ErikSchierboom** [comment]
@andrerfcsantos We've removed the comparison requirement, as we're moving that to Cars Assemble (see https://github.com/exercism/go/issues/1611). I hope you didn't lose any work. If you had already started, you might want to indicate in the just linked issue that you could add the comparison concept to Cars Assemble
