### ISSUE TITLE
card-tricks: introduce multiple-return-values concept

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1619]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. **This exercise is claimed by @jmrunkle.**

---

The `card-tricks` exercise uses multiple return values, but it does not have this as a taught concept.
This concept also includes teaching students how to do `if x, y := z; !y `. (i.e. checking for a value and then having a condition.
Note: don't teach about discard values (`_`).

- [ ] Add `multiple-return-values` as an official concept
  - The exercise introduction should introduce multiple return values
  - Add `multiple-return-values` to the `concepts` property of the `card-tricks` exercise's entry in the `config.json` file
  - Add an entry to the `concepts` array for the `multiple-return-values` concept
  - Create a `concepts/multiple-return-values` directory with its [required files](https://exercism.org/docs/building/tracks/concepts)

**Comment by moshegood** [comment]
To be clear: Multiple return values should be its own concept connected to functions. It should not live inside the slices concept.

**Comment by MiroslavGatsanoga** [comment]
Once the `multiple-return-values` concept is created, it needs to be added to Gross Store exercise.

**Comment by junedev** [comment]
@moshegood What Erik means is that the exercise "Card Tricks" should teach two concepts, `slices` and `multiple-return-values`. 

I agree with you that the new exercise about functions would be a better fit but the problem @ErikSchierboom saw is that a lot exercises already need multiple return values before the student would get to functions in the concept tree. This is why he suggested to add this as a separate concept here.

**Comment by ErikSchierboom** [comment]
Indeed. It is definitely possible for `multiple-return-values` to be explained in a new `functions` exercise, but we would have to do careful analysis to see if the dependencies make sense. For now, the easiest fix is to explain `multiple-return-values` alongside `slices` in the "Card Tricks" exercise and then we can always move this concept to a different exercise later on.

**Comment by jmrunkle** [comment]
I am taking care of this issue. Not sure if the first comment on this issue should be updated to reflect that.
