### ISSUE TITLE
[Sept Sprint] Gross Store

### ISSUE THREAD

**Issue by iHiD** [exercism/go#1621]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. **This exercise is claimed by @MiroslavGatsanoga .**

---

- [ ] https://github.com/exercism/go/issues/1593
- [ ] https://github.com/exercism/go/issues/1592
- [x] https://github.com/exercism/go/issues/1591

**Comment by MiroslavGatsanoga** [comment]
I'd like to work on this one :)
