### ISSUE TITLE
[Sept Sprint] Need for Speed

### ISSUE THREAD

**Issue by iHiD** [exercism/go#1622]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. **This exercise is being worked on by @jaimem88**

---

- [x] https://github.com/exercism/go/issues/1590
- [x] https://github.com/exercism/go/issues/1589
- [x] Introduction should show a real example instead of just the abstract syntax

**Comment by jaimem88** [comment]
👋 I'd like to help with this :)

**Comment by ErikSchierboom** [comment]
I've assigned you.

**Comment by iHiD** [comment]
Great. Thanks @jaimem88!
