### ISSUE TITLE
[Sept Sprint] Chess Board

### ISSUE THREAD

**Issue by iHiD** [exercism/go#1623]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. **This exercise is claimed by @bobtfish.**

---

- [x] https://github.com/exercism/go/issues/1604
- [x] https://github.com/exercism/go/issues/1601
- [x] https://github.com/exercism/go/issues/1603

**Comment by bobtfish** [comment]
Guess I'm claiming this one too 🤣
