### ISSUE TITLE
[Sept Sprint] Party Robot

### ISSUE THREAD

**Issue by iHiD** [exercism/go#1624]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. **This exercise is claimed by @bobtfish.**

---

This will move earlier in the track, between `poetry-door-policy` and `log-logs-logs`. This should be about `string-formatting` not `strings`. 
- [x] https://github.com/exercism/go/issues/1597
- [x] https://github.com/exercism/go/issues/1586
- [x] https://github.com/exercism/go/issues/1625
- [x] https://github.com/exercism/go/issues/1585
- [x] https://github.com/exercism/go/issues/1586
- [x] https://github.com/exercism/go/issues/1728

**Comment by bobtfish** [comment]
I’ll take this

**Comment by junedev** [comment]
@bobtfish I would recommend you create one PR for all the remaining issues from the list above. Otherwise you might run into unnecessary merge conflicts and the content might not be consistent anymore.

**Comment by ErikSchierboom** [comment]
I'm re-opening this as we've identified one more improvement: https://github.com/exercism/go/issues/1728

**Comment by bobtfish** [comment]
This can be closed again. #1728 is done.
