### ISSUE TITLE
party-robot: change taught concepts

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1625]
The `party-robot` exercise currently is designed to teach the `strings` concept, but this will be done by the Poetry Door Club policy exercise that is to be added. As such, the goal of this exercise changes to: teach the `string-formatting` concept (and the [`package-import` concept](https://github.com/exercism/go/issues/1586).

The `strings` concept should be renamed to `string-formatting`: https://github.com/exercism/go/blob/main/config.json#L64

**Comment by bobtfish** [comment]
This is done!

**Comment by junedev** [comment]
@bobtfish I think there is a part missing here. The the exercise introduction and the concept introduction and about file still contain a section that explain strings in general. That section should be removed as this part will be covered by another exercise.

You can paste the text as a comment into this issue https://github.com/exercism/go/issues/1613 so the person creating the string exercise/concept can use it.

Sorry that I did not notice this in the review earlier but it was a bit hard to understand which PR was supposed to cover which issue. You can help with that by writing "resolves #xyz" (where xyz is the issue number) into the PR description. GitHub will then automatically create a link. See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
