### ISSUE TITLE
[Sept Sprint] Elon's Toys

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1626]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. **This exercise is unclaimed. To claim it, please comment below.**

---

- [x] https://github.com/exercism/go/issues/1598
- [x] https://github.com/exercism/go/issues/1599
- [x] https://github.com/exercism/go/issues/1602

**Comment by bobtfish** [comment]
I'd like to claim this

**Comment by ErikSchierboom** [comment]
Done

**Comment by bobtfish** [comment]
All three points here are completed, this should be able to be closed now.

**Comment by junedev** [comment]
@ErikSchierboom The fixes you described in the issues above were only applied to the exercise introduction.md file as by your description. Shouldn't most of them (besides maybe removing links) also apply to the introduction/about of the concept?
