### ISSUE TITLE
the-farm: introduce interfaces concept

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1638]
`The Farm` should unlock `interfaces`. This will involve:

- Updating the exercise's instructions.md file
- Updating the exercise's introduction.md
- Updating the concept's introduction.md
- Updating the concept's about.md file
- Add `interfaces` to the `concepts` for the `the-farm` exercise in the `config.json`

**Comment by junedev** [comment]
@jmrunkle Could you give me an update whether I should unassign you or not?

**Comment by jmrunkle** [comment]
Sorry, still recovering from new baby. I'm nearly done with this so if you do not mind being a little patient, I can finish it.

**Comment by junedev** [comment]
@jmrunkle I know how that feels :blue_heart: and I would really like that you don't have this issue in your neck anymore. So if you don't mind, @andrerfcsantos offered to finish this up. If you could push whatever you have to some branch/ create a draft PR, he can pick it up from there.

**Comment by andrerfcsantos** [comment]
@jmrunkle I don't mind waiting a bit more, but like June said, I'll happily finish this so you can have more time with your family!

**Comment by andrerfcsantos** [comment]
@jmrunkle Can you give us an update on this?

**Comment by jmrunkle** [comment]
I just turned my in-progress code into a draft PR: #1976

I have lost a bit of context on where exactly I had left this, but I will try to make it complete today.

**Comment by jmrunkle** [comment]
Looks like the main thing that was missing was to copy the intro material about interfaces into the intro for the exercise. Let me patch that in and then send the PR out for review.

**Comment by junedev** [comment]
@jmrunkle To avoid further delays (students keep asking for this), I would suggest @andrerfcsantos can directly push small fixes to your branch if anything comes up instead of writing review comments and waiting for them to be resolved. This way it can be merged quickly. If you object, let us know.

**Comment by jmrunkle** [comment]
Sounds fine to me. I don't mind either way
