### ISSUE TITLE
Improve Concept Exercise: The Farm (errors)

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1640]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. **This exercise is claimed by @jmrunkle.**

---

- [x] https://github.com/exercism/go/issues/1636
- [x] https://github.com/exercism/go/issues/1638
- [x] https://github.com/exercism/go/issues/1639

**Comment by sachinmk27** [comment]
I'd like to work on this

**Comment by junedev** [comment]
@ErikSchierboom Have you seen there is also the exercise Deep Thought which teaches errors? The "Deep Thought" exemplar looks more like what we are aiming for here to cover basic `errors` (we would just need to add a part for the customer error). Can you remember why you preferred "The Farm" for the September sprint list and do you know how the two exercises are related?

**Comment by jmrunkle** [comment]
I can take this one since it is blocking some of the work I need in another exercise.

**Comment by ErikSchierboom** [comment]
@junedev I have no preference for The Farm over Deep Thought, it's just that The Farm was already there. I'd be fine with replacing it with Deep Thought. Whatever is best.

**Comment by junedev** [comment]
@jmrunkle Maybe you can have a look at "deep thought" and judge yourself what you think fits best for the basic errors concept. The respective other exercise can be set to "wip" and then used for more advanced concepts like the error wrapping later.

Another comment for you as I don't know whether this came across from the description. The general idea here is to use a custom error type as an example of something implementing an interface. To make the student write an interface you can additionally make up some requirement for a second method besides `Error` that the custom error should have. 

If you dont like that idea you can also just cover errors and then we need a separate exercise for interfaces.

**Comment by jmrunkle** [comment]
> @jmrunkle Maybe you can have a look at "deep thought" and judge yourself what you think fits best for the basic errors concept.

Will do.

**Comment by jmrunkle** [comment]
So... `deep-thought` looks really incomplete (no tests, partial instructions, lots of TODOs that need doing, etc). It seems we missing trackers for that on the September sprint overview (and sub-issues for the actual problems). @junedev @ErikSchierboom?

**Comment by junedev** [comment]
@jmrunkle The primary goal of the September Sprint is to get to a good basic syllabus. The focus was not on "cleanup/finish all existing/started exercises". For a  basic syllabus one exercise on errors would have been ok for now so Erik picked "the farm" and created this sprint ticket.

Once you decided to stick with "the farm" for teaching `errors` and developed a feeling for its content, feel free to create a normal non-sprint ticket for "deep thought" that mentions what things are already covered in "the farm" and maybe ideas for what's left to cover there. Of course if there is time it could still become part of the sprint but for now an exercise on "pointers" for example is more important to get done  than a second one on more error related topics.

**Comment by jmrunkle** [comment]
Thanks for clarifying. `the-farm` seems to be more developed so I think I will continue this one and create some non-sprint issues for outstanding problems with `deep-thought` and what it should / could cover.
