### ISSUE TITLE
[Sept Sprint] New exercise teaching functions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1642]
This is part of our September Spring to get the Go Track in shape. Please read the [Overview issue](https://github.com/exercism/go/issues/1610) for more details. **This exercise is unclaimed. To claim it, please comment below.**

---

**Before building this exercise (or exercises), please read up on [the documentation](https://exercism.org/docs/building/tracks/concept-exercises).**

We need an exercise for the `functions` concept, which should teach about:

- Arguments (incl. syntax for arguments of the same type)
- Return values
- Named return values
- Naked return
- pass by value but the value can be a pointer
- Can also include: Anonymous functions/callbacks

It should **not** teach (these will be covered later):

- Variadic functions (that should be introduced with rest-and-spread)

It is worth to look if it is possible to port this exercise from the JS [lasagna master exercise](https://github.com/exercism/javascript/tree/main/exercises/concept/lasagna-master/.docs).

**Comment by bobtfish** [comment]
I'll take this. I plan to try using the JS lasagna master exercise and I plan to *not* cover anonymous functions - I think that those deserve their own concept / introduction - trying to cram them in here is biting off too much at once.

**Comment by ErikSchierboom** [comment]
@bobtfish Let me know if there is anything I can do to help.

**Comment by bobtfish** [comment]
> @bobtfish Let me know if there is anything I can do to help.

PR ready for initial review in #1720 - I think it's a reasonable first take, but any/all feedback appreciated as this is my first fill concept/exercise!
