### ISSUE TITLE
weather-forecast fails test even though comments are provided.

### ISSUE THREAD

**Issue by zberwaldt** [exercism/go#1671]
weather-forecast exercise fails the test even though a comment has been added to the package variables.

Provided solution:
```go
// Package weather provides tools to report the weather conditions of a particular location.
package weather

// CurrentCondition represents the current condition.
var CurrentCondition string

// CurrentLocation represents the current location.
var CurrentLocation string

// Forecast takes two arguments: city and condition. 
// It will assign them to the appropriate package variable.
// Then return a string describing the weather at the given location.
func Forecast(city, condition string) string {
    CurrentLocation, CurrentCondition = city, condition
    return CurrentLocation + " - current weather condition: " + CurrentCondition
}
```

Test outcomes:
```sh
=== RUN    TestComments
        weather_test.go:32 Exported identifier CurrentCondition should have a comment.
        weather_test.go:32 Exported identifier CurrentLocation should have a comment.
---    FAIL: TestComments (0.00s)
FAIL
exit status 1
FAIL      weather 0.002s
```

**Comment by jarz** [comment]
Broken by #1667 -- the tests are written to expect a very exact syntax tree created by the `var ( ... )` declaration.

**Comment by zberwaldt** [comment]
@jarz This worked for me. Do you want me to close this issue?

**Comment by junedev** [comment]
Please leave the issue open.

**Comment by junedev** [comment]
@sachinmk27 Could you take care of fixing the exemplar file here? Best case both version would pass the test.

@jarz Very sorry for breaking this! Shouldn't have the CI picked this up though?

**Comment by sachinmk27** [comment]
Sure, will fix it.

**Comment by junedev** [comment]
@sachinmk27 Yes, exactly. At the very least the tests should pass for the new exemplar. Even better better would be when the tests still pass if someone changes the stub to the `var (...)` version.
