### ISSUE TITLE
string-formatting: Example might be wrong

### ISSUE THREAD

**Issue by SaschaMann** [exercism/go#1691]
From the bug report dump on Slack

---

I think the example code is incorrect:

f := 4.3242
fmt.Printf("%.4", f)
// Output: 4.32

If the desired output is 4.32 given 4.3242, and you want rounding, then I think this is correct:

f := 4.3242
fmt.Printf("%.2f", f)
// Output: 4.32

For that matter, I think "f" is a confusing variable name given the Printf formatting operator "f". I would suggest "number".

---

INCORRECT EXAMPLE IN FLOATING POINT PRECISION
In your example under String track for Go, the example you gave for implementing floating point precision is this: 
f := 4.3242
fmt.Printf("%.4", f)
// Output: 4.32

The above won't work because the formatting verb (f) is not stated immediately after the precision figure. Also, the correct precision to arrive at that output will be 2 and not 4. It should be:

  f := 4.3242
fmt.Printf("%.2f", f)
// Output: 4.32

**Comment by junedev** [comment]
@bobtfish Would you have time to address this? You already worked on those concept docs.

**Comment by bobtfish** [comment]
Yep, I can fix this.

Thanks for the bug report @SaschaMann and thanks for tagging me @junedev
