### ISSUE TITLE
`sorting-room`: teach about type-switch syntax

### ISSUE THREAD

**Issue by jmrunkle** [exercism/go#1704]
Teach about this syntax:

```go
switch v := i.(type) {
case T:
    // here v has type T
case S:
    // here v has type S
default:
    // no match; here v has the same type as i
}
```

**Comment by junedev** [comment]
@jmrunkle If you want you can also include this as part of the type assertion concept. Many tracks said that things are a bit easier if the concepts are not cut too small.

**Comment by jmrunkle** [comment]
> If you want you can also include this as part of the type assertion concept. Many tracks said that things are a bit easier if the concepts are not cut too small.

Sounds good. I will do that since it simplifies things.

**Comment by jmrunkle** [comment]
This is done between the exercise itself and the `type-assertion` concept
