### ISSUE TITLE
`cars-assemble`: add implementation of `successRate()` as a task

### ISSUE THREAD

**Issue by g-back** [exercism/go#1710]
Hi,
just did the exercise and found the instructions to be a bit confusing (but maybe that's just me?)

In the Instructions, it says:
```
Note that the calculation of the success rate has been provided already.
```
To me this implies that the function `sucessRate()` has already been implemented - which is not the case. Seems to be a leftover of #1662

Suggestions:
- remove the above mentioned sentence
- Implemenation of `successRate()` should be added as the first task, since the calculation requires it. Also move the function to the first place of the stubs.

Thoughts?

**Comment by junedev** [comment]
Your suggestion sounds like a good plan!

**Comment by jmrunkle** [comment]
Sorry, I had the task to fix this and completely forgot to update the documentation parts.

**Comment by ErikSchierboom** [comment]
Good catch @g-back!
