### ISSUE TITLE
party-robot: update introduction

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#1728]
The `party-robot` exercise unlocks the `packages` concept, but its `introduction.md` document does not explain what packages are (it does show how they can be used for the `fmt` package).

Firstly, the `introduction.md` document of the `party-robot` exercise should be updated to better explain what packages are. There is already content for this in the `introduction.md` document of the `packages` concept.

Secondly, the `packages` concept should mention how public/private visibility works. See https://github.com/exercism/go/pull/1720 for sample text for this. The public/private visibility explanation should be added to the exercise's `introduction.md` and the concept's `introduction.md` document.

**Comment by bobtfish** [comment]
I'm handling this
