### ISSUE TITLE
black-jack: LargeHand lacks card information

### ISSUE THREAD

**Issue by mcastorina** [exercism/go#1731]
https://exercism.org/tracks/go/exercises/blackjack

The large hand description states "two aces must always split", however the function signature provided only has 

```go
func LargeHand(isBlackjack bool, dealerScore int) string
```

I think the API should be changed to the following so the function can check the cards. Either that or match `SmallHand` and provide the total score since `22` implies two aces.

```go
func LargeHand(card1, card2 string, dealerScore int) string
// or
func LargeHand(handScore, dealerScore int) string
```

Unless I'm missing something here..

P.S. I'm happy to submit a fix if this really is a mistake

**Comment by mcastorina** [comment]
> Unless I'm missing something here..

Turns out I was missing something :laughing: 

```
// LargeHand implements the decision tree for hand scores larger than 20 points.
```

It must be two aces if `isBlackJack == false`

**Comment by junedev** [comment]
I am reopening this to discuss whether there is something we can do here to improve the exercise. There was another issue opened for this before https://github.com/exercism/go/issues/1709.

**Comment by IsaacG** [comment]
Maybe spell out that large hand is only called when there is an ace and either a second ace or a ten card.

> .. larger than 20 points (i.e. one ace and another card worth 10 or more).

**Comment by mcastorina** [comment]
Question: is there a reason `LargeHand` and `SmallHand` are split in this exercise? Perhaps a single function would make it more clear.

A mentor could also recommend writing private functions to organize the code better. The benefit of this approach is the learner can define `largeHand` and `smallHand` however they like.

**Comment by jkisor** [comment]
Dropping by to share my experience with this exercise. I was stumped for similar reasons to #1709.
The thought in my head was "How do i know I have 2 aces if i don't have access to what my cards are?"

It's a little indirect to be a process of elimination based on assumptions of **when** the function is called or not called. While technically correct, I think it distracts from the goal of the exercise.

I like @mcastorina 's question. Removing `LargeHand` and `SmallHand` and expose `FirstTurn` as function to be implemented. Motivation being: if the trip-up is "when" the methods are called. Let the learner control the "when". Also an excellent point about encouraging learner to write their own functions to organize the strategies.

**Comment by junedev** [comment]
@jkisor Thanks for the input! If there is no major difficulty/complexity hidden in FirstTurn currently, then your suggestion sounds like a good plan.

**Comment by LeamHall** [comment]
The definition of "Small Hand" is "less than 21 points", which does not match a pair of aces. Some of us think literally, and that can cause confusion if we're trying to following specifications that don't work. Which is real life, but this is a learning exercise.  :)

If we're going with @mcastorina 's suggestion then we probably need to work on the instructions, too. So far several of the code challenges give very poor directions.

**Comment by norbs57** [comment]
I would be happy to prepare a PR for this.
