### ISSUE TITLE
election-day: No mention of spec for `nil` argument to `VoteCount` function

### ISSUE THREAD

**Issue by ynfle** [exercism/go#1750]
The test reveal that `0` should be returned

**Comment by andrerfcsantos** [comment]
Maybe I'm understanding what you are saying wrong, but the instructions for that task and the example given do tell what to do in the `nil` case.

**Comment by jmrunkle** [comment]
Yep: https://github.com/exercism/go/blob/main/exercises/concept/election-day/.docs/instructions.md#2-get-number-of-votes-from-a-counter

That pretty clearly says exactly what to do in the `nil` case for `VoteCount`.
