### ISSUE TITLE
Weather forecast: Tests might be insufficient

### ISSUE THREAD

**Issue by SaschaMann** [exercism/go#1759]
I suspect this falls under "asssume the student won't cheat", but this passes the tests but clearly not the spirit of the exercise. When following TDD-principles (which many Exercism tracks tend to do), this would be a sufficient solution:

```go
// Package
package weather

// CurrentCondition
var CurrentCondition string

// CurrentLocation
var CurrentLocation string

// Forecast
func Forecast(city, condition string) string {
	CurrentLocation, CurrentCondition = city, condition
	return CurrentLocation + " - current weather condition: " + CurrentCondition
}
```

Since Go comments follow a certain format, checking their content or at least that their content is non-zero might prevent this. 

I'm not sure this is worth fixing but figured I'd bring it up anyway.

**Comment by junedev** [comment]
Added as part of #1730
