### ISSUE TITLE
lasagna: error unclear when not specifying a return type

### ISSUE THREAD

**Issue by SaschaMann** [exercism/go#1763]
```go
package lasagna

// TODO: define the 'OvenTime' constant
const OvenTime = 40

// TODO: define the 'RemainingOvenTime()' function
func RemainingOvenTime(t int) {
    return OvenTime - t
}
```

results in the following error

```go
# lasagna [lasagna.test]
./lasagna.go:8:5: too many arguments to return
	have (int)
	want ()
./lasagna_test.go:39:31: RemainingOvenTime(25) used as value
```

It's not clear that this is a "Go-level error" rather than a task-level error. The error can be interpreted as "You're returning and int but the exercise expects `()`".

Clearing this up with a custom error message or some additional info might make it clearer for people coming from languages where return types aren't given in the signature. It's mentioned in the docs but it's easy to overlook and this error doesn't point one towards the solution, imo.

**Comment by bobtfish** [comment]
I'll claim / address this one as well.
