### ISSUE TITLE
Party Robot:  value not explicit

### ISSUE THREAD

**Issue by ileossa** [exercism/go#1769]
We don't know that we need the value of the table in hexadecimal and upper. 
Maybe rename the value ? Or adjust the exercise.

**Comment by andrerfcsantos** [comment]
Thanks for logging an issue.

The instructions do refer that the value must be in hexadecimal:

> The robot provides the table number in hex (uppercase) due to a misalignment of its creator and the rest of the world.

[source](https://github.com/exercism/go/blob/main/exercises/concept/party-robot/.docs/instructions.md?plain=1#L30)

Maybe you missed this part of the instructions? If so, what do you think it should be done so you wouldn't miss it?

**Comment by junedev** [comment]
We will use #1776 to track this issue.
