### ISSUE TITLE
Errors in Golang track not glanceable

### ISSUE THREAD

**Issue by Lewiscowles1986** [exercism/go#1789]
Just dry-running https://github.com/exercism/blog/blob/main/posts/exercism-is-the-official-go-mentoring-platform.md and noticed that the errors output seem to be the literal test function...

Fine for me, because I've been coding go for a few years. But for a person unfamiliar... I think YMMV

For a start a learner needs to be able to reconstruct the function call from the table tests (I love table tests, and that you're using them, perhaps these could be structured in a way with an args struct to disambiguate test state from function arguments?

Once this is done They need to spot the error message. If they make a syntax boo-boo, the output makes a lot of sense. But for failing test cases, it's actually easier to not code in the browser, run with verbose flags and watch go make useful noise.

**Comment by Lewiscowles1986** [comment]
The specific exercise that bit me was me rushing and being lazy, but https://exercism.org/tracks/go/concepts/slices

Locally I got the following error (because I'd forgot to bounds-check)

> --- FAIL: TestRemoveItem (0.00s)
>    --- FAIL: TestRemoveItem/Remove_out_of_bounds_index (0.00s)
> panic: runtime error: slice bounds out of range [:7] with capacity 4 [recovered]
>        panic: runtime error: slice bounds out of range [:7] with capacity 4

I didn't get this in browser when I omit lines to check for preExisting element at index

```go
func RemoveItem(slice []int, index int) []int {
	_, preExisting := GetItem(slice, index)
	if preExisting {
		return append(slice[:index], slice[index+1:]...)
	}
	return slice
}
```

vs

```go
func RemoveItem(slice []int, index int) []int {
	return append(slice[:index], slice[index+1:]...)
}
```

**Comment by junedev** [comment]
Hi, thanks for the input.

> I didn't get this in browser

Could you please paste what you saw in the browser instead?

**Comment by Lewiscowles1986** [comment]
https://user-images.githubusercontent.com/2605791/135803504-b3aaf158-9b2c-4ccb-960a-6fab40e34517.mp4
<details>
<summary>Textual output</summary>

```

FAILED
Test 1
TestRemoveItem

CODE RUN
func TestRemoveItem(t *testing.T) {
	type args struct {
		slice	[]int
		index	int
	}
	tests := []struct {
		name	string
		args	args
		want	[]int
	}{
		{
			name:	"Remove an item",
			args: args{
				slice:	[]int{3, 4, 5, 6},
				index:	1,
			},
			want:	[]int{3, 5, 6},
		},
		{
			name:	"Remove the first item",
			args: args{
				slice:	[]int{3, 4, 5, 6},
				index:	0,
			},
			want:	[]int{4, 5, 6},
		},
		{
			name:	"Remove the last item",
			args: args{
				slice:	[]int{3, 4, 5, 6},
				index:	3,
			},
			want:	[]int{3, 4, 5},
		},
		{
			name:	"Remove out of bounds index",
			args: args{
				slice:	[]int{3, 4, 5, 6},
				index:	7,
			},
			want:	[]int{3, 4, 5, 6},
		},
		{
			name:	"Remove negative index",
			args: args{
				slice:	[]int{3, 4, 5, 6},
				index:	-7,
			},
			want:	[]int{3, 4, 5, 6},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := RemoveItem(copySlice(tt.args.slice), tt.args.index); !slicesEqual(got, tt.want) {
				t.Errorf("RemoveItem(slice:%v, index:%v) = %v, want %v", tt.args.slice, tt.args.index, got, tt.want)
			}
		})
	}
}
TEST FAILURE

=== RUN   TestRemoveItem

--- FAIL: TestRemoveItem (0.00s)
```

</details>

**Comment by Lewiscowles1986** [comment]
Interestingly. I Think it might be in that collapsed block, which leads me to question why the first test is not outputting helpful error messages. In any case I solved it because I can read go. I was checking out the new guided feature from the exercism blog, just to see how it would be for learners.

**Comment by junedev** [comment]
Thanks for the video. The issue you showed there is already reported here https://github.com/exercism/go-test-runner/issues/44 and the root cause for this is https://github.com/exercism/go-test-runner/issues/8.
