### ISSUE TITLE
Interest-is-interesting: negative interest rate on negative balances?

### ISSUE THREAD

**Issue by sbromberger** [exercism/go#1840]
> In this exercise you'll be working with savings accounts. Each year, the balance of your savings account is updated based on its interest rate. The interest rate your bank gives you depends on the amount of money in your account (its balance):
>  * -3.213% for a negative balance.

I think this is ambiguous. Does this mean that if I have a negative balance of, say, ($100,000), then after one year I earn $3,213 on it, bringing my balance to ($96,787)?

If so, please name the bank that will let me take out a billion dollar loan on these terms :)

(I realize that the intent is probably to increase the size of the debt, but the way it's presented isn't clear.)

**Comment by junedev** [comment]
The task here is to improve the instructions to remove the ambiguity mentioned above.
