### ISSUE TITLE
Interest is interesting:  Fix float comparison logic

### ISSUE THREAD

**Issue by sbromberger** [exercism/go#1842]
The `Interest()` function unfortunately requires that the rates be in percentage, not decimal (i.e., "three percent" is `3.0`, not `0.03`), and in `float32` (as opposed to `float64`). This has the additional unfortunate consequence of introducing the student unfamiliar with IEEE 754 to the fact that 
` n * float64(r) / 100` may not equal `n * float64(r / 100)`. (See https://play.golang.org/p/148rIMlhIHQ for the demonstration.)

It is almost never a good idea to perform exact equality comparisons on floating point numbers due to float imprecision. In this case, the former calculation is what the test suite expects; the latter fails, even though the difference is within some small epsilon in every case.

I would suggest modifying the test framework to check to see whether `math.Abs(expected - actual) < epsilon` instead of `expected == actual`.

(Edited to add: this checking against epsilon is precisely what we're doing in the Space Age exercise.)

**Comment by junedev** [comment]
When dealing with large numbers, the comparison epsilon needs to be done in a relative fashion (pseudocode):
```
abs(a - b)/ (abs(a) + abs(b)) < epsilon
```
So the task here is to use that in the test code that compares the floats.
You might need to check if that works for all the small values as well in our case, its possible we need two different comparisons. (see e.g. https://github.com/exercism/javascript#running-the-test-suite)

**Comment by andrerfcsantos** [comment]
It seems we are already comparing to an epsilon: https://github.com/exercism/go/blob/main/exercises/concept/interest-is-interesting/interest_is_interesting_test.go#L10

Is there anything else to do here?

**Comment by sbromberger** [comment]
yes - the issue is that the epsilon needs to be proportional to the multiplicand, since the floating point errors are multiplied (and therefore magnified, exceeding the epsilon).
