### ISSUE TITLE
Elon's Toys exercise - Missing task instructions for two required steps/funcs

### ISSUE THREAD

**Issue by ferueda** [exercism/go#1844]
https://exercism.org/tracks/go/exercises/elons-toys

On Elon's Toys exercise you are given instructions for four implementation tasks;

1. Drive the car
2. Display the distance driven
3. Display the battery percentage
4. Check if a remote control car can finish a race

But there are other two implementations that are required in order to pass the tests which are;

```
// CreateCar creates a new car with given specifications.
func CreateCar(speed, batteryDrain int) *Car {
	panic("Please implement CreateCar() method")
}
```

```
// CreateTrack creates a new track with given distance.
func CreateTrack(distance int) Track {
	panic("Please implement CreateTrack() method")
}
```

IMO, instructions for these two should also be explicit and included in the tasks list.

I can help fixing this issue right away (it would be my first contribution).

**Comment by junedev** [comment]
@ferueda Thanks for reporting but we already have an issue for this: https://github.com/exercism/go/issues/1782
