### ISSUE TITLE
Add an automated PR comment

### ISSUE THREAD

**Issue by junedev** [exercism/go#1846]
Angelika created this great GitHub action that can generate PR comments depending on which files have changed in the PR.
https://github.com/exercism/pr-commenter-action

An example can be seen in the Elixir Track: https://github.com/exercism/elixir/pull/930#issuecomment-926567977

I was thinking about adding something similar for the Go track.
It could take care of the following things:
* Remind the maintainer to set the correct size label.
* If concept about.md, introduction.md or exercise introduction.md for a concept exercise is changed, remind the contributor to check the change is applied consistently to all 3 files.
* If the exemplar or the stub is changed, remind the contributor to check that both files are kept in sync (same JSDoc comments, same function signatures).
* If a practice exercise introduction or test file is changed, remind the contributor to check whether the exercise originates in problem-spec and what to do in that case.

Any objections? Any thoughts on additional things the PR comment should cover?

**Comment by andrerfcsantos** [comment]
Sound great!

Another little check I think it could be useful is that if the Pull Request is to fix a typo (maybe we can try to detect this by "typo" in the title), make sure that typo is fixed everywhere on the exercise files or even the whole repo. From the Pull Requests I've seen fixing typos, it's very easy for the PR author to fix just the place where they've seen the typo, but forget other files. A simple search for the typo in all the files can easily reveal all the places needing fixing.

**Comment by junedev** [comment]
@andrerfcsantos The PR commenter is based on differentiating which files were changed so I am not sure it can currently handle this "do something depending on the PR title" logic right now. I added your suggestion as comment that always shows up for now.
