### ISSUE TITLE
Need for speed: hint and exemplar mismatch with regard to `CanFinish`

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/go#1848]
The hint says:

> - We assume that the cars' battery is charged to 100% initially.

The exemplar solution says:

```go
func CanFinish(car Car, track Track) bool {
	maxDistance := car.battery / car.batteryDrain * car.distance
	return track.distance <= maxDistance
}
```

The exemplar solution doesn't assume that the battery is always equal to 100. It actually checks the battery. That feels more correct to me than what the hint suggests, but if that is supposed to be the desired solution, than I would suggest not only removing the hint, but also adding a new test case where the starting battery is less than 100.

**Comment by junedev** [comment]
@andrerfcsantos Re that test case, maybe I made a mistake mergin FYI Re that test case, maybe I made a mistake merging this then, the test looked different before: https://github.com/exercism/go/pull/1824 There is also a longer discussion about issues with the exercise in that PR.
