### ISSUE TITLE
Allow additional custom tests in the generator

### ISSUE THREAD

**Issue by junedev** [exercism/go#1892]
For some exercises it makes sense to add some language specific test cases additional to what is listed in the [problem spec](https://github.com/exercism/problem-specifications) test cases.

Here an example where this would be helpful: https://github.com/exercism/go/issues/1451

Let's discuss ideas how to adjust the generator to incorporate additional test cases. The restriction should be that the new cases adhere to the format of the existing ones (e.g. no new properties are introduced).

**Comment by andrerfcsantos** [comment]
What about having a `canonical-data.append.json` in the `.meta` directory for the exercise?

**Comment by junedev** [comment]
@andrerfcsantos Great idea! That shouldn't be hard and the generator is in that directory already anyway.

So the task here is to change the [generator](https://github.com/exercism/go/blob/main/gen/gen.go) so that it checks whether `.meta/canonical-data.append.json` is present for the exercise. If it it is, the content should be combined with the content of the usual canonical-data.json file.

General information about the generator can be found here: https://github.com/exercism/go#generating-test-cases

**Comment by junedev** [comment]
@eklatzer Not sure whether you mean you want to include this in #2279 but if yes, it would be better if this would be separate PR. Otherwise if the added code for this feature has issues that blocks the other PR for now reason. And the more things are in one PR, the harder it is to review.

**Comment by eklatzer** [comment]
I will wait for #2279 to be merged and then I will do it

**Comment by eklatzer** [comment]
Note for future: we could use the feature of this issue in the exercise `reverse-string` as there is currently the following additional test case:
```
// mutiByteCases adds UTF-8 multi-byte case,
// since the canonical-data.json (generator data source for cases_test.go)
// doesn't have any such cases.
var multiByteCases = []reverseTestCase{
	{
		description: "a multi-byte test case",
		input:       "Hello, 世界",
		expected:    "界世 ,olleH",
	},
}
```

**Comment by eklatzer** [comment]
Same for `roman-numerals` (will also need adjustment in the generator):
```
invalidRomanNumeralTests := []romanNumeralTest{
		{description: "0 is out of range", input: 0},
		{description: "-1 is out of range", input: -1},
		{description: "3001 is out of range", input: 3001},
	}
```

**Comment by eklatzer** [comment]
Same for `two-bucket`:
```
var errorTestCases = []bucketTestCase{
	{
		"Invalid first bucket size",
		0, 5, 5, "one", "one", 1, 0, true,
	},
	{
		"Invalid second bucket size",
		3, 0, 3, "one", "one", 1, 0, true,
	},
	{
		"Invalid goal amount",
		1, 1, 0, "one", "one", 0, 1, true,
	},
	{
		"Invalid start bucket name",
		3, 5, 1, "three", "one", 4, 5, true,
	},
}
```

**Comment by junedev** [comment]
@eklatzer Please don't start on this yet. I think we need to discuss again what is the best approach here. I am not sure anymore the extra json file helps us much compared to what was done in those examples you found. I will leave some more thoughts on this later.

**Comment by junedev** [comment]
Sorry for putting this on hold, here my thoughts on the matter.

When I originally wrote this issue, I did not know we already had a "solution" for adding custom tests. Comparing the existing solution of appending test cases to the generated test cases list to the idea in this issue to have a separate json file, it feels to me the existing way might be better. The idea with the json file only works if the format in the json file fits exactly to the format in the problem spec canonical file. So someone who wants to add a test case needs to go there and figure out this format. In contrast, with the existing solution, the person just needs to look at the existing cases file and then write the item that should be appended in plain Go.
@eklatzer WDYT?

So my tendency would be to not add any feature to the generator and instead document this existing system in the readme (a link to an example would probably already go a long way here). In any case, I would like to keep this issue open to track the missing documentation.

**Comment by eklatzer** [comment]
I completely agree, do you want me to add the docs?
