### ISSUE TITLE
simple-cipher: ambiguous instructions and conflicting files

### ISSUE THREAD

**Issue by sbromberger** [exercism/go#1895]
simple-cipher bundles two `.go` files - `cipher.go` which defines an interface and `simple_cipher.go` which holds a package definition. It is unclear what the purpose of `cipher.go` is - in fact, I didn't even see it there when I started the exercise.

Following on, there is no indication outside of `cipher.go` that the exercise is intended to teach/demonstrate interfaces. This should be clear in the instructions, or the content of `cipher.go` should be moved into `simple_cipher.go` so that people opening the exercise will see what's intended.

The bigger picture would include tags on exercises that showed the concepts to be practiced, but that's probably worth a separate discussion.

**Comment by 4rc0s** [comment]
It seems this is still an issue? If you follow the instructions ("If someone doesn't submit a key at all, generate a truly random key of at least 100 lowercase characters in length.") your code will fail the test ("Argument for NewVigenere must consist of lower case letters a-z only. Values consisting entirely of the letter 'a' are disallowed. For invalid arguments NewVigenere returns nil.") I believe this is the test:
```
func TestVigenereWrongKey(t *testing.T) {
	for _, k := range []string{"", "a", "aa", "no way", "CAT", "3", "and,"} {
		if NewVigenere(k) != nil {
			t.Errorf("NewVigenere(%q): got non-nil, want nil", k)
		}
	}
}
```

**Comment by andrerfcsantos** [comment]
@4rc0s If you think there's still an issue with this, please open a new forum post in the Go section: https://forum.exercism.org/c/programming/go/19

In your post, please include an example of code that you think should pass the tests, but fails that particular one.
