### ISSUE TITLE
Tests being skipped instead of giving an error

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#1911]
In the `kindergarten-garden` and `matrix` exercises, tests are being skipped (with `t.Skip()`) in situations where they should error, example:

```go
func TestNamesNotModified(t *testing.T) {
	cp := append([]string{}, test6names...)
	_, err := NewGarden(test6.diagram, cp)
	if err != nil {
		t.Skip("TestNamesNotModified requires valid garden")
	}
	if !reflect.DeepEqual(cp, test6names) {
		t.Fatalf("NewGarden modified children argment.  " +
			"Arguments should not be modified.")
	}
	sort.Strings(cp)
	if reflect.DeepEqual(cp, test6names) {
		t.Skip("TestNamesNotModified requires names out of order")
	}
}
```

We should investigate if these tests should really be skipped and possibly convert the calls to `Skip` to calls to `Fail`.

**Comment by eklatzer** [comment]
Hey, I have checked the skipped parts and I think that both `t.Skip()` are only used to tell the developer of the tests if the used input (`test6.diagram`) would trigger the test-case to fail. The given test is only used to check, if `func NewGarden()` modifies the second parameter (`children []string`) in place. So here is what the if's with the `t.Skip` are for:

```
if err != nil {
		t.Skip("TestNamesNotModified requires valid garden")
	}
```
-->If the given input is not valid, you cannot know if the value of `children` is modified, as it could be modified after the check that returns the error

```
sort.Strings(cp)
	if reflect.DeepEqual(cp, test6names) {
		t.Skip("TestNamesNotModified requires names out of order")
	}
```
-->If the given input is already sorted, the test-case would not even fail, even if the implementation of `func NewGarden` would modify the value of `children` by sorting them, as this would result in the same output. Example:

```
var in = []string{Alice, Bob, Charlie, David}
NewGarden(..., in)
```
Even if `func NewGarden` sorts the students, the following check would not fail as the two slices are still the same.
```
if !reflect.DeepEqual(cp, test6names) {
		t.Fatalf("NewGarden modified children argment.  " +
			"Arguments should not be modified.")
	}
```


We could modify the test to be:
```
// The lazy way to meet the alphabetizing requirement is with sort.Strings
// on the argument slice.  That's an in-place sort though and it's bad practice
// to have a side effect.
func TestNamesNotModified(t *testing.T) {
	var diagram = `
			VCRRGVRG
			RVGCCGCV`

	//children must be unsorted to trigger test, if NewGarden uses sort.Strings
	var children = []string{"David", "Charlie", "Bob", "Alice"}
	var copyOfChildren = append([]string{}, children...)

	_, _ = NewGarden(diagram, children)

	if !reflect.DeepEqual(children, copyOfChildren) {
		t.Fatalf("NewGarden modified children argment.  " +
			"Arguments should not be modified.")
	}
}
```
We would still have the functionality of the test, but removed the confusing `t.Skip`. The test could also stay the same as it already is.

Reach out to me, if you want me to implement the suggested version

**Comment by eklatzer** [comment]
We could also change the `t.Skip` to `t.Fatalf`. If a developer changes the input used for the test, the CI-job will not pass, as the example solutions fail, but I do not know if test should fail, if the used input is not as expected. Here is, what it could look like:
```
func TestNamesNotModified(t *testing.T) {
	cp := append([]string{}, test6names...)
	_, err := NewGarden(test6.diagram, cp)
	if err != nil || sort.StringsAreSorted(cp) {
		t.Fatalf("TestNamesNotModified requires valid garden and unsorted children (check inputs of test-case)")
	}
	if !reflect.DeepEqual(cp, test6names) {
		t.Fatalf("NewGarden modified children argment.  " +
			"Arguments should not be modified.")
	}
}
```

**Comment by junedev** [comment]
I would recommend to use `t.Fatalf` instead of `t.Skip` as mentioned in the last comment above. But I would try to make it very clear in the failure message that this failure is not related to the student code, e.g. `"error in test setup: ..."`. (This is also how we handle such situation at work.)

@eklatzer With that input, do you want to go ahead an make a PR?

**Comment by eklatzer** [comment]
Yes, I will do after my vacation.
