### ISSUE TITLE
POV: Change exercise from graph to tree logic

### ISSUE THREAD

**Issue by ptillemans** [exercism/go#1918]
[Original Issue Titel: **POV exercise passes all tests with a noop mandatory function**]

The `AddNode` function is mandatory however a noop implementation satisfies all the tests... Apparently the information passed in is never needed/tested.

here is my solution (I cannot find a way to link to it)

``` go
package pov

type arcList map[string]string

type Graph struct {
	arcs arcList
}

func New() *Graph {
	return &Graph{arcs: make(arcList)}
}

func (g *Graph)AddNode(id string) {
}

func (g *Graph)AddArc(a, b string) {
	g.arcs[b] = a
}

func (g *Graph)ArcList() (list []string) {
 	for k, v := range g.arcs {
		 list = append(list, v + " -> " + k)
	}
	return list
}

func (g *Graph)ChangeRoot(oldRoot, newRoot string) (newGraph *Graph) {
	onPath := make(map[string]bool)
	newGraph = &Graph{arcs: make(arcList)}

	// find path between oldRoot and newRoot
	for p := newRoot; ; p = g.arcs[p] {
		onPath[p] = true
		if p == oldRoot {
			break
		}
	}

	// reverse arrow for edges on path, copy rest
	for child, parent := range g.arcs {
		if onPath[child] && onPath[parent] {
			newGraph.arcs[parent] = child
		} else {
			newGraph.arcs[child] = parent
		}
	}

	return newGraph
}
```

**Comment by junedev** [comment]
You raised an excellent issue here. Indeed `AddNode` and `AddArc` are tied to a very specific implementation of the Graph struct, that is (as you demonstrated) not necessary to have to solve the exercise. Furthermore those two methods are used in the tests to construct the Graph without being properly testable themselves (without assumptions about the structure of Graph or other tricks).

I checked how other tracks solved this problem. Here an example how the tests look in C#: https://github.com/exercism/csharp/blob/main/exercises/practice/pov/PovTests.cs

Most languages I checked don't have an equivalent of `AddNode` and `AddArc`. Instead, the constructor function for the Graph has a signature like this:
```go
New(value string, children ...*Graph) *Graph
```

Then, the Graph for the test case is built up like this without the need to make any assumptions about the implementation of Graph and without any additional methods besides the two that are required by the exercise itself (`ArcList` and `ChangeRoot`).
```go
graph := New("x", New("parent", New("siblingA"), New("siblingB")))
```

This would still hint to a certain structure of `Graph`, e.g. just holding an `arcList` would be harder. But on the other hand, the exercise is actually about [trees](https://en.wikipedia.org/wiki/Tree_(graph_theory)) not about generic [graphs](https://en.wikipedia.org/wiki/Graph_(discrete_mathematics)). I think the constructor pattern shown above helps a bit to enforce the notion of a tree (no cycles, every child is a tree in itself again, etc).

Currently, the instructions talk about `graph`, not `tree`. I think that is a bug and I will file an issue for it. The canonical test data and most languages already call the data structure `tree` not `graph` so we should do the same (independent of when the instructions will be fixed).

To some up, the **tasks** to address this issue would be:
- [ ] rename `Graph` to `Tree`
- [ ] remove `AddNode` and `AddArc`
- [ ] think about whether `ChangeRoot` is still a method (that potentially modifies the existing tree) or whether it should rather be a function that accepts a tree as an argument and returns a new tree
- [ ] change the `New` constructor to the pattern that was shown above
- [ ] update all affected exercise files
- [ ] think about whether the difficulty scoring of the exercise needs to be adjusted after those changes

The instructions.md file should NOT be changed. It originates from another repo.

General information about the structure of practice exercises can be found here: https://exercism.org/docs/building/tracks/practice-exercises

**Comment by andrerfcsantos** [comment]
For reference, I'll link the issue @junedev created in the problem specifications related to this: https://github.com/exercism/problem-specifications/issues/1874

We should keep an eye on that issue for potential changes in the `instructions.md` file.

**Comment by norbs57** [comment]
I am happy to work on this issue.

**Comment by andrerfcsantos** [comment]
@norbs57 All yours! Thanks for the interest in contributing to this issue.

Any questions you may have, feel free to ask!

**Comment by norbs57** [comment]
I have prepared a draft PR. The new material is in a new folder for now as I am unsure how it will be integrated:

- Will it replace the old POV exercise that worked with graph operations?
- Or will it be a new, independent exercise
- Potentially one could also merge both into one large POV exercises with separate sections for graphs and trees.

**Comment by andrerfcsantos** [comment]
@norbs57 This will replace the old POV exercise.
