### ISSUE TITLE
Linter failures are not picked up in the CI run on Windows

### ISSUE THREAD

**Issue by junedev** [exercism/go#1931]
If the linter that is executed via GitHub actions fails, this is correctly reported for Ubuntu and macOS. However, the run on Windows shows up as passed/green.

Example:
https://github.com/exercism/go/actions/runs/1417032474 / https://github.com/exercism/go/runs/4093326704 (not sure which link is "persistent")

I am not sure whether this also happens if the actual tests fail (e.g. because of a wrong exemple.go file). Might be an issue with the exit codes not being propagated properly. :shrug:

**Comment by andrerfcsantos** [comment]
Thanks for opening this. I was about to open a similar issue :D

My first impression is that we are trying to run `./bin/fetch-golangci-lint` and `./bin/test-without-stubs` in Windows using powershell, but these are bash scripts. I have to check, but I'm under the impression powershell is just refusing to run them.

So, what I'm thinking:

- [ ] Investigate the problem further and see if it is indeed a bash/powershell compatibility issue. If it is, see if there's a way to fix it in a simple manner (like putting powershell to run bash scripts, or maybe a simple change to the scripts can do it).
- [ ] If not, we might want to consider writing Powershell scripts that do the same as our bash scripts, and have one job for linux/mac and a different one for Windows in [exercise-tests.yml](https://github.com/exercism/go/blob/main/.github/workflows/exercise-tests.yml). The linux/mac job would call the bash scripts and the windows one would call the powershell scripts.
