### ISSUE TITLE
Gross Store: Add additional test case for AddItem

### ISSUE THREAD

**Issue by junedev** [exercism/go#1940]
The current [test cases](https://github.com/exercism/go/blob/8ca15493141fc0a897d4c4a04ec79dd1336c3432/exercises/concept/gross-store/gross_store_test.go#L41) for AddItem in the concept exercise `gross-store` do not cover the case that an item is added more than once. That means, if a student uses `bill[item] = units[unit]` instead of `bill[item] += units[unit]` in their code, they still pass all the tests.

An additional test case should be added that tests the behavior in case an item is added multiple times.

**Comment by andrerfcsantos** [comment]
Closing this as the PR was already merged,
