### ISSUE TITLE
Pythagorean triplets exercise could use more detailed explanation

### ISSUE THREAD

**Issue by halfdan** [exercism/go#1963]
The current explanation for this exercise is extremely short and leaves the user (me) guessing what is exactly expected in the three functions that are presented. I've personally done this exercise in at least 2 other languages where the tests were sufficient to figure out what was expected. For Go, it's unclear what Sum/Range should do. I also found that Sum is sensitive to the order in which the elements are returned.

**Comment by junedev** [comment]
@andrerfcsantos Do you know what the other two functions are supposed to do and if yes, could leave a note here in the ticket so this task becomes easier for a contributor to work on?

**Comment by andrerfcsantos** [comment]
The [stub we provide](https://github.com/exercism/go/blob/main/exercises/practice/pythagorean-triplet/pythagorean_triplet.go) already provides a good description of what those functions should do, but it wouldn't hurt to maybe add them to the `instructions.append.md`:

https://github.com/exercism/go/blob/89661d04e7a6b78e6c51e18f05c87de9e835ab22/exercises/practice/pythagorean-triplet/pythagorean_triplet.go#L5-L7

https://github.com/exercism/go/blob/89661d04e7a6b78e6c51e18f05c87de9e835ab22/exercises/practice/pythagorean-triplet/pythagorean_triplet.go#L11-L16

> I also found that Sum is sensitive to the order in which the elements are returned.

According to the description in the stub that's intended behavior. We might still want to relax that requirement. If so, we had to solve a similar problem in another exercise, and we probably should fix this in the same way: https://github.com/exercism/go/pull/1791

**Comment by halfdan** [comment]
Interesting - I must have been on an old version of this exercise as neither the downloaded files nor the editor showed me comments on those functions.

**Comment by andrerfcsantos** [comment]
This was a rather recent change: https://github.com/exercism/go/pull/1917

Did you start the exercise before November?

If you started an exercise a while ago, but still want to get these changes, the best thing to do is to open the editor, click on the 3 dots and chose "Revert to exercise start", which will force the editor to update to the most current changes (Exercism does this because it doesn't want to overwrite possible changes you might have to the file).

**Comment by halfdan** [comment]
I've since completed the exercise after (correctly) guessing the intent behind those functions, but I'll note that I don't remember being prompted on the website to update to a more recent version of the exercise (which I have seen on other exercises).

I think the original request still stands even with the code comments. All other exercises on the Go track so far had a list of instructions on what to implement and it would be nice to get this exercise in line with that.

**Comment by junedev** [comment]
I will leave this issue open. The task here is to move the instructions from the stub file into instructions.append.md.

General information about practice exercises can be found here if needed: https://exercism.org/docs/building/tracks/practice-exercises#Files
