### ISSUE TITLE
error-handling: ensure `Close` is called only once

### ISSUE THREAD

**Issue by fyrchik** [exercism/go#1967]
Related to #1939 .

The exercise requires the usage of `defer` (the code can panic). This in turn raises a questions about some inner workings of `defer`. 

Answering to the comment in PR: https://github.com/exercism/go/pull/1939#issuecomment-961216677
> Is there any motivation behind this? Did you see any particular solution calling Close() more than once?

In one of the solutions I have mentored there was something like this:
```
...
defer r.Close()
defer func() {
   if recover() != nil {
      ...
      r.Close()
   }
}
```

> I don't believe this adds much or solves any problem with the exercise.

1. Knowing how multiple `defer`s are executed in case one of them handles panic with `recover` is something worth learning IMO.
2. If `r.Close` closes some channel we want to be sure it is called exactly once. So I think it is a reasonable requirement.

**Comment by andrerfcsantos** [comment]
Thanks for clarifying!

I'm now convinced this is a good change.
