### ISSUE TITLE
List Ops: undefined func

### ISSUE THREAD

**Issue by MayrJo170211** [exercism/go#1968]
https://github.com/exercism/go/blob/8de5b265ce06df2057e1c4d7e0a0bd9a2fb92ba6/exercises/practice/list-ops/list_ops_test.go#L11

```sh
# listops [listops.test]
./list_ops_test.go:11:11: undefined: binFunc
FAIL	listops [build failed]
'/usr/local/go/bin/go test --short --json .' returned exit code 2: exit status 2
```

**Comment by junedev** [comment]
Good point. The following type definitions were removed from the stub but they should also be removed from the tests (replaced with the actual definition instead of the custom type):
```go
type predFunc func(int) bool
type binFunc func(int, int) int
type unaryFunc func(int) int
```
Alternatively, these could be put back in consistently.

**Comment by ppmasa8** [comment]
I'm going to try to solve this problem, but I have one question. The type of the first argument of Foldl is different between list_ops.go and example.go, which one should I use?

**list_ops.go**
```go
func (s IntList) Foldl(fn func(int) bool, initial int) int {
	panic("Please implement the Foldl function")
}
```
**example.go**
```go
func (s IntList) Foldl(fn binFunc, initial int) int {
```

**Comment by andrerfcsantos** [comment]
If we are going to remove the custom types, they should also be removed from the example, which means using the full form of the type `func(int) bool` everywhere.
