### ISSUE TITLE
Non-zero values returned wit non-zero errors in `protein_translation_test.go`

### ISSUE THREAD

**Issue by chubin** [exercism/go#1972]
This test here

https://github.com/exercism/go/blame/main/exercises/practice/protein-translation/protein_translation_test.go#L145

seems to be incorrect, at least this is not idiomatic in Go, return values with non-nil errors.
There is one important exception, sentinel errors (like `io.EOF` for example), but here it is not the case, as far as I can judge.

Maybe we should not encourage learning writing non-idiomatic (though not directly erroneous) code,
and eliminate or correct this test?

**Comment by andrerfcsantos** [comment]
I agree.

The task here is to correct the test. When the function returns an error, we should check the error and ignore the resulting slice. Alternatively, we can check if the resulting slice is `nil` or empty when an error occurs, but I think just checking the error is enough.

**Comment by ppmasa8** [comment]
I am trying to solve this problem. Am I correct in saying that what I need to fix here is to make the tryptophan in L145 an empty string?

**Comment by junedev** [comment]
I would recommend to use `nil` instead of an empty slice as nil is the zero value of that variable/field.
