### ISSUE TITLE
Chessboard: Instructions need improvement

### ISSUE THREAD

**Issue by IAmSurajBobade** [exercism/go#1974]
https://github.com/exercism/go/blob/d213d8ddc46022c99e12ab11ed15122132240dd0/exercises/concept/chessboard/.docs/instructions.md?plain=1#L3

No mention of how a chessboard value is set. Please read the instructions once again, the explanation and instructions are not clear.

**Comment by andrerfcsantos** [comment]
What specifically do you think should be changed so the instructions are more clear?

**Comment by junedev** [comment]
I am closing this since there was no feedback. Happy to re-open in case we get more info.

**Comment by shakhzodkudratov** [comment]
Unclear how to build structs
