### ISSUE TITLE
Create new Concept: Variadic Functions

### ISSUE THREAD

**Issue by junedev** [exercism/go#1989]
## Getting Started

If you have not yet contributed to concept exercises before, this task requires some upfront reading to acquire the necessary background knowledge.

Here you can read about what Concept Exercises are and how they are structured:

- [What are Concept Exercises?](https://exercism.org/docs/building/product/concept-exercises)
- [Concept Exercises](https://exercism.org/docs/building/tracks/concept-exercises)
- [Concepts](https://exercism.org/docs/building/tracks/concepts)

## Motivation

The current exercise "Card Tricks" includes `append` (which is a variadic function) and the `x...` syntax when passing arguments to a variadic function. None of this is properly introduced currently. We want to add another concept to fix this. "Card Tricks" will then later be changed to teach `slices` and this new concept at the same time.

## Task

The task here is to create a new concept `variadic-functions` that explains what it means to prefix the last function parameter with `...` and what it means if you pass an argument with `...` as suffix.

## Out of Scope

Changing the "Card Tricks" exercise is out of scope for this issue, there will be a separate issue for this.

## Resources
Before writing this concept, please take a close look at the Go spec so the content you write will be correct:
- https://go.dev/ref/spec#Function_types
- https://go.dev/ref/spec#Passing_arguments_to_..._parameters

This article might be good for the links section:
- https://golangbot.com/variadic-functions/

**Comment by myworkcircle** [comment]
I would like to contribute to this issue, can anyone help ne how can i start, can i simply clone and contribute to the issue, or do i need certain permissions?

**Comment by junedev** [comment]
@myworkcircle Thanks for volunteering for this task! You don't need any special permissions but you need to fork the repository first before you clone it. Then you work on your fork and create a PR from there to the original repo. If you are not familiar with the flow, here is a good introduction that explains this step by step: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by junedev** [comment]
Did you find your way around in the repo? Let me know in case you have any more questions.

**Comment by myworkcircle** [comment]
yes @junedev, i have made changes at my end. Sorry got late in raising a pr. Had some issues with my older system. 
Raised a pr :- https://github.com/exercism/go/pull/2091
