### ISSUE TITLE
Bank Account: race detector not run

### ISSUE THREAD

**Issue by bitfield** [exercism/go#2021]
Solution 88c019dd66f14fd088b1fbc26af734e8 does not obtain the mutex when calling Balance, yet the tests pass. For this exercise, the tests need to be run with the `-race` flag to catch data races.

**Comment by junedev** [comment]
Thanks for the hint! The test runner currently does not include this capability. I created an issue for this in the test runner repo: https://github.com/exercism/go-test-runner/issues/62 Once that issue is addressed, we can use the capability for the bank account exercise.
