### ISSUE TITLE
booking-up-for-beauty: misleading example for output format on exercise 5

### ISSUE THREAD

**Issue by fmmatheus** [exercism/go#2035]
### Description

Exercise 5:

> 5. Return the anniversary date of the salon's opening
> Implement the AnniversaryDate function that returns the anniversary date of the salon's opening for the current year in UTC.
> 
> Assuming the current year is 2020:

```go
AnniversaryDate()

// Output: 2020-09-15
```

Function signature:

```go
func AnniversaryDate() time.Time {
	// solution here
}
```

### Issue

The output example suggest a formatted time `2020-09-15` which will require a `string` type, when the function signature requires a `time.Time` output. Based on exercise instructions, students will use the function `time.Date()`, which will return a different output.

### Suggestion

Use the output for `time.Date()` and specify that the time of the day doesn't matter:

```go
AnniversaryDate()

// Output: 2020-09-15 00:00:00 +0000 UTC
```

**Comment by andrerfcsantos** [comment]
Good catch, thanks for bringing this to our attention.

I agree with changing the output to `2020-09-15 00:00:00 +0000 UTC` as it is what calling `String()` on a date will output. Along with a clarification that the time of day doesn't matter, might be worth to reinforce that the output is a `time.Time` representing a date.

**Comment by junedev** [comment]
I would be fine with this change as a quick fix. Long term we should think about maybe changing the task so that a string is returned there which is really `2020-09-15` and teaching `time.Format` that way.
