### ISSUE TITLE
Lasagna Master: Improve task 3 (AddSecretIngredient)

### ISSUE THREAD

**Issue by junedev** [exercism/go#2036]
Lasagna Master was ported from JavaScript. Task 3 (`AddSecretIngredient`) was meant to make the student practice that in some cases the argument can/will be modified and the modification is visible outside of the function. In contrast, in task 4 the student practices NOT to modify the argument.

Because of the 1to1 port from JavaScript, the practice goal for task 3 got lost because currently `append` is used which creates a new slice so the arguments are not modified. The practice goal can be restored by changing the task so that the first list always ends with an element `"?"` and the secret ingredient is supposed to be inserted in that place. The function should not have any return value.
The solution could look like this:
```go
func AddSecretIngredient(friendsList, myList []string) {
	myList[len(myList)-1] = friendsList[len(friendsList)-1]
}
```

To implement this change, make sure to adjust all relevant exercise files.
See https://exercism.org/docs/building/tracks/concept-exercises for the general structure.

**Comment by sougat818** [comment]
Hi @junedev , I would like to work on this.
