### ISSUE TITLE
Implement new Concept Exercise: Regular Expressions

### ISSUE THREAD

**Issue by junedev** [exercism/go#2037]
## Getting Started

If you have not yet contributed to concept exercises before, this task requires some upfront reading to acquire the necessary background knowledge.

Here you can read about what Concept Exercises are and how they are structured:

- [What are Concept Exercises?](https://exercism.org/docs/building/product/concept-exercises)
- [Concept Exercises](https://exercism.org/docs/building/tracks/concept-exercises)
- [Concepts](https://exercism.org/docs/building/tracks/concepts)

If you have not done so yet, it is probably also helpful to do a couple of "Learning Exercises" (this is how they are called on the site) yourself. You can also look at the code of an existing concept exercise like [`welcome-to-tech-palace`](https://github.com/exercism/go/tree/main/exercises/concept/welcome-to-tech-palace) for reference.

Also be aware of these general guidelines.

- [Exercism Markdown Specification](https://exercism.org/docs/building/markdown/markdown)
- [Exercism Formatting and Style Guide](https://exercism.org/docs/building/markdown/style-guide)

## Goal

The goal here is to create a new concept exercise to teach how to use regular expressions in Go. The concept needs to be written from scratch, the exercise can be ported from another track (see details below).

## Concepts

The following concept needs to be created. You can use the `introduction.md` file of the concept also as `introduction.md` file of the exercise. No need to create different content at this point. Additionally, if you want to save some time it is ok to not have an extensive `about.md` for now. It can also be mainly the `introduction.md` content, maybe with some additions you would like to make.

- `regular-expressions`

## Learning Objectives

In the concepts the student should learn about the following topics and then practice them in the concept exercise.

- which flavor of regex syntax is used in Go and its performance
- limitations of regex in Go (see "Caveats" section here: https://swtch.com/~rsc/regexp/regexp3.html)
- how to create a regular expression with `Compile`/`MustCompile` and when to use which
- how to use the most common regex related functions (maybe what is mentioned here https://gobyexample.com/regular-expressions is a good starting point)
  - understanding difference between `MatchX` and `FindX`
  - understanding that there are byte and string versions of the functions
- understanding the different parts of the `Submatch` results
- how to set flags
- using e.g. https://regex101.com/ to help with writing/reading regex

## Out of Scope

Explaining how to write regular expressions themselves is out of scope for the concept here but we should link to some good resource a student could read to learn about them from scratch. We don't do this as part of the concept because Exercism assumes the student is already fluent in another language and most languages include some form of regular expressions.

## Prerequisites

- `runes` so the student understand the string vs bytes distinction
- `slices` to understand the result of `FindX` etc
- `methods` because most functionality is provided by methods defined for the `RegExp` type

## Exercise Idea

[C# "Parsing Log Lines" Exercise](https://github.com/exercism/csharp/tree/main/exercises/concept/parsing-log-files) could serve as template.

In case you port that exercise, make sure to check all tasks make sense for Go and whether some additional task needs to be added to cover some Go specific content.

## Resources

Here some links that might be helpful as a starting point and/or for the links section of the concept:

- https://pkg.go.dev/regexp
- https://pkg.go.dev/regexp/syntax
- https://github.com/google/re2/wiki/Syntax
- https://gobyexample.com/regular-expressions

## How to proceed

1. Accept this issue by saying "I'd like to work on this" (no need to wait for a response, just go with it).
2. Use this issue to discuss any questions you have.
3. Create a PR and set "exercism/go" as reviewers when you are done. Additionally you can write in #maintaining-go that your PR is ready for review. Once you incorporated any critical feedback that the reviewer might give you and the PR is approved, it will be merged by a maintainer.

**Comment by norbs57** [comment]
I would be happy to have a go at implementing a basic version of this including a concept exercise.

**Comment by junedev** [comment]
@norbs57 You wrote on Slack that you didn't cover all parts of what was described in this issue. If that was the case in the end, please create another issue that states what is currently missing (would probably be good to include a link to this issue as well).

**Comment by norbs57** [comment]
Current coverage of Learning Objectives: 

* which flavor of regex syntax is used in Go and its performance
   => No details given, only link 
* limitations of regex in Go (see "Caveats" section here: https://swtch.com/~rsc/regexp/regexp3.html)
  =>  No details given, only link 
* how to create a regular expression with `Compile/MustCompile` and when to use which
  => Done 
* how to use the most common regex related functions (maybe what is mentioned here https://gobyexample.com/regular-expressions is a good starting point)
  => Overview given as well as an explanation of five core functions with examples 
* understanding difference between `MatchX` and `FindX`
  => Explained functions `MatchString` and `FindString` and included examples 
* understanding that there are byte and string versions of the functions
  => Mentioned in overview 
* understanding the different parts of the `Submatch` results
  => Explained function `FindStringSubmatch` briefly with some examples 
* how to set flags 
  => Missing in concept. Mentioned in hints of associated exercise
* using e.g. https://regex101.com/ to help with writing/reading regex
  => Done

**Comment by junedev** [comment]
@norbs57 Thanks for the summary, I created a small follow up issue.
