### ISSUE TITLE
Implement new Concept Exercise: Randomness

### ISSUE THREAD

**Issue by junedev** [exercism/go#2038]
## Getting Started

If you have not yet contributed to concept exercises before, this task requires some upfront reading to acquire the necessary background knowledge.

Here you can read about what Concept Exercises are and how they are structured:

- [What are Concept Exercises?](https://exercism.org/docs/building/product/concept-exercises)
- [Concept Exercises](https://exercism.org/docs/building/tracks/concept-exercises)
- [Concepts](https://exercism.org/docs/building/tracks/concepts)

If you have not done so yet, it is probably also helpful to do a couple of "Learning Exercises" (this is how they are called on the site) yourself. You can also look at the code of an existing concept exercise like [`welcome-to-tech-palace`](https://github.com/exercism/go/tree/main/exercises/concept/welcome-to-tech-palace) for reference.

Also be aware of these general guidelines.

- [Exercism Markdown Specification](https://exercism.org/docs/building/markdown/markdown)
- [Exercism Formatting and Style Guide](https://exercism.org/docs/building/markdown/style-guide)

## Goal

The goal here is to create a new concept exercise to teach randomness (random number generation).
The concept needs to be written from scratch, the exercise can be ported from another track (see details below).

## Concepts

The following concept needs to be created. You can use the `introduction.md` file of the concept also as `introduction.md` file of the exercise. No need to create different content at this point. Additionally, if you want to save some time it is ok to not have an extensive `about.md` for now. It can also be mainly the `introduction.md` content, maybe with some additions you would like to make.

- `randomness`

## Learning Objectives

In the concepts the student should learn about the following topics and then practice them in the concept exercise.

- how to create pseudo random numbers with the `math/rand` package (float and int)
- what seeding is for and how/where to define the seed in the code
- that there are some helpers in the `math/rand` package line `Shuffle` and `Perm`
- when and how to create cryptographically secure random numbers with `crypto/rand` (does not have to be part of the exercise but would be good to mention in the concept to raise security awareness)

## Out of Scope

- details of pseudo random number generation in general
- discussing the different algorithms for random number generation
- details on entropy sources etc

## Prerequisites

- `numbers`

Other prerequisites should be added as needed to solve the specific exercise.

## Exercise Idea

[C# "Parsing Log Lines" Exercise](https://github.com/exercism/csharp/tree/main/exercises/concept/parsing-log-files) could serve as template.

In case you port that exercise, make sure to check all tasks make sense for Go and whether some additional task needs to be added to cover some Go specific content.

## Resources

Here some links that might be helpful as a starting point and/or for the links section of the concept:

- https://pkg.go.dev/math/rand
- https://pkg.go.dev/crypto/rand
- https://gobyexample.com/random-numbers

## How to proceed

1. Accept this issue by saying "I'd like to work on this" (no need to wait for a response, just go with it).
2. Use this issue to discuss any questions you have.
3. Create a PR and set "exercism/go" as reviewers when you are done. Additionally you can write in #maintaining-go that your PR is ready for review. Once you incorporated any critical feedback that the reviewer might give you and the PR is approved, it will be merged by a maintainer.

**Comment by norbs57** [comment]
I am happy to have a go at this.
