### ISSUE TITLE
Minesweeper: deviance from problem specs and other tweaks

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#2046]
I noticed the Minesweeper exercise deviates from the problem specs in a way that is not documented. The [original exercise](https://github.com/exercism/problem-specifications/blob/main/exercises/minesweeper/description.md) asks the student the student to fill each square of a board with the number of mines adjacent to that square. The Go version of the exercise deviates from this spec by adding a border to the board. However, there's nothing in the description talking about this additional border. The tests check if the border is "correct", without explicit saying what makes a border correct (the student has to look at the tests and do some guesswork).

Overall, this exercise feels like it could use "more love". What I think we should look at:

- [ ] Decide if we want to keep the deviance from problem specs or not. If we want to keep it, we must include an additional description  mentioning the board border and we should add more custom tests checking if the border is correct (as of right now, they allow some incorrect borders). I think we should adhere to the problem specs, as I don't think adding a border to the board adds much to the exercise, but I'm interested to see other opinions.
- [ ] Improve [the tests](https://github.com/exercism/go/blob/main/exercises/practice/minesweeper/minesweeper_test.go) organization. Might be worth to organize the tests into named sub-tests that can be picked up by the test runner, like what happens with other exercises. This would improve the experience for someone using the online editor and the testing experience in general.
- [ ] [The board](https://github.com/exercism/go/blob/fddd098d153121ae0d302ec1ae91f73655e57a3c/exercises/practice/minesweeper/board.go#L5) is a `[][]byte`, which I find a bit weird, not sure if anyone else feels the same. Seems like a more natural choice would be `[][]rune`. For some solutions this makes no difference, but there are other solutions where students make smaller functions, and I find a bit weird seeing them receiving `byte`s representing characters of the board. I feel like working with `rune`s would be more appropriate.

**Comment by junedev** [comment]
I went digging around a bit and I found out that the exercise was added to the Go track 8 years ago when the canonical test data for this exercise did not exist yet. The description in problem spec at that time contained the border and it was removed from there 2 years ago: https://github.com/exercism/problem-specifications/pull/1602. The canonical test data never contained the border.

In conclusion, imo we should follow the decision made for problem spec to remove the border. So the main task here would be to change the exercise so it matches the problem spec version.

I have no strong preference regarding byte vs. rune here. Rune is probably a bit more idiomatic.

**Comment by norbs57** [comment]
I'd be happy to have a go at this. 

I noticed that in C# and Java APIs, there is an `Annotate` function that takes a slice of strings and returns a slice of strings. I would suggest following this example. This would resolve the byte-vs-rune issue as neither appears in the API.

**Comment by andrerfcsantos** [comment]
Assigned! Thanks for taking a look at this.

I have no problems on having a slice of strings too.
