### ISSUE TITLE
Implemented tests not matching `tests.toml`

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#2056]
The [saddle-points](https://github.com/exercism/go/tree/main/exercises/practice/saddle-points) exercise implements [4 tests](https://github.com/exercism/go/blob/main/exercises/practice/saddle-points/saddle_points_test.go), however [tests.toml](https://github.com/exercism/go/blob/main/exercises/practice/saddle-points/.meta/tests.toml) specify a lot more. There are probably more exercises in this situation.

This might throw off configlet, which will read `tests.toml` to know which tests are implemented, when those tests might not be actually implemented.

**Comment by eklatzer** [comment]
Hey, I think this will be done when the discussion in #2279 is finished so you could assign me
