### ISSUE TITLE
Wrong mention of current domain being golang.org

### ISSUE THREAD

**Issue by davidandradeduarte** [exercism/go#2085]
In https://exercism.org/tracks/go/concepts/basics there's a mention to `golang.org` being the current domain, which isn't true at this point, since `go.dev` is the new domain.

Should be rephrased to:
... _Golang because of its **previous** domain name, golang.org, but the proper name is Go._ ...

**Comment by junedev** [comment]
Good point. Would you like to provide a PR?

Here are the files where this needs to be changed:
- https://github.com/exercism/go/blob/main/concepts/basics/introduction.md
- https://github.com/exercism/go/blob/main/concepts/basics/about.md
