### ISSUE TITLE
linked-list: `Val` field accessed in tests

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#2090]
The stub for `linked-list` has this comment:

https://github.com/exercism/go/blob/9d5b5eba3d1f214ff777a3e4cb0396313453a6a4/exercises/practice/linked-list/linked_list.go#L3

This gives the idea that the student is entirely free to define the `Node` and `List` structs freely, however this is not totally true for the `Node` struct. Since our tests access a `Val` field on elements, the `Element` struct **must** include a `Val` field:

https://github.com/exercism/go/blob/9d5b5eba3d1f214ff777a3e4cb0396313453a6a4/exercises/practice/linked-list/linked_list_test.go#L48

https://github.com/exercism/go/blob/9d5b5eba3d1f214ff777a3e4cb0396313453a6a4/exercises/practice/linked-list/linked_list_test.go#L113

This means that a student can have a perfectly good solution, but the tests can still fail if the student didn't call the field exactly `Val` or decided to make all fields private. The student then might realize the change they need to make, but it can be annoying to have to make a trivia rename change just to make the tests happy. How I think we can improve this:

* In the stub, provide a definition of `Node` to the student that includes the `Val` field, along with a comment explaining what is supposed to be. Also might be worthwhile to have a comment clarifying that the struct might not be complete and other fields will probably help. This has the advantage of not requiring solutions currently passing the tests to change.
* Alternatively, we require an additional method `func (n *Node) Val() interface{}` that returns the value stored in a node and we use that method in the tests. Since this function will be provided in the stub, this has the advantage of making immediately clear to the student that obtaining a value from a `Node` will be required, giving total freedom to the student to define the struct. The disadvantage is that all solutions currently passing the tests will have to be updated.

**Comment by junedev** [comment]
I would go with the first option listed above. However, I would not type out the Node struct in the stub file with `Val` set and then a comment regarding other fields. Instead I would add another comment below the existing one saying that the test expects the Node to include an exported field with name `Val`. Then the student can still go an figure out the data type, other fields etc.

**Comment by junedev** [comment]
I also prefer `Value` over `Val` but its not critical.

**Comment by nahuakang** [comment]
If no one has picked this up, can you @junedev please assign it to me? 🙏
