### ISSUE TITLE
Exercises' Community Solutions are visible without solving

### ISSUE THREAD

**Issue by olumidesan** [exercism/go#2092]
Hi, Exercism.

Not sure if this is a bug or an Easter Egg.

**Context**:
As a logged in user, the Community solutions for exercises are only visible **after** a valid solution has been submitted. The Community Solutions button is disabled prior to my submission of a valid solution.

**Bug (on the [WebApp](https://exercism.org))**
I noticed I can view the community solutions of any exercise without solving it by simply appending `/solutions` to the url of the current page and loading the page, despite the Community Solutions button still being disabled.

So, if the exercise I'm yet to solve is: https://exercism.org/tracks/go/exercises/census, navigating to https://exercism.org/tracks/go/exercises/census/solutions shows me all the Community Solutions -- which I'm guessing shouldn't be allowed.

**Comment by junedev** [comment]
This was discussed in out Slack channel and it was decided this is a "feature" for now. See https://github.com/exercism/exercism/issues/5850. Closing this as duplicate.
