### ISSUE TITLE
test case expects 0.0 == parseInt("4")

### ISSUE THREAD

**Issue by venkateshpitta** [exercism/go#2107]
`        if ExtractFancyNumber(fnb) == 4 {
                // the test case says so --shrug--
                return fmt.Sprintf("This is a fancy box containing the number 0.0")
        }
`
is required to satisfy
`                {
                        description: "Describe a valid different fancy number",
                        input:       differentFancyNumber{"4"},
                        want:        "This is a fancy box containing the number 0.0",
                },
`

**Comment by andrerfcsantos** [comment]
Closing this for the same reason as https://github.com/exercism/go/pull/2108

Let's discuss this in https://github.com/exercism/go/issues/2110
