### ISSUE TITLE
The Farm: Instructions can be more clear

### ISSUE THREAD

**Issue by MikaeelMF** [exercism/go#2109]
Hi!
I hope all are doing great!

In the instructions, I've found that it is not explicitly clear what should happen in the case of `ErrScaleMalfunction` and `fodder < 0`. It can mislead one to believe it is counted as "any other error" or all cases of `fodder < 0` is a `negative fodder` error.
To make this clear in instructions, I think it is a good idea to add a new subsection in instructions on specifying different cases for `ErrScaleMalfunction`.

I would like to know what are your thoughts on this.
Thank you!

**Comment by andrerfcsantos** [comment]
Thanks for opening this issue!

> In the instructions, I've found that it is not explicitly clear what should happen in the case of ErrScaleMalfunction and fodder < 0

I don't see this as a problem as if there's an `ErrScaleMalfunction` and you multiply a negative fodder value by 2, it'll keep being negative, so I don't think there's doubt that a negative fodder always returns a negative fodder error, regardless of `ErrScaleMalfunction`. But maybe I'm overlooking something?

Where I see potential confusion is if we have `fodder < 0` and `cows < 0`, where is not clear what should be returned: negative fodder error or a `SillyNephewError`? Returning one or the other just depends on the order the check is made, so it might be worth have the description clarify this.

**Comment by MikaeelMF** [comment]
Thanks for your reply, André!
The main confusion that this might make is if one considers `ErrScaleMalfunction` and `fodder>0` as a single case of error. This will result in considering `ErrScaleMalfunction` and `fodder<0` as another form of error and returning 0 and the same error by mistake. Since we also have the test case with negative fodder and no error as well.

Things might be a bit more clear by writing:
"For any other error besides `ErrScaleMalfunction`, return `0` and the error."
For example instead of using :
For any other error, return `0` and the error.

Of course, this can be only my problem and I am overthinking things! 😅 

On your point about negative fodder and cows, I totally agree! 👍

**Comment by MikaeelMF** [comment]
I have created a PR to address both issues. it would be great if you could review it.
