### ISSUE TITLE
sorting-room: make edge case of "Describe a fancy number box" clearer

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#2110]
I've seen some reports of students this being confusing by this and it is something we can improve.

Right now we have the following test for task 4 "Describe a fancy number box" of the exercise `sorting-room`:

https://github.com/exercism/go/blob/8437f72dd89fc9d743927e88fcd0c5cef75b08dc/exercises/concept/sorting-room/sorting_room_test.go#L135-L139

The point of this test is to check if the student is correctly checking for the `FancyNumber` type. Since `differentFancyNumber` is not a `FancyNumber`, solutions should not attempt to parse the string as a number. This test tries to catch that by having something that is not a `FancyNumber` with a string with a valid number.

Event though the instructions clearly say that something that is not a `FancyNumber`, clearly the message is not getting through, as we have a lot of people just assuming that the test case is wrong.

Some ways I can see this being improved (but suggestions are also welcome):

* Change the description of the test `"Describe a valid different fancy number"`. I understand this description can be misleading as it hints that the number is "valid". However, the "valid" means that the string is a valid number, not that `differentFancyNumber` is a valid `FancyNumber`. Making the wording more clear would help I think to clear some of the confusion.
* Maybe change the wording in the task description itself to make this extra clear.

**Comment by norbs57** [comment]
Currently the example  in the instructions is as follows: 

```
fmt.Println(DescribeFancyNumberBox(FancyNumber{"10"}))
// Output: This is a fancy box containing the number 10.0
fmt.Println(DescribeFancyNumberBox(AnotherFancyNumber{"one"}))
// Output: This is a fancy box containing the number 0.0
```

Maybe there would be less confusion if the second example was changed so that the string parsed as an int? 

```
fmt.Println(DescribeFancyNumberBox(AnotherFancyNumber{"4"}))
// Output: This is a fancy box containing the number 0.0
```

I think there is a similar issue in Section 3 "...extracting the number from a fancy number box" , but maybe students did not stumble about this because there was no corresponding test case.

**Comment by junedev** [comment]
@andrerfcsantos @norbs57 Is this issue resolved by the PR that was merged or is there more we want to do here?

**Comment by andrerfcsantos** [comment]
@junedev Yes, this solved. Not entirely sure why he PR being merged didn't close this, but thanks for pointing it out.
