### ISSUE TITLE
Cars Assemble: Error in return value of test case

### ISSUE THREAD

**Issue by jewthon** [exercism/go#2122]
There is a problem in #2083 
Problem : the expected return type in test case 14 and 15 is float but the testcase it is receiving is in int. 
Solution : I want to make correction is the test case return value 

Please assign me this issue

**Comment by andrerfcsantos** [comment]
Hi!

Thanks for taking the time to write an issue.

Maybe I'm missing something, but I don't see the issue. Tests 14 and 15 for me are these ones:

https://github.com/exercism/go/blob/9ecfb014112598afd9f2d77c12e2ee46dc711d37/exercises/concept/cars-assemble/cars_assemble_test.go#L147-L156

This is in the `TestCalculateCost` function, that tests the `CalculateCost` function. `carsCount` and `want` are `int` and `unint` respectively:

https://github.com/exercism/go/blob/9ecfb014112598afd9f2d77c12e2ee46dc711d37/exercises/concept/cars-assemble/cars_assemble_test.go#L127-L131

Which are exactly the argument and return types `CalculateCost` expects:

https://github.com/exercism/go/blob/9ecfb014112598afd9f2d77c12e2ee46dc711d37/exercises/concept/cars-assemble/cars_assemble.go#L16-L18

Maybe you are referring to a different test case?

**Comment by jewthon** [comment]
Thanks for reaching me out .
But even if I am including the  codition in raw but still it is given error
I can show you

**Comment by andrerfcsantos** [comment]
If you are detecting the error in a particular solution, yes, please post the solution here.

**Comment by andrerfcsantos** [comment]
@jewthon Sure, no problem, take your time!

If you believe the problem might be with your solution, you can ask for mentoring and a mentor will help you see if there's anything wrong with your solution or are the tests that are potentially wrong.

If on the other hand you strongly believe the problem are the tests, you can post the problematic solution here and we can take a look.

**Comment by jewthon** [comment]
Thanks, I'll check it out.

**Comment by andrerfcsantos** [comment]
@jewthon Any news on this?

**Comment by jewthon** [comment]
Not yet!

**Comment by junedev** [comment]
@jewthon Did you start this exercise some months ago and then continued later on? There was a different version of this exercise before, maybe that is causing the issue.

**Comment by jewthon** [comment]
I also doubt that. I think this is the reason why I am getting error. Ok I
got you
