### ISSUE TITLE
POV: Make test structure more test runner friendly

### ISSUE THREAD

**Issue by junedev** [exercism/go#2134]
Currently, the structure of the tests differs from our usual patterns and is not very good for the test runner.

We should investigate, whether we can bring it more into this format: https://github.com/exercism/go-test-runner#subtest-format-specification (This might mean that this causes some duplication which is ok.)

Even if we can't reach that ideal structure, we should make sure that the cases_test.go file only contains the test case slices, not also parts of the test code. Currently, test code being in that helper file leads to issues where the error in the test output is not properly associated with the actual test case that caused it.

**Comment by norbs57** [comment]
I'd be happy to have a go at this.
