### ISSUE TITLE
Vehicle purchase exercise, introduction: UTF-16 link and string order

### ISSUE THREAD

**Issue by norbs57** [exercism/go#2147]
The [introduction to this exercise](https://github.com/exercism/go/blob/main/exercises/concept/vehicle-purchase/.docs/introduction.md) contains the following paragraph: 
```text 
The comparison operators above can also be used to compare strings.
In that case a dictionary (lexicographical) order is applied.
You can find a list of the exact order of all the characters [here][utf-16-list].
```

One of our students raised two issues about this: 

1.  The link is to a UTF-16 resource. This is confusing as Go strings are UTF-8 encoded. 

2. The last two sentences suggest that the ordering of Go strings is lexical based on **characters**. On the other hand, the Go spec says: ["string values are ... ordered, lexically **byte-wise**." ](https://go.dev/ref/spec#Comparison_operators)
 
I am unsure how to best resolve this. According to the Wikipedia UTF-8 page, sorting UTF-8 strings by byte or code-points gives the same result. But I don't think we want to explain that in this document. 

Perhaps the easiest solution would be to remove the last sentence in that paragraph. As an introduction to the sample string comparisons below, we could add a phrase such as `For example:`.  

Also, should we change the second sentence so that it reads: 
```text
In that case a lexicographical (dictionary) order is applied.
```
and replace the term "dictionary order" with "lexicographic order" throughout in `hints.md` and `introduction.md`?

**Comment by andrerfcsantos** [comment]
I agree with both suggestions.

> According to the Wikipedia UTF-8 page, sorting UTF-8 strings by byte or code-points gives the same result. But I don't think we want to explain that in this document.

Going into the details of utf-8 here is unnecessary indeed.
