### ISSUE TITLE
Clarify when an exercise is tested with the `-race` flag.

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#2155]
For some exercises, we are running the tests with the `-race` flag. The tests that run with this flag have a custom property in its `config.json`. Here's `bank-account` for example:

https://github.com/exercism/go/blob/920eb320d4dc6f569f55d65c4b4a15f5acc3401d/exercises/practice/bank-account/.meta/config.json#L34-L37

However, this can create some confusion among the students, as they can run the tests normally and have them working, but have them fail on the online editor. To make this a bit clearer I'd suggest the following:

* Add a clarification on [docs/TESTS.md](https://github.com/exercism/go/blob/main/docs/TESTS.md#tests) that for some exercises the tests might be run with this flag active.
* Add a sentence to the `instructions.append.md` of the exercise saying the particular exercise is run with this flag and provide the command to run the tests with the flag.

Right now the only exercise we have using this flag is `bank-account`.

**Comment by nahuakang** [comment]
@andrerfcsantos Happy to claim this issue :)
