### ISSUE TITLE
Wrong expected value in unit test for Annalyn's Infiltration

### ISSUE THREAD

**Issue by gawelczyk** [exercism/go#2164]
From the Instructions: "Prisoner has to be awake to be rescued ..." so two unit tests are wrong:

`func CanFreePrisoner(knightIsAwake, archerIsAwake, prisonerIsAwake, petDogIsPresent bool) bool {}`

```
=== RUN   TestCanFreePrisoner
=== RUN   TestCanFreePrisoner/All_characters_are_sleeping._Dog_is_present.
    d:\Adam\exercism\go\annalyns-infiltration\annalyns_infiltration_test.go:274: CanFreePrisoner(false,false,false,true) = false; want true
--- FAIL: TestCanFreePrisoner (0.00s)
    --- FAIL: TestCanFreePrisoner/All_characters_are_sleeping._Dog_is_present. (0.00s)
```
and
```
=== RUN   TestCanFreePrisoner
=== RUN   TestCanFreePrisoner/Knight_is_awake._Archer_is_sleeping._Prisoner_is_sleeping._Dog_is_present.
    d:\Adam\exercism\go\annalyns-infiltration\annalyns_infiltration_test.go:274: CanFreePrisoner(true,false,false,true) = false; want true
--- FAIL: TestCanFreePrisoner (0.00s)
    --- FAIL: TestCanFreePrisoner/Knight_is_awake._Archer_is_sleeping._Prisoner_is_sleeping._Dog_is_present. (0.00s)
```

Both of them should expect FALSE unless you change the description.

**Comment by andrerfcsantos** [comment]
The instructions and the tests are correct.

Note that the part that says the prisoner must be awake is also listed as "one of two ways" to succeed. The other way to succeed is:

> If Annalyn has her pet dog with her she can rescue the prisoner if the archer is asleep. The knight is scared of the dog and the archer will not have time to get ready before Annalyn and the prisoner can escape.

This case doesn't depend on the prisoner being awake.

**Comment by gawelczyk** [comment]
The prisoner is not startled by Annalyn's sudden appearance when she has a dog - case 1, the prisoner might be asleep or not,
but when she hasn't got the dog, the prisoner is startled by her appearance so the prisoner has to be awake - case 2.

It works from logical point of view but sounds a bit misleading when read first time :-) Especially when you focus on coding, not analyzing logic in details. I have to be more careful next time.

Thanks for explanation
