### ISSUE TITLE
Add a service like Grammarly to the CI/CD pipeline.

### ISSUE THREAD

**Issue by ahmedsameha1** [exercism/go#2169]
Is it possible to add a service _**like**_ [Grammarly](https://app.grammarly.com/) to the current CI/CD pipeline? This will catch as many typos and grammar/punctuation mistakes as possible.

**Comment by andrerfcsantos** [comment]
Do you know any good service for this?

The problem with using any one service for this is that I don't know any that would be able to deal with the diversity of files we have. I'm a user of Grammarly and I even use it on VSCode when reviewing medium/large PRs where a lot of markdown files are involved. Grammarly is great at giving smart suggestions for regular text, but can easily throw a lot of false positives even in text-heavy files like markdown. When dealing with code files, the false positives are even higher. I don't want CI to list all those cases, where a lot will be false positives - I feel like manual review is still the best approach here.

I've used other spellcheckers in the past, most of them have the same problems and are not as good as Grammarly for regular text.

The perfect spellchecker would be as smart as Grammarly on giving suggestions, but would also understand markdown/code semantics and would look for just the right bits to spellcheck - but I don't know any spellchecker that does this currently.

**Comment by junedev** [comment]
In the JavaScript track, we had a contributor that applied all the suggestions tools made and it removed a lot of the "story like" phrases we use in concept exercises. They used Grammarly and some other tool. Lots of parts of that PR had to be reverted to the original version. That means even if we would somehow only look at markdown and somehow exclude the code parts, it would still give lots of false positives.

Imo, the only thing CI could do here is to create some kind of report that can be manually checked by the author and reviewer but then again, I also don't know any tool that can handle the kind of files we have and produce human readable reports for those.

As a very minimal thing to address the issue, we could encourage contributors in the contribution guidelines to activate spell checkers in their IDE.

In general, I have to say I am not worried too much about typos/punctuation issues etc. It is always a nice thing for new contributors to start with a tiny typo fix to get to know the general process of contributing via GitHub etc. We get lots of PRs around those issues, they are easy to review and over time I think there will be less and less typos left in the content. So while the current process is rather inefficient, it also has its advantages.

**Comment by junedev** [comment]
As mentioned above, the only tangible thing we could do here would to recommend people to use these checking tools by themselves. But I recently used the free version of Grammarly and it is nearly unusable. They push you to the paid version everywhere. Other tools not even have a free version.
In conclusion that means there is nothing we can really do about this issue for the time being so I will close it.
