### ISSUE TITLE
Isbn Verifier: Test case for invalid Isbn should be added 

### ISSUE THREAD

**Issue by TristanAppDev** [exercism/go#2173]
For [Isbn Verifier](https://github.com/exercism/go/tree/main/exercises/practice/isbn-verifier) an additional test case should be added because you can have code which allows this `4-598-21507-A` ISBN and still pass all tests.

**Comment by andrerfcsantos** [comment]
Additions to the test cases of practice exercises must be suggested in the [problem specifications](https://github.com/exercism/problem-specifications) first, so all tracks can benefit from them. IF the changes are approved there, we can sync our exercise to match the tests in problem specs.
