### ISSUE TITLE
"Errors" concept appears to contradict itself on practicality of comparing errors

### ISSUE THREAD

**Issue by scubbo** [exercism/go#2191]
Referencing [this content](https://exercism.org/tracks/go/concepts/errors) ([source](https://github.com/exercism/go/blob/main/concepts/errors/introduction.md)).

Early on, the introduction references [this StackOverflow question](https://stackoverflow.com/a/50333850), which notes that (_heavily_ abridged): "_the `errors.New()` function[...]returns a pointer to a very simple struct value. This is so that if you create 2 error values with the same `string` value, they won't be equal_".

However, later in the introduction, there is the following snippet:

> You can compare error variables with the equality operator ==:
> ```golang
> var ErrResourceNotFound = errors.New("resource not found")
> // ...
> if err == ErrResourceNotFound {
>   // do something about the resource-not-found error
> }
> ```
> How to check for errors of a specific custom error type will be covered in later concepts. 

_Technically_, there's nothing wrong with the block above - it is, literally speaking, an example of comparing error variables. However, if `err` is created with another call to `errors.New` (as would probably be the case if `err` is returned from a call to an external function), then the equality-check above will (correctly, but unexpectedly) evaluate to `false`. The code above would only operate as-expected if the abridged code called some package-internal code like:

```golang
var ErrResourceNotFound = errors.New("resource not found")

func someInternalFunction() (T, error) {
  // Some logic here...
  // But we assume it always fails...
  return nil, ErrResourceNotFound // _Not_ `return nil, errors.New(...)`
}

func main() {
  _, err = someInternalFunction()
  if err == ErrResourceNotFound {
    // ...
  }
```

I'm not sure what the fix is here, since I'm not sure what the intention was of including the error-equality-checking.

* If the intention was to show students how to check for a particular (lower-case-)type of error, then I think the introduction should show how to check for the (upper-case-)Type of an error, rather than doing variable-equality checks. I'd be happy to make this change if someone can confirm that that was the intention.
* If the intention was to show students how to create a package-level Error, to return that error from a function, and to compare a returned Error value to the previously instantiated one, I think it would be helpful to clarify that this will _not_ be able to detect similar-but-not-identical errors returned from other functions (which instantiate their own Errors with `errors.New`)
* An alternative approach (and probably a better one?) would be to drop the discussion of "_logic based on error variables_" entirely until the "_later concepts_"

**Comment by junedev** [comment]
@scubbo I am sorry, I have trouble understanding the issue. If I paste your example into the playground, I cannot reproduce the case where the comparison would evaluate to false: https://go.dev/play/p/NzioqeS8mKi

Of course, if `ErrResourceNotFound` would be exported form another package, you would have to import it to make the comparison, e.g. it would look like `err == repository.ErrResourceNotFound` but that also works just fine.

Could you please provide a working playgroup example for the case you are thinking of? You can do that by entering/pasting the code here https://go.dev/play and then clicking on "Share" will provide you a link you can paste here.

**Comment by scubbo** [comment]
Ah, ok - I seem to have made some false assumptions about idiomatic Go, then. I'm used to instantiating an Exception (to which Go's Errors are similar, but not the same) at the point of throwing them, not pre-instantiating them and then referring to them at return("throw")-time. In such a setup (i.e. where Errors are instantiated when-returned), it wouldn't be possible to export the Error in order to make a comparison. But it sounds from your response that pre-instantiating and exporting Errors is commonplace in Go - so my concerns are ill-founded.

I guess this can be closed as "_not an issue_" (or, as "_requester doesn't yet grok Go's style_" ;) ) - thank you for your time and patience in explaining this!
