### ISSUE TITLE
Code examples: "Output" for non print statements can be confusing - Gopher's Gorgeous Lasagna

### ISSUE THREAD

**Issue by TristanAppDev** [exercism/go#2194]
Change "Output:" to "=>" for Gopher's Gorgeous Lasagna.

For easy tracking: #2156

**Comment by junedev** [comment]
@TristanAppDev Please do not create new issues for each exercise as this creates overhead for maintainers. Feel free to add a list of checkboxes to tick off as a comment in the original issue, if you want to indicate which exercises need to be fixed. All PRs can link the same original issue, that's fine.

**Comment by TristanAppDev** [comment]
Ok @junedev
