### ISSUE TITLE
Go track: tests said passed, analyzer said failed.

### ISSUE THREAD

**Issue by bobahop** [exercism/go#2213]
On iteration 8 of my Raindrops solution

![err_1](https://user-images.githubusercontent.com/32035397/132098244-2f87cf79-b498-4659-aac3-9ee0c63f5a3c.JPG)
![err_2](https://user-images.githubusercontent.com/32035397/132098249-7d9e9d28-16cd-44d7-b806-36ef887db0ac.JPG)

**Comment by iHiD** [comment]
(Moved this to exercism/go as I think it's track-specific)

**Comment by andrerfcsantos** [comment]
Does this still happen? I'm unable to reproduce.

I tried the solution Bob posted and the analyzer seems to have no automated feedback [check iteration 6](https://exercism.org/tracks/go/exercises/raindrops/iterations).

However, running Bob's solution in the analyzer locally gives me this:

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/6928620/170588925-f60dce8d-ff36-41c7-a1de-c968247be87d.png">

**Comment by bobahop** [comment]
Well, I suppose if something is given ten months before being addressed there is a chance for it to have been fixed along the way. 😄  I also can no longer reproduce the analyzer issue. So, since I opened the issue I'll go ahead and close it.
