### ISSUE TITLE
Linked List: Inconsistency between method names in global and track specific instructions

### ISSUE THREAD

**Issue by dirkkul** [exercism/go#2219]
Hi,

I'm currently doing the linked list exercise and noticed that some methods are named differently in the global and track specific instructions. In specific, in the readme part that comes from the global problem specification (instructions.md), the List should have the the methods:
* `push` (*insert value at back*);
* `pop` (*remove value at back*);
* `shift` (*remove value at front*).
* `unshift` (*insert value at front*);

However in the stub file and the track-specific part of the readme (instructions_append.md) they are called:
- PushFront
- PushBack
- PopFront
- PopBack

Moreover, In the description the Node field should have a field "Val", while the tests check for a member "Value" (this was recently changed [here](https://github.com/exercism/go/issues/2090)). 

My proposal would be to:
1) change the Val to Value in instructions_append.md
2) name the List methods consistently with the problem-specification (eg push, pop etc), even though I like the track-specific names more

I'm happy to do an MR in case this is ok.

**Comment by dirkkul** [comment]
Another thing I've noticed:

The description says

> To keep your implementation simple, the tests will not cover error conditions. Specifically: pop or shift will never be called on an empty list.

But the go tests do exactly that (https://github.com/exercism/go/blob/main/exercises/practice/linked-list/cases_test.go, just search for ErrEmptyList) and require the definition of an additional ErrEmptyList. Otherwise they do not even compile. This variable is mentioned nowhere

**Comment by andrerfcsantos** [comment]
@dirkkul Thanks for opening an issue about this, you raise some great points here.

> 1. change the Val to Value in instructions_append.md
> 2. name the List methods consistently with the problem-specification (eg push, pop etc), even though I like the track-specific names more

Feel free to open a PR with this.

> But the go tests do exactly that (https://github.com/exercism/go/blob/main/exercises/practice/linked-list/cases_test.go, just search for ErrEmptyList) and require the definition of an additional ErrEmptyList. Otherwise they do not even compile. This variable is mentioned nowhere

We can adjust the tests to remove the need for that variable indeed in the short term.
In the long-term, we probably want to look at making the tests conform with the [problem specs](https://github.com/exercism/problem-specifications/blob/main/exercises/linked-list/canonical-data.json). But for now, I think it's fine to just adjust the tests so they do not give an error.
