### ISSUE TITLE
Improvement idea for Diamond tests

### ISSUE THREAD

**Issue by rootulp** [exercism/go#2222]
While solving the Diamond exercise, I had a difficult time iteratively solving the exercise because [diamond_test.go]( https://github.com/exercism/go/blob/main/exercises/practice/diamond/diamond_test.go) is all or nothing. In other words, the entire solution is implemented and all tests pass or the solution isn't implemented and all tests fail.

While solving, I found it helpful to iteratively solve against test cases like:

```go
func TestDiamond(t *testing.T) {
	tests := []test{
		{'A', "A\n"},
		{'B', " A \nB B\n A \n"},
		{'C', "  A  \n B B \nC   C\n B B \n  A  \n"},
		{'D', "   A   \n  B B  \n C   C \nD     D\n C   C \n  B B  \n   A   \n"},
	}
	for _, test := range tests {
		got, err := Gen(byte(test.input))

		if err != nil {
			t.Errorf("Gen(byte(%v)) err %v", test.input, err)
		}
		if got != test.want {
			t.Errorf("Gen(byte(%v) got\n%v want\n%v", test.input, got, test.want)
		}
	}
}
```

If maintainers are open to a test like the above being added to the exercise, I think it could help future solvers and I'm happy to create a PR for it.

**Comment by andrerfcsantos** [comment]
Hi!

Thanks for opening an issue about this.

The instructions and test cases come from the [problem-specifications repo](https://github.com/exercism/problem-specifications). The test cases for this exercise are in [canonical-data.json](https://github.com/exercism/problem-specifications/blob/main/exercises/diamond/canonical-data.json).

It seems that Go decided to not use the test cases in the problem specs repo for this exercise and instead implemented property-based testing. However, you raise a good point and I think that value-based tests like the ones in the `canonical.json` file can help arrive at a solution.

So, my suggestion here would be to add the tests in [canonical-data.json](https://github.com/exercism/problem-specifications/blob/main/exercises/diamond/canonical-data.json) to the tests we already have.
