### ISSUE TITLE
pig-latin: Remove call to `Printf` in tests and use sub-tests

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#2230]
While testing solutions locally for the exercises in the track, I noticed that the exercise pig-latin has a direct call to `fmt.Printf`:

https://github.com/exercism/go/blob/d631baf6724946b6682fbcbad06bdeda0a09bf14/exercises/practice/pig-latin/pig_latin_test.go#L13

This makes it so just running `go test` produces output, which is not desirable. I understand this call to print was probably an attempt to explicitly print which tests failed and which ones passed, but the `go` command itself can print the result of individual tests in verbose mode with `go test -v` - the tests themselves shouldn't print if they passed or failed.

While removing this call to print, we can make this exercise use sub-tests, as discussed in https://github.com/exercism/go/issues/2098

The tasks here are:

- Remove the call to `fmt.Printf` on the tests
- Remove `PASS: ` and `FAIL: ` from strings - `go test -v` can provide this kind of output based just on the test (or sub-test) results
- Make exercise use sub-tests (example in https://github.com/exercism/go/issues/2098)

**Comment by Satho-M** [comment]
I can work on this one if nobody else is already.
