### ISSUE TITLE
The answer of task4 of Interest is Interesting is wrong.

### ISSUE THREAD

**Issue by qiankunxienb** [exercism/go#2256]
Here is my code:

```go
func YearsBeforeDesiredBalance(balance, targetBalance float64) int {
	rate := float64(InterestRate(balance)) / 100.0
    rateSqur := targetBalance / balance
    base := 1.0 + rate
    year := math.Log(rateSqur) / math.Log(base)
    fmt.Println(rate, rateSqur, base, year)
    return int(year) + 1
    
}
```

Here is the last test case:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/71627005/174317258-ec6ae421-258c-402f-8436-1582a16c4492.png">

The correct answer is 104, instead of 85:

```
2345.67 * (1 + 0.01621) ^ 104 = 12489.56
```

**Comment by andrerfcsantos** [comment]
The test is correct. The problem with your solution and trying to use a formula, is that the interest rate is not constant, and it grows as your balance grows, so you can't assume your interest rate will always be `0.01621` - it'll change over the years as the balance increases.

**Comment by qiankunxienb** [comment]
Yes, you are right. I get the point.
