### ISSUE TITLE
Remove suggestion of `sync.Map` from Parallel Letter Frequency

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#2257]
In [instructions.append.md](https://github.com/exercism/go/blob/main/exercises/practice/parallel-letter-frequency/.docs/instructions.append.md) for `parallel-letter-frequency`, we have a link for the docs of `sync.Map`.

Some students actually read this and get the idea they should use a `sync.Map`. This is terrible advice for this exercise because:

1. Even the docs discourage the use of this map, and mention that when types for the map are known, a regular and properly typed map + mutex is better:

> The Map type is specialized. Most code should use a plain Go map instead, with separate locking or coordination, for better type safety and to make it easier to maintain other invariants along with the map content.
Source: [sync.Map](https://pkg.go.dev/sync#Map)

2. Using a map and protecting it with locks (either by using sync.Map or a regular map + mutexes) is not the best way to solve the exercise. It's best to avoid lock contention altogether by letting each goroutine have its own map and communicate these maps through channels.

My suggestions here are:

- Remove the link to the `sync.Map`
- Add more links about waitgroups, channels and goroutines. Some students find this article very useful and directly applicable to the exercise: [Synchronizing Go Routines with Channels and WaitGroups
](https://dev.to/sophiedebenedetto/synchronizing-go-routines-with-channels-and-waitgroups-3ke2), maybe we can include it too.

**Comment by Jasstkn** [comment]
That's true. Firstly, I was trying to use sync.Map but it wasn't obvious how to do it and I failed.
For me also several articles were helpful:
- https://golangbot.com/buffered-channels-worker-pools/
- https://www.digitalocean.com/community/tutorials/how-to-run-multiple-functions-concurrently-in-go
- https://www.golang-book.com/books/intro/10

**Comment by andrerfcsantos** [comment]
Sure! Thanks for taking interest in the issue. Yeah, I think those links are good, feel free to include them.
