### ISSUE TITLE
Problem in the "Gopher's Gorgeous Lasagna" question

### ISSUE THREAD

**Issue by AshiishKarhade** [exercism/go#2262]
I found a problem with the 2/6 test cases while attempting the question "[Gopher's Gorgeous Lasagna](https://exercism.org/tracks/go/exercises/lasagna/)". 

I believe the given test cases provided in the system are WRONG.

**The failing test cases are - 5 and 6**

Problem - 

> We have to find the elapsed time of Lasagna. It takes two parameters - numberOfLayers and timeInOven

`func elapsedTime(numberOfLayers, timeInOven){
    return (numberOfLayers * 2) + (40 - timeInOven)
}`

**TestCase 5 -  layers:   1, time:     30**
- this should return, 2 + 10 = 12
- but the test in the system **expects 32**

**TestCase 6 -  layers:   4, time:     8**
- this should return, 8 + 32 = 40
- but the test in the system **expects 16**

**Comment by Jasstkn** [comment]
@AshiishKarhade hey. I guess you don't need to subtract expected  amount of time and actual one. Because according to the exercise:
> the second parameter is the number of minutes the lasagna has been in the oven
Basically, you need to sum up total time for cooking all layers and actual time in the oven.

**Comment by AshiishKarhade** [comment]
@Jasstkn Thank you for checking out. 
But there's a function
`
func RemainingOvenTime(actualMinutesInOven int) int {
    // calculates remaining oven time left
}
`
It makes no sense for this function to accept the parameter _actualMinutesInOven_ and return it as it is

Also, in the instructions - **TASK 2**
You will find more clarification here. 
![Screenshot 2022-06-21 at 9 22 03 AM](https://user-images.githubusercontent.com/27147691/174712723-b020df46-92a8-444a-ab02-1965c8cea7e5.png)
 
If you see the commented sample function , it takes _30_ as parameter value and returns _10_

**Comment by Jasstkn** [comment]
> @Jasstkn Thank you for checking out. But there's a function `func RemainingOvenTime(actualMinutesInOven int) int { // calculates remaining oven time left }` It makes no sense for this function to accept the parameter _actualMinutesInOven_ and return it as it is
> 
> Also, in the instructions - **TASK 2** You will find more clarification here. ![Screenshot 2022-06-21 at 9 22 03 AM](https://user-images.githubusercontent.com/27147691/174712723-b020df46-92a8-444a-ab02-1965c8cea7e5.png)
> 
> If you see the commented sample function , it takes _30_ as parameter value and returns _10_

But it's not cooking time. It's time that you have spent working on the lasagna:
> The function should return how many minutes in total you've worked on cooking the lasagna, which is the sum of the preparation time in minutes, and the time in minutes the lasagna has spent in the oven at the moment. 

Function `RemainingOvenTime` refers to the time that you need to keep cooking lasagna in the oven. It's not connected with the `ElapsedTime` function.
