### ISSUE TITLE
Bank Account: fix links in instructions

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#2271]
In the [Bank Account](https://exercism.org/tracks/go/exercises/bank-account) exercise, the [instructions.append.md](https://github.com/exercism/go/blob/main/exercises/practice/bank-account/.docs/instructions.append.md) has some links that could use some formatting:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/6928620/175783330-d1fedb66-36cc-4372-beed-a8977f690ce0.png">

## Tasks

* Put these links in a list. The text for the links should be descriptive of the link, by including the source of the link and its title. For instance, a good text for `https://tour.golang.org/concurrency/9` would be `Tour Of Go: sync.Mutex`. For list and link formatting in markdown, check [Exercism's Markdown Style Guide](https://exercism.org/docs/building/markdown/style-guide).

## Contributing to this issue

* If you'd like to contribute to this issue, just make a comment below saying that you'd like to work on this. After that, feel free to open a PR with the fix and link it to this issue. See more information on how to link PRs to issues on [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).
* If you have further questions on how to solve this issue or get stuck in the middle of solving it, post your concerns/questions below and we'll help you!

**Comment by Jasstkn** [comment]
@andrerfcsantos just noticed. would like to contribute this if you don't mind. :)

**Comment by andrerfcsantos** [comment]
@Jasstkn Go for it :)
