### ISSUE TITLE
Formatting of instructions of meteorology

### ISSUE THREAD

**Issue by eklatzer** [exercism/go#2289]
Hey, when doing the exercise `meteorology` I have seen, that the format of the instructions could maybe be improved:
![image](https://user-images.githubusercontent.com/47006675/177961739-e033ab17-eae5-4df6-b103-b84d4da3cbe9.png)

We should maybe move the format to a/the codeblock

**Comment by andrerfcsantos** [comment]
A full codeblock instead of the inlined form could work better here indeed and it is worth trying.

Thanks for the suggestion!
