### ISSUE TITLE
Card Tricks: clarify GetItem out-of-bounds handling

### ISSUE THREAD

**Issue by bobahop** [exercism/go#2323]
Card Tricks used to return the indexed value and true/false for it the index was valid. If the index was invalid, then `0, false` could be returned.

That was changed to returning `-1` for an invalid index. But there is automated advice elsewhere that:

> By convention, when returning an `error` value, other values are not used, and it's considered idiomatic to return the [zero value](https://golang.org/ref/spec#The_zero_value) in this situation. The `error` value makes using an invalid "out of band" value to signal an error redundant in Go.

It seems that returning `-1` for an out-of-band value might be leading the student down the wrong path.

So, as per discussion with @andrerfcsantos on Slack, I'm suggesting it get changed back to returning the index and a bool.

Since the functions concept teaches about multiple return values, perhaps it could be made a prerequisite of Card Tricks? Or maybe the basics concept where functions are introduced could also show a function with multiple return values?

**Comment by andrerfcsantos** [comment]
>  we could add an admonition block that explains that the proper way of handling the error case will be covered later on

I agree with doing this if keeping the exercise as is.

**Comment by bobahop** [comment]
I'm with both of you on keeping as is with an admonition.

**Comment by junedev** [comment]
Great, I'll use this issue to track that the admonition gets added. I changed the title for that.

**Comment by bobahop** [comment]
I love the word "admonition" btw. It's so fun to pronounce.
