### ISSUE TITLE
Kindergarten garden: go mod module makes no sense

### ISSUE THREAD

**Issue by Ilingu** [exercism/go#2351]
Hi, while doing the `kindergarten-garden` exercise I notice a **very minor** problem in the `go.mod` file. 

The module is set to _"are"_ while the package is named _"kindergarten"_, so I think there is some type of **typo** here. 

I know that it's an insignificant issue, but I don't think that it was set to _"are"_ on purpose, besides all others exercises have a coherent naming which respect the **Go Package Notation**, thus if one of the main contributors agrees with me, I'd be pleased to make the change and send a PR.

**PS:** kindergarten-garden exercise can be found here: `/exercises/practice/kindergarten-garden`

**Comment by andrerfcsantos** [comment]
Well spotted!

So the task here is to change the module in [go.mod](https://github.com/exercism/go/blob/main/exercises/practice/kindergarten-garden/go.mod). I suggest changing it to have the same name as the package: `kindergarten`.

Checking if the name in the go.mod file matches the package is something that we can maybe add as a check in [gomod-syns](https://github.com/exercism/go/tree/main/gomod-sync), but that will be a separate issue.
