### ISSUE TITLE
census: missing tests for the `Count` function

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#2386]
The last task asks to write a function `Count` that counts all the residents with valid information. However, the invalid residents we have also happen to have a missing address. This means that a solution that only tests for the presence of the address passes the tests:

```go
func Count(residents []*Resident) int {
	result := 0
	for _, resident := range residents {
		if len(resident.Address) != 0 {
			result += 1
		}
	}
	return result
}
```

## Tasks

- [ ] Add more tests to the `Count` function in [census_test.go](https://github.com/exercism/go/blob/main/exercises/concept/census/census_test.go) that includes lists of residents with invalid information or other than just the address. The tests must ensure that testing for just 1 or 2 fields is not enough to consider a resident valid/invalid.

## Working on this issue

If you would like to work on this issue, comment below that you are interested in working on this.

**Comment by Jasstkn** [comment]
@andrerfcsantos hey. can I work on it?

**Comment by andrerfcsantos** [comment]
@Jasstkn Go ahead!
