### ISSUE TITLE
Need For Speed  |  Task 3  |  Drive the Car

### ISSUE THREAD

**Issue by saurami** [exercism/go#2394]
Instructions for "Task 3 - Drive the Car" are not clear:

Implement the Drive function that updates the number of meters driven based on the car's speed, and reduces the battery according to the battery drainage. If there is not enough battery to drive one more time the car will not move:

```
speed := 5
batteryDrain := 2
car := NewCar(speed, batteryDrain)
car = Drive(car)
// => Car{speed: 5, batteryDrain: 2, battery: 98, distance: 5}
```

Whats the relation between distance, speed and battery drain ?
OR
Whats the formula to calculate the distance if speed and battery drain are given ?

**Comment by eklatzer** [comment]
Hey, in the first lines of the instructions you can find the following line, which describes this: `Each time you drive the car using the remote control, it covers the car's speed in meters and decreases the remaining battery percentage by its battery drain.`

**Comment by saurami** [comment]
That isn't enough information. There's no information about calculating distance.

**Comment by eklatzer** [comment]
`Each time you drive the car using the remote control, it covers the car's speed in meters`--> each time you `Drive`, the distance increases by the value of `speed`

**Comment by saurami** [comment]
Just finished with the solution.

`Each time you drive the car using the remote control, it covers the car's speed in meters`--> each time you Drive, the distance increases by the value of `speed` if the battery is 100%

**Comment by eklatzer** [comment]
> each time you Drive, the distance increases by the value of speed if the battery is 100%
This is not correct: it is done if the battery>=battery drain, not if the battery is 100%

**Comment by saurami** [comment]
Looks like there's a bug in the test cases for the drive function.

The below code for `Drive` function passes all 5 `TestDrive/` test functions:

```
func Drive(car Car) Car {
	if car.battery == 100 {
		return Car{
			battery: 100 - car.batteryDrain,
			batteryDrain: car.batteryDrain,
			speed: car.speed,
			distance: car.distance + car.speed,
		}
	} else {
		return Car{
			battery:      car.battery,
			batteryDrain: car.batteryDrain,
			speed:        car.speed,
			distance:     car.distance,
		}
	}
}
```

**Comment by eklatzer** [comment]
Hey, thanks for the info, I created a PR to cover a case that also allows to drive, but with less battery than 100%. The case directly covers `battery=batteryDrain`.
