### ISSUE TITLE
Improve test for Animal Magic / GenerateWandEnergy

### ISSUE THREAD

**Issue by funwithbots** [exercism/go#2417]
The current test validates that different values are generated but it doesn't detect typecasting `rand.Intn` to float64. This passes and I don't believe meets the intent of the challenge.

`
func GenerateWandEnergy() float64 {
   return float64(rand.Intn(12))
}
`

**Comment by junedev** [comment]
@norbs57 In case you are still around, would you like to take a look at this as you are the author of the exercise?

**Comment by norbs57** [comment]
We could add a test that divides the range [0..12] into a number of smaller intervals, say 20 intervals each of size 0.6, e.g. [0..0.6), [0.6..1.2), [1.2..1.8), etc. The test program would count the frequency of generated numbers in each interval, and it would flag up student submissions where the frequency distribution was statistically highly improbable.  

In order to detect more sophisticated "non-random" sequences generated by student programs, we would need to code more advanced statistical randomness tests, see the literature. I am not sure that would be worth it.

**Comment by junedev** [comment]
I like the idea with the intervals. It doesn't have to be more sophisticated just as you said. 
The check for "highly improbable" can also just be something simple like "2 buckets with 0 values inside after some large number of tries".

@norbs57 @funwithbots Anyone up for creating the PR with the new test?

**Comment by funwithbots** [comment]
math/rand pretty much only gives back some variation of `int` or `float` values. I think detecting use of `int` for the test is probably sufficient. If someone goes nuts and does something elaborate with floats or intentionally games the test, I agree it's not worth trying to gauge true randomness. There are so many ways to break this short of a statistical analysis. 

`float64` gives enough digits of precision that after even 10 iterations, if all the values are +/- 1e+6 of an integer, it should fail. Flipping a bool as soon as a non-int based value is returned would do this.

I'm happy to open the PR and add a test if that makes sense. Otherwise, I can take the bucket approach.

**Comment by norbs57** [comment]
The bucket-approach would also deal with submissions that leave out part of the expected range, say they never generate numbers less than 1 or larger than 11.  Having said that, you could also write some separate tests to deal with those.  

The approach of checking frequencies could also be used to improve testing of functions `RollADie`  and `ShuffleAnimals` functions in this exercise.

**Comment by norbs57** [comment]
I am taking a break from Exercism (and Slack) during the Summer. Having said that, I would be happy to check the probability of "false positives" in the "Animal Magic" additional tests. Please drop me an email if you would like me to look at that.

**Comment by funwithbots** [comment]
Sounds good! I'll open a PR for this issue. Once it's good, I'll plan to tackle the other two exercises.

**Comment by funwithbots** [comment]
PR is open and all sanity checks passed. Review anyone?

https://github.com/exercism/go/pull/2420

**Comment by andrerfcsantos** [comment]
Can this be closed since #2420 is merged?
