### ISSUE TITLE
Add comment at the top of generated files with test cases

### ISSUE THREAD

**Issue by junedev** [exercism/go#2421]
Every now and then it happens that contributors directly edit the cases file which is produced by the generator. As we might move towards autogenerating issues about updating exercises that contributors can pick up, this problem might happen more often.

To avoid this, it would be good if the main generator script would add a comment section at the top explaining that the file is auto-generated and should not be edited directly and maybe link to the docs of how to run the generator.

**Comment by eklatzer** [comment]
Hey, I will adjust the generator
