### ISSUE TITLE
Tests too lax on Lasagna Master

### ISSUE THREAD

**Issue by tehsphinx** [exercism/go#2424]
On task 3 of `Lasagna Master`, the `AddSecretIngredient` this is what should be done:
```
Write a function AddSecretIngredient that accepts two arrays of ingredients of type []string as parameters.
The first parameter is the list your friend sent you, the second is the ingredient list for your own recipe.
The function should generate a new slice and add the last item from your friends list to the end of your list.
Neither argument should be modified.
```

But solutions that just overwrite the last ingredient (instead of adding an additional one) like the following are also considered correct:
```
myRecipe[len(myRecipe)-1] = fRecipe[len(fRecipe)-1]
```

That shouldn't be the case. Also this solution would change the input which is not allowed according to the description.

**Comment by tehsphinx** [comment]
It seems I was looking at an older exercise version and now I'm wondering why the change to replace the last item instead of adding an additional one.

**Comment by junedev** [comment]
@tehsphinx Please see https://github.com/exercism/go/issues/2036 for the reasoning.

Let me know whether there is still something to be improved here or whether the issue can be closed.
