### ISSUE TITLE
Clear distinction between private and public function needed 

### ISSUE THREAD

**Issue by legendarykamal** [exercism/go#2478]
In this file https://github.com/exercism/go/tree/main/concepts/basics

**Comment by junedev** [comment]
@legendarykamal Thanks for leaving a note. Can you say more why you think this is necessary? The syllabus is designed to gradually walk through the different concepts and the goal for basics is only to give a very rough overview so students are able to solve the following learning exercises.

Public/private is then introduced later in the "packages" concept: https://exercism.org/tracks/go/concepts/packages
