### ISSUE TITLE
Saddle Points - Directions / Comments Incorrect 

### ISSUE THREAD

**Issue by W8CYE** [exercism/go#2482]
saddle_points_test.go contains the following incorrect comment. 

```go
// Short cut!  Have you already done the matrix exercise?
// If it seems helpful, copy your code from the matrix exercise
// to this directory so you have access to it.  You can leave it as matrix.go
// and start a new file saddle_points.go with additional code that completes
// this exercise.  Submit only saddle_points.go for this exercise.
```

The key point `Submit only saddle_points.go for this exercise.` will result in online tests failing while local tests succeed. 

I propose changing this to `Submit both saddle_points.go and matrix.go for this exercise.` which allows the online tests to pass. 

Alternatively, the comment could be removed entirely suggesting that all solution code must be created and uploaded. 

I will submit a PR to resolve once the solution is agreed.

**Comment by junedev** [comment]
Good catch, I totally agree. If you agree that matrix is helpful for this exercise, I would suggest leaving the comment as such intact and just fixing it as you mentioned in the first suggestion.
