### ISSUE TITLE
Investigate why the test for animal magic sometimes fails on windows

### ISSUE THREAD

**Issue by junedev** [exercism/go#2484]
The test for the "SeedWithTime" function in animal magic exercise sometimes fails on windows.
See https://github.com/exercism/go/runs/8195983378?check_suite_focus=true for an example.

We already tried to increase the timeout but that didn't solve the problem.

**Comment by Ravalnath** [comment]
@junedev Quick question, why does the time.duration in sleep have to be a random number. Can't we just keep it as time.Duration(10) instead?
I think this has some coincidence when the random number generated is 0. I am able to reproduce this here:
[Go Playground](https://go.dev/play/p/GZHeBWe4vms)

**Comment by junedev** [comment]
For reference, the question was already answered in the PR linked above.

**Comment by junedev** [comment]
@Ravalnath With your hint, I think I got it (might be what you meant above). We select a number between 0 and 10 for the waiting time and the seed also applies for that selection. When the waiting time was 0, the seed might be the same as before, leading to another waiting time of 0 and so on. The test fails. I read that the waiting time is particularly important on Windows as the seeding is slow there, that might be the reason we only see it for Windows. And since it only happens for 0 and not the other numbers (1,2,3, ...) explains why it only happens sometimes (1 out of 10).
So the fix would be to add 1 to the waiting time so it is never 0. Would you like to do a new PR?

**Comment by junedev** [comment]
I will close the issue for now and re-open it in case the problem re-appears.
