### ISSUE TITLE
Avoid compiler optimization in benchmarks

### ISSUE THREAD

**Issue by junedev** [exercism/go#2489]
As layed out by Dave Cheney here https://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go in the section at the bottom, a function call in a benchmark should always assign the result to some global variable to avoid that the compiler simply does not execute the function at all. Bill Kennedy also teaches this in his Go trainings if I remember correctly.

Currently, we don't do this at all. I don't know how many of our benchmarks are wrong because of that but I think it would be good to demonstrate this best practice in our code.

**Comment by andrerfcsantos** [comment]
I also thought about this before and did a test or two with our benchmarks and the reality is that I haven't really seen any differences in the benchmark results with and without the optimization "prevention".

This is one of the best practices in Go that I wonder if it's really needed. If the compiler is smart enough to realize the return value is not being used, wouldn't it also be able to detect that a global variable is only being assigned to and never really used in a meaningful way?

We can still do this as a way to showcase this technique to students as you said, but I don't think our benchmarks are wrong currently. I usually run benchmarks on students' solutions and never saw anything weird - optimizing the functions gives better results in benchmarks, which is a sign the exercise functions are not being ignored.

It could also be worth to investigate a way to check easily (with a command or something) if a function is really being ignored by the benchmarks or not, so we could potentially see which exercises need this and for which versions of Go (to check against potential changes in the compiler in different versions of Go).
