### ISSUE TITLE
Beer song: deprecate exercise and implement Bottle Song

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#2505]
As per https://github.com/exercism/problem-specifications/pull/2097, we should deprecate the `beer-song` exercise, and implement its replacement, [bottle-song](https://github.com/exercism/problem-specifications/tree/main/exercises/bottle-song).

## Contributing to this issue

Anyone is welcome to contribute to this issue. If you are interested in working on this, just post a comment below saying you want to work on this. Keep in mind that this task requires some exercism knowledge and might not be a good first issue if you are new to contributing.

Here are some docs related to this task:

- [Exercism Docs: Deprecating an exercise](https://exercism.org/docs/building/tracks/deprecated-exercises)
- [Exercism Docs: Practice Exercises](https://exercism.org/docs/building/tracks/practice-exercises)

**Comment by junedev** [comment]
There was a bug in the problem spec version, we should wait until that is fixed before we tackle this: https://github.com/exercism/problem-specifications/pull/2102

**Comment by andrerfcsantos** [comment]
Seems the issue was fixed and we can start working on this

**Comment by PakkuDon** [comment]
Hi there! Can I work on this one?

**Comment by andrerfcsantos** [comment]
@PakkuDon Sure, go ahead! Thanks for the interest and don't hesitate if you have any questions.
