### ISSUE TITLE
say: implement new tests

### ISSUE THREAD

**Issue by andrerfcsantos** [exercism/go#2508]
New tests were introduced recently in problem-specifications repo for the say exercise: https://github.com/exercism/problem-specifications/pull/2087

We should bring these tests to the Go track.

This exercise has a test generator, so we should use it and configlet to generate the new test cases.

## Contributing to this issue

Anyone is welcome to contribute to this issue. If you are interested in working on this, just post a comment below saying you want to work on this.

This issue requires you to write the test generator and configlet against this exercise.

Here are some links to help you on this task:

- [Go track README: Synchronizing tests and instructions](https://github.com/exercism/go#synchronizing-tests-and-instructions)
- [Github: exercism/configlet](https://github.com/exercism/configlet)
- [Exercism Docs: configlet](https://exercism.org/docs/building/configlet)

**Comment by PiotrLewandowski323** [comment]
Hi, can I work on this one?
