### ISSUE TITLE
Hamming exercise should depend on Error concept.

### ISSUE THREAD

**Issue by ar-qun** [exercism/go#2517]
It is actually possible to start https://exercism.org/tracks/go/exercises/hamming without finishing https://exercism.org/tracks/go/concepts/errors

**Comment by junedev** [comment]
We do not have those dependencies/ unlocking mechanism set up for the Go track yet. It is a lot of work that we didn't get around to yet. The issue for this is here: https://github.com/exercism/go/issues/1396
