### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by mintyknight** [exercism/go#2528]
There is a dead link in the README pointing to https://github.com/exercism/docs/blob/master/language-tracks/configuration/exercises.md
<img width="929" alt="image" src="https://user-images.githubusercontent.com/3869257/198892221-01c751ca-f057-47d1-b7af-41bd9c6d4222.png">

**Comment by andrerfcsantos** [comment]
Well spotted. It seems the 3 links in the image are invalid. We might want to just keep a link to [Exercism Docs: config.json](https://exercism.org/docs/building/tracks/config-json),

Feel free to open a PR fixing this.
