### ISSUE TITLE
Fails

### ISSUE THREAD

**Issue by bitfield** [exercism/go#2602]
package lasagna

import "fmt"

// TODO: define the 'PreparationTime()' function
func PreparationTime(layers []string, avPrepTime int) int {
	if avPrepTime == 0 {
		return 4
	}
	return len(layers) * avPrepTime
}

// TODO: define the 'Quantities()' function
func Quantities(layers []string) (noodles int, sauce float64) {
	noodleWeight := 50
	sauceAmount := 0.2
	for i := 0; i < len(layers); i++ {
		if layers[i] == "noodles" {
			noodles += noodleWeight
		}
		if layers[i] == "sauce" {
			sauce += sauceAmount
		}
	}
	return noodles, sauce
}

// TODO: define the 'AddSecretIngredient()' function
func AddSecretIngredient(friendsList, myList []string) {
	myList[len(myList)-1] = friendsList[len(friendsList)-1]
}

// TODO: define the 'ScaleRecipe()' function
func ScaleRecipe(quantities []float64, portions int) []float64 {
	scaledAmounts := make([]float64, len(quantities))
	fmt.Printf("portions %v", portions/2)
	for i := 0; i < len(quantities); i++ {
		scaledAmounts[i] = quantities[i] * float64(portions) / 2
	}
	fmt.Printf("portionList %v", scaledAmounts)

	return scaledAmounts
}

**Comment by junedev** [comment]
Looks like it is related to this known issue: https://github.com/exercism/go-test-runner/issues/6
