### ISSUE TITLE
Minor correction to instruction text for animal-magic instructions.md

### ISSUE THREAD

**Issue by Kristianwhittick** [exercism/go#2790]
The following text instruction does not match the comment after the function, as the text says between and the comment says the value can be equal to zero. Please change the text to "**... number equal or greater than 0.0 and less than 12.0**".

Implement a GenerateWandEnergy function. The wand energy should be a random floating point number **between 0.0 and 12.0.**

f := GenerateWandEnergy()  // f will be assigned a random float64, **0.0 <= f < 12.0**

**Comment by andrerfcsantos** [comment]
This is being discussed in the forum: https://forum.exercism.org/t/minor-correction-to-instruction-text-for-animal-magic-instructions-md/10963
