### ISSUE TITLE
TDD and the Golang track

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/go#2810]
Hey folks,

A friendly question here more than an issue.  As someone who used Exercism a lot in the past, I've found the Golang track a bit tricky to get traction on, mostly because it seems pretty difficult to build the data structures and the APIs incrementally, testing as you build.  Maybe that's just me, but the primary blocker seems to be that you often need to write fairly complete code before you can get meaningful feedback from the tests.

It seems like there's been a conscious decision on the part of the maintainers to prefer generated tests, and I see a lot of tests that require fairly complete APIs.  This is fine if you want to build a complete-ish solution, test it, then iterate on your solution, but it makes it difficult to build up your models and APIs incrementally, enabling relevant tests as you go (more TDD in approach.)

Any history on why that decision was taken?  Is this now the standard practice on Exercism more generally, or is this a cultural artifact of the Go track?

Thanks, appreciate your time.

**Comment by andrerfcsantos** [comment]
This is being discussed in the forum: https://forum.exercism.org/t/tdd-and-the-golang-track/11535
