### ISSUE TITLE
Clarify problem statement for error-handling

### ISSUE THREAD

**Issue by tleen** [exercism/go#703]
Based on [user feedback](http://exercism.io/submissions/dcbbef5ad09e447fb261ba8a13bc211b) and my own experience, the problem definition for error-handling can use some clarification. This is actually a fairly tricky topic at this stage if you are new to Go and I think in this case a little more hand-holding will be helpful.

I'll handle this one, but am open to feedback first. Should it be explained more?

**Comment by robphoenix** [comment]
I've just attempted this exercise and while it's fundamentally not that complicated, the explanation is utterly confusing and doesn't help clarify the problem and expected solution in any way. I think #707 goes a long way to rectify this, :+1: @tleen
I've made some notes as I was doing the exercise, knowing you recently opened this issue. I think I have a couple of things to add, and I'd like to move the commentary into the README. I'll try and get it done over the weekend, but it might not be til Tuesday.

**Comment by tleen** [comment]
:+1: I've been trying to go through the track as a newbie (which I am) and seeing where suddenly things get weird/hard. It is a valuable way of experiencing things. This exercise is a jump. In nextercism this may be rectified, but for now I think shepherding is a good approach to keep people from just giving up completely.

Thus far when I look at solutions I look for:

- can I do this? - can I figure out the problem quickly from what is available via docs
- common approaches - is it obvious how to handle this and a good number of solutions don't go that way
- blatant copies - copying the example.go file (perhaps with  a simple str replace) to move on
- give ups - pure submissions with no attempt to solve the problem

This problem hit a lot of those buttons and I think moving explanations to the README will be that much more helpful. Now that we have a new way to modify local READMEs we should shift the test commentary to those. #728 should eventually move to README too.
