### ISSUE TITLE
clock 1.0.1 generated cases_test.go fails build

### ISSUE THREAD

**Issue by leenipper** [exercism/go#705]
Committed cases_test.go is based on 1.0.0 so the current code is ok.

Using latest x-common clock/canonical-data.json 1.0.1, the generated code fails to build. It breaks b/c two addTests generate due to two different groups having the "add" property.

> ./cases_test.go:61: addTests redeclared in this block

The subtract cases are in a different group but still have "add" property.

From #677 ...
> Clock updated to 1.0.1 and I have code that works for it too, but I want to compare clock 1.0.0 code vs clock 1.0.0 code, so I reverted the 1.0.1 changes (they can be applied later)

@petertseng Perhaps those 1.0.1 changes combined the matching properties differently? I didn't want to dig further if the reverted code handled it already and might be helpful.

But taking a different slant, it might be cleaner if a "subtract" property were used in clock/canonical-data.json, since combining multiple groups into one seems a bit awkward.  And is this case something which classifyByProperty should detect ?

**Comment by petertseng** [comment]
I guess the two choices we have are to either have a separate group for them (like #706), or just put all add cases in the same group somehow. It is a bit troublesome.
