### ISSUE TITLE
The tests for perfect numbers are too vague

### ISSUE THREAD

**Issue by Skarlso** [exercism/go#712]
This code here right now makes all of the tests pass for perfect numbers.

```go
package perfect

const testVersion = 1

var ErrOnlyPositive error

type Classification struct {
}

var ClassificationDeficient Classification
var ClassificationAbundant Classification
var ClassificationPerfect Classification

func Classify(n uint64) (Classification, error) {
	return ClassificationPerfect, ErrOnlyPositive
}
```

Output:

```bash
❯ go test
PASS
ok  	_/Users/nyehehe/exercism/go/perfect-numbers	0.007s
```

Notice how there is no logic in there what so ever. ;)

The types are a nice addition, but they make the test too fragile. It needs to be made explicit so code like this doesn't make it pass.

**Comment by tleen** [comment]
Thanks! We will look into it. If you would like to submit a patch contributions are always welcome. :)

**Comment by petertseng** [comment]
suggest solve in same way as https://github.com/exercism/go/issues/207 please

**Comment by Skarlso** [comment]
Hey @tleen and @petertseng. Sure. :) I'd love too. :)

**Comment by Skarlso** [comment]
Interestingly enough that will make it so solutions like this one won't work any longer: http://exercism.io/submissions/26ed419e9b8643529d038f2af927f072

But I guess, that's almost like a `meh`, since it gave a false positive anyways. :)

**Comment by Skarlso** [comment]
PR sent. I'm off for the night. :) Catch you tomorrow. 👍
