### ISSUE TITLE
Consider me unavailable for this track until further notice

### ISSUE THREAD

**Issue by petertseng** [exercism/go#719]
Hi.

Recently there are a lot of changes requiring attention by the maintainers of every track:

* Docs moves
* Tree structure for tracks
* README generation

It's too much for me to handle this for all of the tracks that I'm a maintainer of (that's why we ideally have multiple maintainers per track).
So I'd advise that the Go track consider me unavailable until further notice, since my *hope* is that there are enough other maintainers that things can proceed without me (well, I am looking at the PR backlog and I do have fears that this hope is not panning out, but I still have to advise the same).
I'm glad to stick around in case of emergency or something, and feel free to ask me questions about https://github.com/exercism/go/pull/677 if you need, but otherwise it would swell if things are able to proceed without me.

**Comment by ferhatelmas** [comment]
@robphoenix @tleen @leenipper Sorry guys, for unavailability in the last months, I will start contributing again from this weekend. Thanks for your great work.

**Comment by robphoenix** [comment]
Hey @ferhatelmas! No worries, no need to apologise, we all have lives :smile:

**Comment by petertseng** [comment]
A ~1 month update (not that I was or am planning to give these on a regular basis): There is still too much going on for Nextercism. I continue to be unavailable for this track.
