### ISSUE TITLE
Exercism Go Maintainers Team

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#721]
I've not used the teams feature before, so this is a bit of an experiment, but I've just started a new team, `exercism-go-maintainers` and invited the current maintainers, @tleen , @petertseng, @leenipper, @ferhatelmas  & @kytrinyx 
I've found myself on more than one occasion needing/wanting to look at different exercise solutions I haven't completed yet for a PR/issue on this repo and I thought that having an Exercism maintainers team may help to pool resources in tackling any queries about exercises and their solutions. This may be a dead end, or not work as I expect, or may just be a little bit of fun, so do please ignore this if it's just extra fuss in your life :smile: 

I'll close this later today.

**Comment by tleen** [comment]
@robphoenix can you re-send my invite? I didn't see it in my inbox.

**Comment by kytrinyx** [comment]
@tleen I think this is a team on Exercism (so no email). It should be here: http://exercism.io/notifications

@robphoenix this sounds like a good experiment :)

**Comment by tleen** [comment]
Got it. I'm in thanks!

**Comment by robphoenix** [comment]
This is already useful & interesting. I think it will be really helpful when we're discussing an exercise that not all maintainers have had experience with. Thanks all.
My only question now is if there's a programming language @petertseng doesn't know??? :open_mouth: :wink:

**Comment by iHiD** [comment]
@robphoenix - If you'll excuse me hijacking this post, may I ask a few questions about your intentions with this:

Firstly, do you want to specifically see *maintainers* solutions to an exercise, or everyone's solutions?

**Comment by robphoenix** [comment]
No worries @iHiD Initially I wanted to see anyone's solutions. This stems from discussions about adding difficulty ratings & topics to `config.json` for exercises I haven't completed yet and wanting more context than the README & example. 

Though having done it, it's quite nice to have that connection with the other maintainers, and may lead to a better understanding of where we are each coming from in terms of our general programming & specific language experience, and maybe further discussions around different exercises within Exercism itself.

**Comment by tleen** [comment]
Came about rather organically via the discussion in #715 about setting the difficulty on the luhn exercise.

**Comment by iHiD** [comment]
Thanks :) OK, great - that's helpful. Brainstorming a bit...

So nextercism will allow you to:
- Browse/search published solutions to an exercise.
- Browse/search a person's published solutions.

Publishing a solution is an optional (and encouraged) step at the end of the iterating process.

So if the maintainers published their solutions you could browse their solutions, or browse everyone's solutions to the exercises in question. Would this fulfil your need or do you need more?

Would some sort of "following"/stalking mechanism help, where you can see keep track of what others have done (a sort of timeline view?). Or maybe some sort of group functionality.

I'm keep to keep things as simple and learning-focussed as possible, but I don't want to remove functionality that people currently rely on.

**Comment by robphoenix** [comment]
Will I need to complete the exercise to browse solutions to it?

As a maintainer being able to browse solutions to an exercise I haven't completed is very helpful in discussing Issues/PR's about that exercise, whether those solutions are by other maintainers or not. Really I didn't need to start the team, @tleen was able to share his solution with me, which was enough for the discussion.

As a user, I haven't ever found myself needing/wanting a timeline view, though there have been times where I have had more than one fruitful interaction with a user and gone on to browse their other solutions, and I have found myself keeping an eye out for particular names when browsing the *other people's solutions* lists, whether I would want to go on and *follow* other users I don't know, inevitably, if I could, I would.

I haven't actually done an Exercism exercise in ~3 months but seeing the activity of others in the team has inspired me to want to get back into it, maybe just competitive spirit.

**Comment by kytrinyx** [comment]
@robphoenix I think it would make sense to make it so all maintainers can see everything... if they want to (opt in). I can give you that on the Go track right now, if you like.

**Comment by robphoenix** [comment]
@kytrinyx that'd be useful, thanks!

**Comment by kytrinyx** [comment]
@robphoenix done. @tleen, @leenipper, @ferhatelmas let me know if you want access to all the solutions as well.
