### ISSUE TITLE
Update track metadata as outlined in #717

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#731]
From #717:

If you haven't already, now would be a good time to do the following:

- [ ] add a rough estimate of difficulty to each exercise (scale: 1-10)
- [ ] add topics to each exercise
- [ ] choose *at most 20 exercises* to be core exercises (set `core: true`, and delete the `unlocked_by` key)
- [ ] for each exercise that is not core, decide which exercise is the prerequisite (max 1)

If possible, leave 3 or 4 simple exercises as (core: false, unlocked_by: null), as this will provide new participants with some exercises that they can tackle even if they have not finished the first core exercise.

**Comment by robphoenix** [comment]
I've started trying to fill in all the exercise topics and difficulty ratings, roughly, so we can get on to choosing ~10 core exercises.

Though we could probably choose our core exercises now, as well as the 3 or 4 simple exercises that will be outside this hierarchy.

**Comment by tleen** [comment]
[Hello World](../tree/master/exercises/hello-world) should be our first right?

**Comment by tleen** [comment]
What is the overall opinion of core? Is it sort of a mini-track and the unlocks are further explorations? 

Exercises I think differentiate Go from other tracks:
 
* [Scrabble Score](../tree/master/exercises/scrabble-score) - Because it deals with runes which are a unique Go pain point for people transitioning into it
* [Bank Account](../tree/master/exercises/bank-account) - For the structs, variable protection and concurrency
* [Error Handling](../tree/master/exercises/error-handling) - It has proven to be a difficult exercise and introduces some core Go stuff like panics, recovery, errors and named return values. 

These are from the relatively small pool of exercises I have already completed. Many more to go :smile:.

**Comment by robphoenix** [comment]
> Hello World should be our first right?

right :+1:

**Comment by tleen** [comment]
@robphoenix I've been working the config file bottom up so we don't clash.

**Comment by robphoenix** [comment]
Okay all,@tleen @leenipper @ferhatelmas @petertseng, we're getting down to the last few exercises! :tada: 
So we don't duplicate effort I think it's worth *'claiming'* an exercise when updating it in the `config.json`.

Here are the last exercises to be updated:

- [ ] prime-factors (#764)
- [ ] strain (#762)
- [ ] diffie-hellman (#766)
- [ ] beer-song (#772)
- [ ] ocr-numbers (#773)
- [ ] wordy
- [ ] nucleotide-count
- [ ] grade-school
- [ ] matrix
- [ ] saddle-points
- [ ] meetup
- [ ] binary-search
- [ ] binary-search
- [ ] kindergarten-garden
- [ ] simple-cipher
- [ ] paasio
- [ ] pov
- [ ] minesweeper
- [ ] robot-simulator
- [ ] tournament
- [ ] word-search
- [ ] all-your-base
- [ ] connect
- [ ] poker (#768)

So, if you start on one of these, either edit this comment, putting your name next to it, or add a comment below.
Awesome work everyone!

**Comment by tleen** [comment]
I think we get this done then should have a discussion about core. Probably in its own issue? It could get long. Need to spend some time actually mapping out the nextercism version of the track

**Comment by leenipper** [comment]
@robphoenix and @tleen ... you guys have done a tremendous job with the all the exercises' config.json difficulty and topics.   I apologize for my "lateness to the party" to help out with review/suggestions.   I wanted to say a very big thanks to you both before you tie the final bows on these.  :+1:

**Comment by tleen** [comment]
Thanks @leenipper you feedback has been great. It is making for better commits and therefore a better track!

**Comment by tleen** [comment]
FYI: I have been using "Records" rather loosely to correspond with something akin to database "rows".

**Comment by tleen** [comment]
For the track layout discussion: [saddle-points test](https://github.com/exercism/go/blob/master/exercises/saddle-points/saddle_points_test.go) more-or-less suggests you should have have done [matrix](https://github.com/exercism/go/tree/master/exercises/matrix).

**Comment by tleen** [comment]
@robphoenix in honor of the heavy lifting you have done on this :pray: , [config/matrix](../tree/master/exercises/matrix) is yours to bring home. I suggest "Matrices" as one topic :smile:

**Comment by robphoenix** [comment]
>  I apologize for my "lateness to the party" to help out with review/suggestions. 

No need @leenipper, your comments have been invaluable, thankyou. 

> config/matrix is yours to bring home. 

I thought I'd never see the day! Thankyou for getting us here @tleen. Looking forward to writing `closes #345`

Excellent work fellow maintainers, we can move on to choosing our core topics now! :rocket:
