### ISSUE TITLE
simple-cipher missing step #3? 

### ISSUE THREAD

**Issue by tleen** [exercism/go#786]
I may be mistaken (I'm blitzing through the exercises quickly) but does the this track's [simple-cipher](../tree/master/exercises/simple-cipher) not require the user to do the third step in the README with the random key/ArgumentError? This may be a case where we need to override the generated README?

**Comment by leenipper** [comment]
> override the generated README

Agreed.

From the test code in simple-cipher:

> // Steps 2 and 3 seem to be describing the Vigenère cipher (Google it)
> // so let's do that too.  The **random thing, don't worry about**.  There is
> // no test for that.

**Comment by tleen** [comment]
Ok we can fix that, probably worth keeping an eye out on the other autogenerated READMEs they may be out of sync with the implementations.

**Comment by tleen** [comment]
Now I am wondering if we should take over the generated README to fix that one little thing about randomness that the test file says to ignore. We could

- Leave as is - let the test file explain that the random element of step #3 is unnecessary
- Take over the README - remove the randomness text describing step 3
- Fulfill the README - add the randomness requirement into the exercise

**Comment by robphoenix** [comment]
Ideally I think we should fulfill the README, this could perhaps be a separate issue. In the meantime, I like moving notes like these from the test suite into the README.
