### ISSUE TITLE
series: Move bonus instructions to README

### ISSUE THREAD

**Issue by tleen** [exercism/go#804]
[series](https://github.com/exercism/go/blob/master/exercises/series/series_test.go) has the standard series exercise and a bonus exercise. The bonus AFAICT is unique to the Go track. I believe it is also the first time we encounter build tags in the track. This may be a good case for adding to the README directly or putting in a .meta/description.md.

**Comment by robphoenix** [comment]
I agree. I think there's a few exercises where we can move a lot of the text in a test suite into the README.
I think I'd prefer it went in the `.meta/description.md` file to keep it separate, unless this ends up being visually confusing.
