### ISSUE TITLE
Update topic formatting

### ISSUE THREAD

**Issue by tleen** [exercism/go#812]
Topics in the config file should be [lowercase/underscored](https://github.com/exercism/meta/issues/83).

**Comment by robphoenix** [comment]
ah, ok, could you open this on configlet @tleen?

It's a simple fix [here](https://github.com/exercism/configlet/blob/master/cmd/fmt.go#L146) if you want to open a PR :smiley:  (once https://github.com/exercism/meta/issues/83 is finalised)

**Comment by tleen** [comment]
[Opened](https://github.com/exercism/configlet/issues/60).
