### ISSUE TITLE
[nextercism] Move `No Stub` hints.md

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#814]
**THIS SHOULD BE BRANCHED OFF THE NEXTERCISM BRANCH, NOT MASTER**

Previously `twelve-days` was the first exercise without a stub and therefore has this note: https://github.com/exercism/go/blob/e4e0a673dbf4abd10eaea73bf64f6c3f78054a7f/exercises/twelve-days/HINTS.md

This should be moved to the first core exercise without a stub all exercises prior to this should have stubs. I think this could happen much earlier, say the 4th or 5th core exercise, by this time the user could well have completed 11 - 14 exercises.

**Comment by robphoenix** [comment]
Twelve-days is, pre-nextercism, the 13th exercise

Exercises that should have stubs:

- [ ] gigasecond
- [ ] bob
- [ ] acronym
- [ ] hello-world
- [ ] two-fer
- [ ] leap
- [ ] triangle
- [ ] hamming
- [ ] nucleotide-count
- [ ] rna-transcription
- [ ] raindrops
- [ ] accumulate
- [ ] roman-numerals
- [ ] strain

This gives us 14 exercises with a stub and the first exercise without a stub will be `scrabble-score`.

**Comment by robphoenix** [comment]
I think maybe this is overkill??
Perhaps `raindrops` can be the first exercise without a stub, that would give up to 10 exercises that someone will have tackled with a stub. My only concern with this is if someone only tackles the core exercises then there will only be 3 exercises with a stub. Is this a viable concern, am I being overly worried? :man_shrugging:

**Comment by tleen** [comment]
I think after 3 they should probably get the hang of it. I think we would want to make clear in `hello-world` that that exercise is 'stubbed' and what that means. Then we explain in `raindrops` that stubs are a thing of the past and explain how to get started with their own file, but they have to do it themselves. And then we never mention stubs again for the rest of that track.

**Comment by robphoenix** [comment]
> That would be a documentation issue.

:100:

**Comment by robphoenix** [comment]
closed by #860
