### ISSUE TITLE
Nextercism restructuring re-ordered current Exercism 

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#816]
I've been so focused on preparing for Nextercism I completely overlooked how changes to the config.json file would affect the current Exercism track exercises.

Unfortunately https://github.com/exercism/go/commit/0bee9d4964961a4037bc263a67f7e1cb1887b5f4 has re-ordered the track on the current Exercism site.

I'd like to propose that we revert the ordering changes from https://github.com/exercism/go/commit/0bee9d4964961a4037bc263a67f7e1cb1887b5f4, but keep any changes to individual exercises such as `core: true` so that Go will be included in the nextercism site, and create a new `nextercism` branch that can contain any changes specific to Nextercism that may otherwise be a confusion on the current site. This branch could then be merged in at a suitable time for the public launch.

@kytrinyx I'd appreciate a sanity check on this please, thanks.

**Comment by robphoenix** [comment]
I've created the [nextercism](https://github.com/exercism/go/tree/nextercism) branch.

**Comment by tleen** [comment]
This will diverge the configurations so they will be out of sync. This is ok since the current config now has a short shelf life. I would suggest any new topics and stuff go into the nextercism branch.

**Comment by kytrinyx** [comment]
This sounds sensible, with the caveat that @tleen brings up.

**Comment by robphoenix** [comment]
>  I would suggest any new topics and stuff go into the nextercism branch.

Yep, I suggest we have a sort of freeze on the `master` branch except for bug fixes and such. It should be pretty obvious what needs to be in the `nextercism` branch and what can go in `master`.

**Comment by robphoenix** [comment]
closed by https://github.com/exercism/go/commit/a0947517f37e937db5877df0fbd5dadb0312a49a

Just fyi @tleen I felt it best the nextercism branch starts after this commit, so you may need to rebase if you're working off that branch.
