### ISSUE TITLE
Implement List-Ops

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#823]
Accumulate & Strain are both to be deprecated in favour of List-Ops

https://github.com/exercism/problem-specifications/issues/553#issuecomment-279275406
https://github.com/exercism/problem-specifications/issues/588#issuecomment-279275431

This exercise would be a great opportunity to highlight discussions surrounding functional programming in Go and give newcomers to the language an opportunity to gain an understanding of why it's easier just to use a `for loop` in Go than `map/filter/reduce`

For reference:
https://github.com/exercism/go/issues/18
https://github.com/robpike/filter
https://www.reddit.com/r/golang/comments/1m25a1/map_reduce_and_filter_in_go/?st=j6opmjhz&sh=2398c792
https://groups.google.com/forum/#!topic/golang-nuts/RKymTuSCHS0

**Comment by ljagged** [comment]
I implemented this exercise and submitted a [pull request](https://github.com/exercism/go/pull/1126).I didn't see this issue prior to the implementation, otherwise I would have mentioned it. This is my first exercism pull request and I'm still learning go, so I would appreciate any feedback.Thanks!

**Comment by leenipper** [comment]
The list-ops is a useful exercise, even with the discussions referenced.  Thanks for contributing!
