### ISSUE TITLE
Explain test cases file in first exercise with a generator

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#824]
Exercises with generators have the test cases in a separate file from the test suite, we should add a comment to the first exercise this occurs in to explain it.

**Comment by tleen** [comment]
That is `leap` if we go by unlocks or `hamming` if we do not. I will mod both `hints.md` to note the cases_test file. :+1:

**Comment by robphoenix** [comment]
Closed by #878

**Comment by tleen** [comment]
Any idea why did my commit not auto-close this? Was it because it was on the `nextercism` branch?
