### ISSUE TITLE
Nextercism ordering

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#825]
I feel I took the wrong approach in #805 & #813 

I think these attempted to do too much, weren't as thoughtful as they could have been, were driven by an anxiety to get the track ready for Nextercism, and overlooked some of the very considered work @tleen has done towards getting the track ready for Nextercism.

Seeing as #805 also kinda broke the track for current users (#816) I think starting the Nextercism branch is a good place to take a step back and try a different, more gradual approach.

The current `config.json` file has exercises marked as core, but the order of the exercises is what it was for Exercism v1. I'd like to outline, and put up for discussion, what I see as a few logical steps we could take to get the track in to good shape for Nextercism. If these are agreed upon then this issue can be a tracking issue for these steps, which I will open as separate issues to tackle in turn. This is what we do as programmers, take a big problem and break it down into smaller ones.

While I believe I took the wrong approach, I don't feel it was a waste of time, it gave me a much better understanding of what is required of this restructuring.

So...

1. [x] **Choose bonus exercises.** These are exercises that will be marked in the `config.json` file as `core: false, unlocked_by: null`. They will be available as soon as the `hello_world` exercise has been submitted, before approval has been given by a mentor. These are good for giving a user something to get on with on their learning path, as discussed here: https://github.com/exercism/v2-feedback/issues/36
I think these should be fairly low difficulty exercises, of which we have ~2 or 3.
2. [x] **Choose ~20 core exercises**. I think most important is choosing the first 5 - 10 core exercises.
3. [x] **Define order of core exercises** This is perhaps tied up in the previous step, but it may help to just identify core exercises first, and then wrangle over their order?
4. [x] **Identify logical groupings** I think this can be done alongside the previous steps, @tleen has already had some great ideas.
5. [x] **Add unlocked_by exercises to core structure** Once we have our core structure in place we can start discussing the exercises that are unlocked by these.

**Comment by tleen** [comment]
You did a good job on the big config, its a lot of work, so don't feel like you took the wrong approach! It is difficult to do these as small changes because so much of it is interrelated, you always want to just add that next thing, then the next thing from that...

I like this plan, lets do it.

**Comment by robphoenix** [comment]
closed by #835
