### ISSUE TITLE
Choose 'bonus' exercises

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#828]
From #825 

These are exercises that will be marked in the `config.json` file as `core: false, unlocked_by: null`. They will be available as soon as the `hello_world` exercise has been submitted, before approval has been given by a mentor. These are good for giving a user something to get on with on their learning path, as discussed here: https://github.com/exercism/v2-feedback/issues/36
I think these should be fairly low difficulty exercises, and we should have ~2 or 3.

# Bonus Exercises

* `bob`
* `gigasecond`
* `acronym`

**Comment by robphoenix** [comment]
A few potential exercises for this:

1. `leap`
2. `raindrops`
3. `gigasecond`
4. `bob`
5. `rna-transcription`

**Comment by tleen** [comment]
Perhaps the ```pangram``` exercise? That could unlock a whole series of the *gram family: ```isogram``` ```anagram```and ```acronym```. All of which are fairly easy variations of each other.

**Comment by tleen** [comment]
I'm thinking```raindrops``` for core.

**Comment by robphoenix** [comment]
> That could unlock a whole series of the *gram family

Do we want to have a bonus exercise unlock other exercises? I thought they would be standalone.

> raindrops for core.

I agree with your reasoning, (fizzbuzz), but that reasoning kinda makes me think it might be good as a bonus, it can be a good one to tackle early as it could be a familiar problem that just requires learning a different syntax. I'm not particularly invested in this view though :smiley:

**Comment by tleen** [comment]
`bob` is a similar exercise to raindrops which may work well as a bonus.

**Comment by tleen** [comment]
> Do we want to have a bonus exercise unlock other exercises? I thought they would be standalone.

I think that is more in keeping with their goal.

**Comment by robphoenix** [comment]
> I think that is more in keeping with their goal.

Sorry, I'm not clear which one *that* is referring to. :smile: 

tbh I quite like pangram for core.

> bob is a similar exercise to raindrops which may work well as a bonus.

Yeah I like `bob` for bonus. Shall we lock it in for bonus and leave raindrops for core?

**Comment by robphoenix** [comment]
I think either one of `leap` or `gigasecond` could work for bonus. I'm in two minds about `gigasecond`, the use of the `time.Time` type could easily trip up someone coming from a dynamic programming background, I think it did me. But on the flipside, it could be a good nudge to investigate the standard library and deal with the idea of types (maybe it should be a topic for the exercise??) in a fairly simple manner.

**Comment by robphoenix** [comment]
Maybe `scrabble-score` or `etl` alongise `bob` and `leap` or `gigasecond`?
I think that would give a nice set of exercises to get started with, covering `strings`, `for loops`, `maps`, potentially `boolean logic` or `std lib types`, and `functions`.

**Comment by tleen** [comment]
>> I think that is more in keeping with their goal.

> Sorry, I'm not clear which one that is referring to.

Ah I was talking about the goal of bonus exercises. Having them be as-is without unlocking other exercises. We should keep them standalone.

**Comment by tleen** [comment]
It's probably ok to include `gigasecond` into the bonus pool. We can add a note to the README about the stdlib Time etc. They are stubbed and basically one liners so the initial bonus area would be a good place. Time does come into play but if they get stuck its not blocking anything.

**Comment by tleen** [comment]
> tbh I quite like pangram for core.

Yep me too. Then it can unlock that whole group. This way if a user liked the exercise they can go at 3 similar ones. Conversely if they are not into string-hunting it they can skip all the related ones.

> Yeah I like bob for bonus. Shall we lock it in for bonus and leave raindrops for core?

I'm for that.

**Comment by tleen** [comment]
> Maybe `scrabble-score` or `etl` alongside `bob` and `leap` or `gigasecond`?

The only reason I would want to keep those out of bonus is that I have them mentally mapped as an tightly related unlock grouping. Both are scrabble related (characters <-> numbers), the `scrabble-score` is best solved with a Map while `etl` forces you to use one. I figured we would pick a place where we think it is time to get Maps in the users head and use those to get it going. I would hope that if a user did not use a Map to solve `scrabble-score` *then* did `etl` they would have an ah-ha moment, and go back to `scrabble-score`, use a Map instead of a huge conditional and **get** why you use Maps.

I have to think if you are a beginning programmer Maps could be a real mind-blower even moreso than Time in the stdlib. But they are hugely important for problem solving so it should probably be in core somewhere...

**Comment by robphoenix** [comment]
> The only reason I would want to keep scrabble-score/etl out of bonus is that I have them mentally mapped as an tightly related unlock grouping. 

Yeah, I had that originally as well.

> I would hope that if a user did not use a Map to solve scrabble-score then did etl they would have an ah-ha moment, and go back to scrabble-score, use a Map instead of a huge conditional and get why you use Maps.

This is brilliant. It's happened to me, going back and refactoring previous exercises after a :bulb: moment in another one.

Maybe we just keep it with these two, `bob` & `gigasecond`?
We could then have `leap` and `rna-transcription` opened by `hello-world` or `two-fer`?

**Comment by tleen** [comment]
Ok lets go with that.

**Comment by robphoenix** [comment]
Closed by #835
