### ISSUE TITLE
Choose 'core' exercises

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#829]
From #825 
See also #794

Roughly 20 exercises.

# Core Exercises [difficulty] (Ordering to be finalised)
1. [`hello-world`](https://github.com/exercism/go/tree/master/exercises/hello-world) [1]
1. [`two-fer`](https://github.com/exercism/go/tree/master/exercises/two-fer) [1]
1. [`hamming`](https://github.com/exercism/go/tree/master/exercises/hamming) [1]
1. [`raindrops`](https://github.com/exercism/go/tree/master/exercises/raindrops) [1]
1. [`scrabble-score`](https://github.com/exercism/go/tree/master/exercises/paasio) [1]
1. [`isogram`](https://github.com/exercism/go/tree/master/exercises/isogram) [2]
1. [`difference-of-squares`](https://github.com/exercism/go/tree/master/exercises/difference-of-squares) [2]
1. [`luhn`](https://github.com/exercism/go/tree/master/exercises/luhn) [2]
1. [`grains`](https://github.com/exercism/go/tree/master/exercises/grains) [2]
1. [`clock`](https://github.com/exercism/go/tree/master/exercises/clock) [3]
1. [`parallel-letter-frequency`](https://github.com/exercism/go/tree/master/exercises/parallel-letter-frequency) [3]
1. [`tree-building`](https://github.com/exercism/go/tree/master/exercises/tree-building) [3]
1. [`robot-name`](https://github.com/exercism/go/tree/master/exercises/robot-name) [3]
1. [`tournament`](https://github.com/exercism/go/tree/master/exercises/tournament) [3]
1. [`twelve-days`](https://github.com/exercism/go/tree/master/exercises/twelve-days) [4]
1. [`matrix`](https://github.com/exercism/go/tree/master/exercises/matrix) [4]
1. [`error-handling`](https://github.com/exercism/go/tree/master/exercises/error-handling) [5]
1. [`bank-account`](https://github.com/exercism/go/tree/master/exercises/bank-account) [4]

**Comment by tleen** [comment]
lol I was typing the list of current ones as this popped up :+1:

**Comment by robphoenix** [comment]
> lol I was typing the list of current ones as this popped up

great minds...

**Comment by tleen** [comment]
The first 4 are perfect. I had them pegged as the starter core too. ```pangram``` and ````acronym``` are probably too alike to be both in core. I figured one of the *gram exercises would have the others as bonus. 

Some others I think warrant discussion for core:

-  [`tree-building`](https://github.com/exercism/go/tree/master/exercises/tree-building) - Mostly because it introduces the concept of refactoring.

-  [`robot-name`](https://github.com/exercism/go/tree/master/exercises/robot-name) - The idea of preventing colllisions makes this an interesting exercise. Randomness is a good thing to explore.

- [`bank-account`](https://github.com/exercism/go/tree/master/exercises/bank-account) - I think one core exercise should deal with state management. I learned a lot on this one. That it has concurrency protection is a nice bonus.

- [`allergies`](https://github.com/exercism/go/tree/master/exercises/allergies) - Bitmasking is such a useful concept, ideeally one of the core exercises would use it and then it can gateway into other bitwise exercises, like  [`secret-handshake`](https://github.com/exercism/go/tree/master/exercises/secret-handshake).

- [`error-handling`](https://github.com/exercism/go/tree/master/exercises/error-handling) - Error handling is such an important topic in Go. This exercise may actually be too hard to introduce it but it's what we have for now. Eventually I would like to add an simple early core exercise that deals with multiple return values and the idiomatic err pattern.

- [`passio`](https://github.com/exercism/go/tree/master/exercises/passio) - Because it uses standard interfaces Readers/Writers and is an example of some good patterning.

These were ones I noted going through the track so far...

**Comment by robphoenix** [comment]
> pangram and acronym are probably too alike to be both in core. I figured one of the *gram exercises would have the others as bonus.

Agreed, I think `pangram` would be good core, unlocking `acronym` and the other *gram exercises.

**Comment by robphoenix** [comment]
> tree-building - Mostly because it introduces the concept of refactoring.

:+1: 

> robot-name - The idea of preventing collisions makes this an interesting exercise. Randomness is a good thing to explore.

:+1: Yep, I like this, I do think though it's probably worth bringing the bonus tests into the main test suite. I don't think anything's gained from splitting them. If needs be we can describe in the readme how to only run certain tests with `go test` so the user can work on them incrementally.

> bank-account - I think one core exercise should deal with state management. I learned a lot on this one. That it has concurrency protection is a nice bonus.

I had thought of this being unlocked by `parallel-letter-frequency` being as they're both concerned with concurrency, but they consider it from different angles I suppose. `plf` as in intro to `goroutines` and `channels` and this as an intro to `mutexes`. I think they could both work as core, rather than having a separate concurrency series of exercises unlocked by each other. Ok :+1: and I'd like to see `plf` as core before it.

> allergies - Bitmasking is such a useful concept, ideeally one of the core exercises would use it and then it can gateway into other bitwise exercises, like secret-handshake.

Couldn't agree more about bit-shifting. I had `grains` down as a core exercise to unlock `allergies`, `secret-handshake`, & `variable-length-quantity`, what do you think?

>error-handling - Error handling is such an important topic in Go. This exercise may actually be too hard to introduce it but it's what we have for now. Eventually I would like to add an simple early core exercise that deals with multiple return values and the idiomatic err pattern.

I think this could be core, I don't think it's necessarily too hard, I think it's just a little confusing, with some clearer explanation in the README it could be easier to digest. So :+1: with the caveat that the documentation is improved.

> paasio - Because it uses standard interfaces Readers/Writers and is an example of some good patterning.

Ok I can get down with that :+1: though it should come after `bank-account` due to it's use of `mutexes` and I think the documentation could be improved to help getting started.

**Comment by robphoenix** [comment]
For your consideration...

* `pangram` - unlocking `acronym`, and the other `*gram` exercises
* `parallel-letter-frequency` - as an introduction to go concurrency primitives
* `grains` - unlocking a series of bitshifting exercises; `allergies`, `secret-handshake`, & `variable-length-quantity`
* `clock` - a fairly easy exercise dealing with types, `New()` and methods

**Comment by tleen** [comment]
Ok liking this sofar. Liking `parallel-letter-frequency` as a concurrency concept unlock. We should probably freeze here, put this into config and see how it looks via the visualizer.

**Comment by tleen** [comment]
Ok here is how the early track looks now...

![screenshot from 2017-08-24 19-59-45](https://user-images.githubusercontent.com/1599679/29694037-218681b2-8907-11e7-9183-96634fd3ffcc.png)

**Comment by tleen** [comment]
So we should move `anagram`+ `isogram` to a `pangram` unlock?

**Comment by tleen** [comment]
and have `accumulate` unlock `strain`? both are the functional programming exercises.

**Comment by tleen** [comment]
I've been playing with it. Starts to get to be a really long aside. Perhaps we should stick all the dna stuff together with `hamming`?

**Comment by tleen** [comment]
Here is a possibility sticking the dna stuff in hamming. `raindrops` would need some bonus unlocks and I think `clock` would need to be earlier:

![screenshot from 2017-08-25 15-35-15](https://user-images.githubusercontent.com/1599679/29729684-2471045c-89ab-11e7-9016-1e173422f3f1.png)

**Comment by tleen** [comment]
Lets try to define the core exercises up to clock, then the associated unlocks. That will take a swath of exercises off the table for the next section. We can always refine later if something pops up.

**Comment by tleen** [comment]
Future note: `tree-building` can unlock `ledger`, also `binary-search-tree` perhaps. The user should encounter `binary-search` somewhere before `binary-search-tree` even if it has to be an unlock off of `tree-building` first...

**Comment by robphoenix** [comment]
> Lets try to define the core exercises up to clock, then the associated unlocks. That will take a swath of exercises off the table for the next section. We can always refine later if something pops up.

Okay, core up to clock are currently:

1. [`hello-world`](https://github.com/exercism/go/tree/master/exercises/hello-world) [1]
1. [`two-fer`](https://github.com/exercism/go/tree/master/exercises/two-fer) [1]
1. [`hamming`](https://github.com/exercism/go/tree/master/exercises/hamming) [1]
1. [`raindrops`](https://github.com/exercism/go/tree/master/exercises/raindrops) [1]
1. [`scrabble-score`](https://github.com/exercism/go/tree/master/exercises/paasio) [1]
1. [`pangram`](https://github.com/exercism/go/tree/master/exercises/pangram) [2]
1. [`grains`](https://github.com/exercism/go/tree/master/exercises/grains) [2]
1. [`clock`](https://github.com/exercism/go/tree/master/exercises/clock) [3]


@tleen `pangram` is currently core, do you want to switch that for `isogram`? If so, we should perhaps adjust their difficulties. Do you want to add `difference-of-squares` to core? 

> sticking the dna stuff in hamming. raindrops would need some bonus unlocks (the only one I think is suitable is bob but we have that as an initial bonus) 

I'm starting to think we shouldn't worry so much about grouping these exercises together around themes within the subject matter of the exercises (dna for instance). I think we have a pretty good set of core exercises, and we should go through defining 1-3 exercises of suitable difficulty that each of these can unlock. For instance:

* hello-world
  * bob (bonus)
  * gigasecond (bonus)
* two-fer
  * leap
* hamming
  * etl
  * acronym
* isogram
  * pangram
  * anagram
* raindrops
  * triangle
  * rna-transcription
* scrabble-score
  * nucleoide-count
  * protein-translation
* grains
  * allergies
  * secret-handshake
  * variable-length-quantity
* clock

I'm also conscious of filling up the repo's log with commits changing things around over and over, so I think we should wait until we've at least got the majority of core exercises and what they unlock defined before we commit the structure again. If needs be we can start another branch off the `nextercism` branch that we can commit to without care, and then rebase it and remove all the unnecessary commits, leaving only one that makes the change?

**Comment by tleen** [comment]
ok sounds good.

**Comment by robphoenix** [comment]
> I like difference-of-squares as an earlyish core exercise 

What do you think of it between `isogram` & `grains`?

**Comment by kytrinyx** [comment]
I just came by to drop this link: https://twitter.com/billglover/status/906017681148481537
as an extra vote for having error-handling as part of the core 👍

**Comment by robphoenix** [comment]
closed by #835
