### ISSUE TITLE
Identify logical exercise groupings

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#830]
See #825

**Comment by robphoenix** [comment]
`twelve-days`
`food-chain`
`house`
`beer-song`

**Comment by robphoenix** [comment]
`pangram`
`isogram`
`anagram`
`acronym`

**Comment by tleen** [comment]
[`accumulate`](https://github.com/exercism/go/tree/master/exercises/accumulate)
[`strain`](https://github.com/exercism/go/tree/master/exercises/strain)

Both functional programming exercises.

**Comment by tleen** [comment]
[`raindrops`](https://github.com/exercism/go/tree/master/exercises/raindrops)
[`bob`](https://github.com/exercism/go/tree/master/exercises/bob)

Centrally both behave the same way, a big switch on input.

**Comment by robphoenix** [comment]
bit-shifting

`grains`
`allergies`
`secret-handshake`
`variable-length-quantity`

**Comment by tleen** [comment]
`scrabble-score`
`etl`

Scrabble based, both deal with mapping runes <-> numbers, [Map focused](https://github.com/exercism/go/issues/828#issuecomment-324605857).

**Comment by tleen** [comment]
Take an ASCII-art style representation of data and identify what it encodes:

[`kindergarten-garten`](https://github.com/exercism/go/tree/master/exercises/kindergarten-garden)
[`ocr-numbers`](https://github.com/exercism/go/tree/master/exercises/ocr-numbers)

Inversely, take data in one representation and output it in ASCII-art style.

[`diamond`](https://github.com/exercism/go/tree/master/exercises/diamond)
[`tournament`](https://github.com/exercism/go/tree/master/exercises/tournament)

**Comment by tleen** [comment]
Create output 'shape' based on input value.

[`pascals-triangle`](https://github.com/exercism/go/tree/master/exercises/pascals-triangle)
[`diamond`](https://github.com/exercism/go/tree/master/exercises/diamond)

**Comment by tleen** [comment]
[Matrix](https://en.wikipedia.org/wiki/Matrix_(mathematics)) manipulation/search usually as multi-dimensional arrays.

[`matrix`](https://github.com/exercism/go/tree/master/exercises/matrix)
[`word-search`](https://github.com/exercism/go/tree/master/exercises/word-search)
[`queen-attack`](https://github.com/exercism/go/tree/master/exercises/queen-attack)
[`saddle-points`](https://github.com/exercism/go/tree/master/exercises/saddle-points)
[`transpose`](https://github.com/exercism/go/tree/master/exercises/transpose)
[`minesweeper`](https://github.com/exercism/go/tree/master/exercises/minesweeper)

**Comment by tleen** [comment]
String manipulation/search based around the concept of DNA.

[`rna-transcription`](https://github.com/exercism/go/tree/master/exercises/rna-transcription)
[`nucleotide-count`](https://github.com/exercism/go/tree/master/exercises/nucleotide-count)
[`protein-translation`](https://github.com/exercism/go/tree/master/exercises/protein-translation)

**Comment by tleen** [comment]
Refactoring existing code.

[`ledger`](https://github.com/exercism/go/tree/master/exercises/ledger)
[`tree-building`](https://github.com/exercism/go/tree/master/exercises/tree-building)

**Comment by shaleh** [comment]
Primes:

prime-factors
nth-prime

**Comment by robphoenix** [comment]
closed by #835
