### ISSUE TITLE
robot-name: merge bonus tests into main test suite

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#832]
From https://github.com/exercism/go/issues/829#issuecomment-324587887

> it's probably worth bringing the bonus tests into the main test suite. I don't think anything's gained from splitting them. If needs be we can describe in the readme how to only run certain tests with go test so the user can work on them incrementally.

**Comment by shaleh** [comment]
Agreed. If there is a separation pointing to the `go build` docs so the user knows to pass `-tags bonus` or `-tags simple-only` would be a good idea.
