### ISSUE TITLE
error-handling: improve documentation

### ISSUE THREAD

**Issue by robphoenix** [exercism/go#833]
From https://github.com/exercism/go/issues/829#issuecomment-324587887

>  it's just a little confusing, with some clearer explanation in the README it could be easier to digest. So :+1: with the caveat that the documentation is improved.

**Comment by tleen** [comment]
@robphoenix I was thinking of moving the Nextercism tag off of all the README problems and handling them now via the .meta/descriptions or updating the exercises themselves.

**Comment by tleen** [comment]
Also @robphoenix, you may have seen this but in getting started on some of these I hit this bug: exercism/configlet#65

**Comment by robphoenix** [comment]
I did, thanks @tleen, I was a little confused myself about how we should update the exercise READMEs

**Comment by tleen** [comment]
Long term we probably want to bring the exercises into line with the problem-specification READMEs. But for quick fixes I think it is ok to adjust the README's locally.
