### ISSUE TITLE
roman-numerals: README says no bigger than 3000 but has 3999 as test case

### ISSUE THREAD

**Issue by shaleh** [exercism/go#836]
So which is it? No bigger than 3000? Or no bigger than 3999?

**Comment by tleen** [comment]
Appreciate you opening this issues. Lots of out of sync READMEs with the test data. Please keep posting as you find.

**Comment by robphoenix** [comment]
Thanks @shaleh this is really useful to us. As @tleen says, do keep highlighting these things as you find them. We hope to get these discrepancies dealt with for the new Exercism launch.
