### ISSUE TITLE
poker: README needs more implementation detail

### ISSUE THREAD

**Issue by tleen** [exercism/go#853]
[It](https://github.com/exercism/go/blob/master/exercises/poker/README.md) is fairly sparse on the expected implementation.

**Comment by shaleh** [comment]
The wikipedia link is helpful. Document that no jokers are used.

Document that a list of hands which are 5 cards is the input. Each hand is composed of cards separated by spaces.

The expected return is also a list of hands in the same format as the input. This allows for a tie.

**Comment by shaleh** [comment]
This challenge would be interesting if there was a level 2 using a different number of cards.

**Comment by tleen** [comment]
Closed via 9e637cbf4c1623f50f18bd307249f8533df5f9d9.
