### ISSUE TITLE
Commentary on nextercism config.json

### ISSUE THREAD

**Issue by shaleh** [exercism/go#868]
As promised, @robphoenix.

 * robot-name: I used a singleton pattern and Go's `once` construction. This will also be the first task to use methods and receive by reference. None of this is reflected in the topics. The difficulty is not increased. For someone well verses in Go this is likely a trivial task.
 * error-handling: This is one of the first uses of `defer` and `recover`. Again, no Go specific topics there. Perhaps callbacks? Exception handling?
 * bank-account: again `defer`. Also, maybe OO design?
 * triangle: unlocked by leap this is the first to really introduce types, enums, etc. No mention in topics
 * pascals-triangle: topics: recursion, algorithms
 * queenattack: topics: mathematics
 * anagram: topics: sorting
 * react: topics: interfaces, callbacks
 * phone-numbe: topics: regexp?
 * nth-prime & prime-factors: I used the same core code to solve both problems
 * saddle-points: with the matrix code written, this was a snap
 * word-search: for some programmers this could be more difficult than a 4
 * change: the large number test bumps up the difficulty. I started with greedy, then used a simple either or. When I hit that test I had to write a smarter solution. Perhaps make it an option to the developer?

All in all the unlocks and general order appears pretty sane.

**Comment by tleen** [comment]
We are free to add our own topics, at the same time if something we think should be a topic and is not, I feel it should be proposed first in the [TOPICS.txt](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt) file. Sometimes [things don't get included](https://github.com/exercism/problem-specifications/pull/886), which should not preclude it from our track but we should give the problem-spec contributors a fair crack at thinking on the topic as a global before including it locally.

> saddle-points: with the matrix code written, this was a snap

This is really why I wanted all the matrix stuff together. It feels like if you solved one the rest follow fairly easily.

> queenattack: topics: mathematics

It doesn't seem obvious to me. Is it graph coordinate stuff?

> error-handling: This is one of the first uses of defer and recover. Again, no Go specific topics there. Perhaps callbacks? Exception handling?

I think this is our best exercise when it comes to teaching people how go works. It is an exercise that problem-specifications is very general about, so if we would have custom topics it would be here.

> robot-name: I used a singleton pattern and Go's `once` construction. 

If you think `once` is useful enough here we should probably include it in the HINTS.md file for the exercise so users can explore it before implementation.

Everything else seems ok, if you want we can `nextercism` PR them into existence (or at least a deeper debate!).

**Comment by shaleh** [comment]
robot-name felt like a great place to learn the `once` pattern. It made the central name store pretty easy to implement and would allow for an expansion of concurrent robot naming. I spent more code on the random name generation than anything else. The bonus_example.go uses a naked map which totally works. I pushed each exercise as a way to learn parts of Go or flex some older programming skills. A singleton acting as name store and generator is a pretty canonical pattern. The example is that pattern implemented more loosely.

react is a close second to error-handling in terms of exercising Go machinery.

I solved the queen by asking of the point was on a line. Basic geometry maths.

I started this as an Issue instead of a PR because I was not sure where to hold the conversation. I can make a PR of the obvious bits and we can discuss how to document the Go specific topics.

**Comment by robphoenix** [comment]
> I started this as an Issue instead of a PR because I was not sure where to hold the conversation. 

:+1: 

> I can make a PR of the obvious bits 

I'd be happy to see PR's for the following things you mention:

* pascals-triangle: topics: recursion, algorithms
* queenattack: topics: mathematics (this wasn't obvious to me either, but you've convinced me :smile: )
* anagram: topics: sorting
* react: topics: interfaces (callbacks isn't obvious to me, would you mind expanding on this a bit, thanks)
* phone-number: topics: regular_expressions
* word-search: for some programmers this could be more difficult than a 4 (increase difficulty to a 5?)

If you could open an individual PR for each one that would be great, thanks. This means there can be any further discussion on each change individually, and it keeps individual changes separate in the commit log.

> change: the large number test bumps up the difficulty. I started with greedy, then used a simple either or. When I hit that test I had to write a smarter solution. Perhaps make it an option to the developer?

I suppose it might be possible to split the test cases up and advise the user on how to only run certain test cases

```
go test -run=SmallNumbers
```

This though would have to be done by the generator.

> and we can discuss how to document the Go specific topics.

I think this is a discussion that merits it's own issue.

> robot-name felt like a great place to learn the once pattern

I'm not well-versed in CS or design patterns. If you think this is a useful addition to the exercise then perhaps open an issue expanding on this and how it might be documented, or even open a PR with any changes you think might improve this exercise.

Lastly, thankyou very much for this thoughtful review @shaleh, it's really helpful and appreciated. :tada: 
 And apologies it's been a slow process contributing to this repo recently, thankyou for your patience! :pray: 

I'm going to close this issue as I think any further discussion from ideas raised here can take place in more specific issues.
