### ISSUE TITLE
pangram: more tests

### ISSUE THREAD

**Issue by navossoc** [exercism/go#872]
I was going to make a pull request with two more simples test cases, but I got really confused 😕 

https://github.com/exercism/go/blob/master/exercises/pangram/pangram_test.go
https://github.com/exercism/go/blob/nextercism/exercises/pangram/pangram_test.go

Both tests look almost the same, but on the `nextercism` it don't have a `targetTestVersion` const.

If I will do a pull request should I add the `targetTestVersion` or since this branch are not released yet should I maintain as the initial test (no constant)?

Anyway, I want to add this two tests:

```go
{"abcdefghijklmnopqrstuvwxy", false, "missing character 'z'"},
{"bcdefghijklmnopqrstuvwxyz", false, "missing character 'a'"},
```

There is nothing special on this two cases, but I saw a few people resolving this exercise doing a loop to put all the letters on a map, but most of them forgot to include the 'z' letter.
This is not the best way to solve it, but hey, the tests should at least enforce the correctness of the code.

```go
for i := 'a'; i < 'z'; i++ {
```

So, to cover loops on both directions, this two cases should do the trick.

Let me know if you want me to do a pull request to the `nextercism` branch, but let me know if I should add that version constant.

**Comment by tleen** [comment]
`nextercism` removed the need for test versioning (#861). I think it is best to add this to the `nextercism` branch. Eventually the tests should be automatically generated from the problem-specifications (#605) but for now this is a good modification.

**Comment by navossoc** [comment]
Done, take a look:
https://github.com/exercism/go/pull/873

Feel free to close this issue after merging the pull request.
