### ISSUE TITLE
Change label "good first patch" to "good first issue"?

### ISSUE THREAD

**Issue by tleen** [exercism/go#896]
Just saw this announcement: 

![screenshot from 2017-10-11 20-05-50](https://user-images.githubusercontent.com/1599679/31472949-b018b34a-aebf-11e7-8770-2a1090092328.png)

Should we change our "good first patch" label to be "good first issue"? We have the "help wanted" already.

**Comment by robphoenix** [comment]
Makes sense :+1:

**Comment by ferhatelmas** [comment]
I agree it seems better wording.

**Comment by tleen** [comment]
All set on this, do you think it is redundant to have a "good first issue", "beginner friendly" and "first-timers only"?

**Comment by ferhatelmas** [comment]
I would say yes. I think this is one of `Less is more` cases.

**Comment by robphoenix** [comment]
Yep, I agree with this also.

**Comment by tleen** [comment]
Combined those other two labels were on one issue (#857). I relabeled it to "good first issue" for historical purposes and removed "beginner friendly" and "first-timers only" from the label pool.
