### ISSUE TITLE
Why is config not handled globally ?

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/go#904]
It seems each track is setting its own `difficulty`, `topics`, `core` and `unlocked_by` exercises. Why isn't it handled as problem specifications ? This way, they will be discussed in one place.

If there is some documentation I'm missing, could you guide me ?

**Comment by tleen** [comment]
It the core issue of Exercism, something that is hard in one language may be easy in another. Concepts that may be obvious in one language may be tricky in another. There is a constant push and pull between what should be common across the board and what is unique to each track. Take the READMEs for instance: common information in `problem-specifications` but also some need track-specific instructions and hints. It would be very difficult to come to a language-independent consensus on difficulty for an exercise, we sometimes have a hard time agreeing for an exercise in a single language! :smile:

**Comment by tleen** [comment]
@ferhatelmas I think any discussion about this is best handled in exercism/problem-specifications#968, it's an Exercism-wide issue not specific to our track. If you agree you can close the issue.

**Comment by ferhatelmas** [comment]
@tleen Thanks.

I wanted to ask first here since I might be missing pieces (especially in the light of that I was away and many changes are going on).

However, after your explanation, it's clear that it might be hard to solve for all but we can close this and follow up this problem on common repositories. Will try to chime in. 

If you aware of other issues related to this problem, please link them here.
