### ISSUE TITLE
complex-numbers: implement exercise

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/go#918]
[Specification](https://github.com/exercism/problem-specifications/tree/master/exercises/complex-numbers).

**Comment by mcaci** [comment]
Hello everyone, I would love to contribute to the track with this exercise if you agree :)

**Comment by mcaci** [comment]
I have started reading the documentation here to see what to do: https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md 

Would there be other documentation I should read before starting?

**Comment by eklatzer** [comment]
Hey, I will add the exercise

**Comment by saurami** [comment]
@eklatzer - can you share the updated link to implement an exercise from specification ?

The [current link](https://github.com/exercism/docs/blob/main/you-can-help/implement-an-exercise-from-specification.md) shows a 404

**Comment by eklatzer** [comment]
I hope this helps: [implement-an-exercise-from-specification](https://github.com/exercism/legacy-docs/blob/9f69fa90dbd8d1a91c9b3ad179c468dd9ae4c453/you-can-help/implement-an-exercise-from-specification.md)

**Comment by junedev** [comment]
@eklatzer Is there really no version of this on any non-legacy repo or `exercism.org/docs`? Did you find the instructions in there were still roughly correct?

**Comment by eklatzer** [comment]
I only searched for the name of the file and Exercism and found this one. Did not search further as everything was clear for me

**Comment by junedev** [comment]
I couldn't find a good equivalent in the docs repo, I will open an issue there.
