### ISSUE TITLE
markdown: implement exercise

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/go#925]
[Specification](https://github.com/exercism/problem-specifications/tree/master/exercises/markdown)

**Comment by ilmanzo** [comment]
I'm going to tackle this :) what could be a good function name for markdown to html conversion ? is "Convert(input string) string" clear enough ?

**Comment by leenipper** [comment]
Render or Parse will work.

Remember that this exercise is a "re-factor". As well as the example.go, create a .go file which also passes the tests but _**needs refactoring.**_  There is at least one other re-factor exercise for reference.

**Comment by ilmanzo** [comment]
mm I'm sure my example implementation needs refactoring :) If you agree I'll send a first PR just to have some feedback, then we can discuss on that
