### ISSUE TITLE
nucleotide-codons: implement exercise

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/go#926]
[Specification](https://github.com/exercism/problem-specifications/tree/master/exercises/nucleotide-codons)

**Comment by ilmanzo** [comment]
I guess you can close this issue; specification says

**NOTE: This exercise has been deprecated**
Your track should implement protein-translation instead.

(which is already implemented)

**Comment by leenipper** [comment]
Thanks @ilmanzo.
Closing due to [deprecated exercise](https://github.com/exercism/problem-specifications/commit/d6b97a4f79d473c2d70e3ed96eadaf3fab202b91#diff-48fd1d77915a9d98fa8881b0ac09c05c).
