### ISSUE TITLE
zipper: implement exercise

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/go#933]
[Specification](https://github.com/exercism/problem-specifications/tree/master/exercises/zipper)

**Comment by sladyn98** [comment]
@ferhatelmas would love to work on this issue could you guys guide me a bit on what is required :)

**Comment by sladyn98** [comment]
@ferhatelmas Can you guys guide me on how should I proceed, would love to contribute.

**Comment by leenipper** [comment]
@sladyn98, We appreciate your interest to help out! 

The main [README.md](https://github.com/exercism/go/blob/master/README.md) is the best starting point.    The [Exercise Files Overview](https://github.com/exercism/go/blob/master/README.md#exercise-files-overview) section explains the different files for implementing an exercise.

Are there any specific questions you have on how to start?
