### ISSUE TITLE
testVersion defined in some exercises

### ISSUE THREAD

**Issue by ardrigh** [exercism/go#941]
I noticed that some of the exercises I was getting have the `testVersion` defined in them, possibly added by #860 

Looking through the commit history, it appears these should have been removed by #861 

A [quick repo search](https://github.com/exercism/go/search?utf8=%E2%9C%93&q=testVersion&type=) finds four examples where this is still defined

Just thought I'd point it out for consistency sake.

**Comment by tleen** [comment]
Thanks!

**Comment by ferhatelmas** [comment]
@ardrigh Thanks for great issue description. :heart:
