### ISSUE TITLE
Transpose Test might not make sense in test 6

### ISSUE THREAD

**Issue by psimoesSsimoes** [exercism/go#965]
There are these two tests:

{
		"first line longer than second line",
		[]string{
			"The fourth line.",
			"The fifth line.",
		},
		[]string{
			"TT",
			"hh",
			"ee",
			"  ",
			"ff",
			"oi",
			"uf",
			"rt",
			"th",
			"h ",
			" l",
			"li",
			"in",
			"ne",
			"e.",
			".",
		},
	},
	{
		"second line longer than first line",
		[]string{
			"The first line.",
			"The second line.",
		},
		[]string{
			"TT",
			"hh",
			"ee",
			"  ",
			"fs",
			"ie",
			"rc",
			"so",
			"tn",
			" d",
			"l ",
			"il",
			"ni",
			"en",
			".e",
			" .",
		},
},

I might be wrong but in test "first line longer than second line" shouldn't the last string in the array be ". " instead of "." ? this would make sense according to example "second line longer than first line"

**Comment by leenipper** [comment]
Thanks for asking about this item.

As best I can tell, the expected test results are following these two statements in the README:
```
- Pad to the left with spaces.
- Don't pad to the right.
```

The test cases in the exercise are generated from [this file](https://github.com/exercism/problem-specifications/blob/master/exercises/transpose/canonical-data.json), and have stood the test from other exercism language tracks; so my assumption is that the test data is as intended.

**Comment by psimoesSsimoes** [comment]
God... Shame on me. I should have read the readme again.
Thanks for the info!

**Comment by leenipper** [comment]
Quite alright, @psimoesSsimoes .  I remember being a bit confused about that exercise's expected test results myself!
