### ISSUE TITLE
Is there an error in the luhn test cases?

### ISSUE THREAD

**Issue by kevin-DL** [exercism/go#972]
Hello, maybe my understanding of the test case is wrong
```go
{
	"a simple valid SIN that becomes invalid if reversed",
	"59",
	true,
}
```
Shouldn't the expected result be false in this case?

**Comment by tleen** [comment]
It is valid via the Luhn formula:

> double every second digit, starting from the right
59
(10)9
> if doubling the number results in a number greater than 9 then subtract 9 from the product.
(10-9)9
(1)9
19
> sum the digits
1 + 9 = 10
> if sum is evenly divisible by 10 it passes
10/10 = 1r0

**Comment by kevin-DL** [comment]
Thanks, the description of the test case threw me off.

Cheers
Kevin

**Comment by kevin-DL** [comment]
It's my bad, thinking too much.
Closing

**Comment by vr001** [comment]
```
{
        "a valid Canadian SIN",
        "055 444 285",
        true,
    }
```
The sum is 35. Correct me if I am wrong. 
If thats the case can someone explain how this becomes valid?

Thanks. (Sorry if my question is silly)
