### ISSUE TITLE
reverse-string: Implement Benchmark Test

### ISSUE THREAD

**Issue by billglover** [exercism/go#973]
The current version of the tests for the `reverse-string` exercise don't include benchmark tests.

Given the numerous different ways a solution to this exercise could be implemented, I felt like a benchmark test would be appropriate here.

Link to tests: [reverse_string_test.go](https://github.com/exercism/go/blob/master/exercises/reverse-string/reverse_string_test.go)

**Comment by billglover** [comment]
I'd be happy to implement this and raise a pull request if this is worthwhile.

Before I do so, I'm off to re-read the contributing guidelines.

**Comment by tleen** [comment]
@billglover that would be awesome.

**Comment by billglover** [comment]
On it!
