### ISSUE TITLE
Police commit messages

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/go#979]
We have some style guide for commit messages such as
 * add exercise name with colon

Let's setup some tools to better service new comers:
 * https://gitcop.com/

Please add your suggestions. Otherwise, I'm planning to go with mine at the weekend.

**Comment by leenipper** [comment]
Good idea.
exercisename: topic blah blah
is a good starting point.

**Comment by tleen** [comment]
That is a neat tool!

It may not be able to discriminate enough between repo issues and specific exercise issues. Things like:

readme:
gen: 
maintainers: 
...

**Comment by ferhatelmas** [comment]
@kytrinyx We need admin rights on repo to enable it. Could you enable it for us or give us right so that we can enable for ourselves? Thanks!

**Comment by kytrinyx** [comment]
GitCop is asking for read AND write access to commit statuses for every single repository that I have access to, public and private, across all organizations.

I'm not comfortable with this.

If GitCop converts their service to using a GitHub App rather than an OAuth app so that we can install it on just a single repository, then I'd be OK with using it. https://developer.github.com/apps/

**Comment by ferhatelmas** [comment]
I agree it's too broad. I will be looking for another solution. Thanks @kytrinyx.

**Comment by kytrinyx** [comment]
Thanks @ferhatelmas!

**Comment by ferhatelmas** [comment]
@kytrinyx By the way, it might be a nice feature GitHub can provide natively.

**Comment by kytrinyx** [comment]
GitHub provides an API so that additions like this can exist. There are a lot of things that GitHub *could* provide natively, but that are better served as addons.

**Comment by ferhatelmas** [comment]
I think we can integrate [this](https://github.com/antham/gommit) to travis.

**Comment by kytrinyx** [comment]
`gommit` looks reasonable to me.

One question, though—not all commits are for a specific exercise, but if we add this, we will need to follow the format defined. What would go before the colon in that case?

**Comment by ferhatelmas** [comment]
I think it will be an area and it seems we will define them in #986.

**Comment by nealot** [comment]
https://github.com/commitizen/cz-cliz is another more popular alternative.

**Comment by bitfield** [comment]
@ferhatelmas, have you had any further thoughts on this? It's been open for a while, so I'm wondering if we should either move it forward, or close it.

**Comment by ferhatelmas** [comment]
@bitfield let me check it soon, probably there are better solution nowadays.
