### ISSUE TITLE
Run gofmt with simplify flag on generator output

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/go#981]
We already run gofmt on generator output and we can add `-s` flag to simplify it. See `gen/gen.go` for current implementation.

**Comment by ilmanzo** [comment]
in gen.go you are not using gofmt but the "go/format" package that provides source code formatting . 

Actually simplify is implemented only in the gofmt command :

https://github.com/golang/go/blob/master/src/cmd/gofmt/simplify.go

I'm not sure what could be the right approach here ?

**Comment by leenipper** [comment]
Perhaps keep current logic which uses go/format package, but after success, do a separate "gofmt -s" using os/exec package, executed from the gen/gen.go.

**Comment by ilmanzo** [comment]
IMHO this could break in a number of ways... If you have an old version of the go compiler, or if your go binary isn't in the system path you'd get an error... Do you think it's worth it ? In my knowledge , gofmt -s only covers a few corner cases, and keep in mind we are talking about code generated by a template. Can be pretty simple to implement but I'm not sure of the actual usefulness of this...

**Comment by leenipper** [comment]
Out of curiosity, I ran gofmt -s on all the generated go code files and only one file was actually simplified for the better. So it may not be worth it.

**Comment by bitfield** [comment]
I don't think it's worth it.
