### ISSUE TITLE
Improve config documentation 

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/go#985]
Upon adding new exercise, config needs to be updated in a certain fashion but we don't have any pointers or explanation in our README to do it. See [one comment](https://github.com/exercism/go/pull/980#issuecomment-353716142) from confused contributor.

**Comment by hilary** [comment]
Until the documentation gets written, you can get a decent idea of what the info is from the discussion about the [new track progression model](https://github.com/exercism/discussions/issues/159)
